/* eslint-disable */
// This file is generated by specforge. DO NOT EDIT.

import type { ApiClient, RequestOptions } from "../client";
import type { Pet } from "../models/Pet";
import type { Pets } from "../models/Pets";

export interface ListPetsParams {
  limit?: number;
}

export interface ShowPetByIdParams {
  petId: string;
}

export class PetsApi {
  constructor(private readonly client: ApiClient) {}

/**
 * List all pets
 */
  async listPets(params: ListPetsParams): Promise<Pets> {
    return await this.client.requestJson<Pets>("GET", `/pets`, { query: { "limit": params.limit } });
  }

/**
 * Create a pet
 */
  async createPets(options?: RequestOptions): Promise<void> {
    await this.client.request("POST", `/pets`);
  }

/**
 * Info for a specific pet
 */
  async showPetById(params: ShowPetByIdParams): Promise<Pet> {
    return await this.client.requestJson<Pet>("GET", `/pets/${params.petId}`);
  }

}

/** Construct the PetsApi against an existing client. */
export function petsApi(deps: { client: ApiClient }): PetsApi {
  return new PetsApi(deps.client);
}
