/* eslint-disable */
// This file is generated by specforge. DO NOT EDIT.

import type { ApiClient, RequestOptions } from "../client";
import { PetSchema, PetsSchema, validatePet, validatePets, validateResponse } from "../validate";
import type { Pet } from "../models/Pet";
import type { Pets } from "../models/Pets";

export interface ListPetsParams {
  limit?: number;
}

export interface ShowPetByIdParams {
  petId: string;
}

export class PetsApi {
  constructor(private readonly client: ApiClient) {}

/**
 * List all pets
 * @param params.limit - How many items to return at one time (max 100) (optional)
 * @returns The response body
 * @throws {ApiError} default - unexpected error
 */
  async listPets(params: ListPetsParams): Promise<Pets> {
        const result = await this.client.requestJson<Pets>("GET", `/pets`, { query: { "limit": params.limit } });
    if (this.client.validate) { validateResponse("GET", `/pets`, 200, result, PetsSchema); }
    return result;
  }

/**
 * Create a pet
 * @throws {ApiError} default - unexpected error
 */
  async createPets(options?: RequestOptions): Promise<void> {
        await this.client.request("POST", `/pets`);
  }

/**
 * Info for a specific pet
 * @param params.petId - The id of the pet to retrieve
 * @returns The response body
 * @throws {ApiError} default - unexpected error
 */
  async showPetById(params: ShowPetByIdParams): Promise<Pet> {
        const result = await this.client.requestJson<Pet>("GET", `/pets/${params.petId}`);
    if (this.client.validate) { validateResponse("GET", `/pets/${params.petId}`, 200, result, PetSchema); }
    return result;
  }

}

/** Construct the PetsApi against an existing client. */
export function petsApi(deps: { client: ApiClient }): PetsApi {
  return new PetsApi(deps.client);
}
