// Code generated by specforge. DO NOT EDIT.

package sdk

import (
	"context"
	"net/url"
)

// List all pets
func (c *Client) ListPets(ctx context.Context, limit int) (*Pets, error) {
	query := url.Values{}
	if limit != 0 {
		query.Set("limit", fmtInt(limit))
	}
	var out Pets
	if err := c.DoJSON(ctx, "GET", "/pets", query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Create a pet
func (c *Client) CreatePets(ctx context.Context) error {
	query := url.Values{}
	return c.DoJSON(ctx, "POST", "/pets", query, nil, nil)
}

// Info for a specific pet
func (c *Client) ShowPetById(ctx context.Context, petId string) (*Pet, error) {
	query := url.Values{}
	var out Pet
	if err := c.DoJSON(ctx, "GET", "/pets/" + pathEscape(petId), query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

