// Code generated by specforge. DO NOT EDIT.

package sdk

import (
	"sync"
	"time"
)

// CacheEntry holds a cached HTTP response: the ETag returned by the server,
// the raw response body, and the wall-clock time the entry was stored.
type CacheEntry struct {
	ETag      string
	Data      []byte
	Timestamp time.Time
}

// ResponseCache is a thread-safe in-memory cache for GET responses.
// Entries are keyed by full URL and expire after the configured TTL.
type ResponseCache struct {
	mu      sync.RWMutex
	entries map[string]CacheEntry
	ttl     time.Duration
}

// NewResponseCache creates a cache with the given time-to-live.
func NewResponseCache(ttl time.Duration) *ResponseCache {
	return &ResponseCache{
		entries: make(map[string]CacheEntry),
		ttl:     ttl,
	}
}

// Get returns the cached entry for url if it exists and has not expired.
// The second return value reports whether a valid entry was found.
func (c *ResponseCache) Get(url string) (CacheEntry, bool) {
	c.mu.RLock()
	entry, ok := c.entries[url]
	c.mu.RUnlock()
	if !ok {
		return CacheEntry{}, false
	}
	if time.Since(entry.Timestamp) >= c.ttl {
		// Expired — evict lazily.
		c.mu.Lock()
		delete(c.entries, url)
		c.mu.Unlock()
		return CacheEntry{}, false
	}
	return entry, true
}

// Set stores a response body and its ETag under the given URL key.
func (c *ResponseCache) Set(url string, etag string, data []byte) {
	c.mu.Lock()
	c.entries[url] = CacheEntry{
		ETag:      etag,
		Data:      data,
		Timestamp: time.Now(),
	}
	c.mu.Unlock()
}

// Clear removes all cached entries.
func (c *ResponseCache) Clear() {
	c.mu.Lock()
	c.entries = make(map[string]CacheEntry)
	c.mu.Unlock()
}

// Len returns the number of entries currently in the cache (including expired).
func (c *ResponseCache) Len() int {
	c.mu.RLock()
	defer c.mu.RUnlock()
	return len(c.entries)
}
