// Code generated by specforge. DO NOT EDIT.

package sdk

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"math/rand"
	"net/http"
	"net/url"
	"strconv"
	"strings"
	"time"
)

// AuthProvider injects credentials into an outgoing request.
// Use BearerAuth / APIKeyAuth helpers, or supply your own.
type AuthProvider interface {
	Apply(req *http.Request) error
}

// BearerAuth sends Authorization: Bearer <token>. getToken is called per request.
type BearerAuth struct {
	GetToken func(ctx context.Context) (string, error)
}

func (a BearerAuth) Apply(req *http.Request) error {
	if a.GetToken == nil {
		return nil
	}
	tok, err := a.GetToken(req.Context())
	if err != nil {
		return err
	}
	if tok != "" {
		req.Header.Set("Authorization", "Bearer "+tok)
	}
	return nil
}

// StaticBearer is a convenience AuthProvider for a fixed token.
func StaticBearer(token string) AuthProvider {
	return BearerAuth{GetToken: func(context.Context) (string, error) { return token, nil }}
}

// APIKeyAuth sends the key in a named header (e.g. "X-API-Key").
type APIKeyAuth struct {
	Header string
	GetKey func(ctx context.Context) (string, error)
}

func (a APIKeyAuth) Apply(req *http.Request) error {
	if a.GetKey == nil || a.Header == "" {
		return nil
	}
	key, err := a.GetKey(req.Context())
	if err != nil {
		return err
	}
	if key != "" {
		req.Header.Set(a.Header, key)
	}
	return nil
}

// ResponseTransformer transforms response data before it reaches the application.
// Transformers are applied in order after JSON decoding.
type ResponseTransformer interface {
	Transform(response any) any
}

// Client is the generated HTTP client for Swagger Petstore.
type Client struct {
	BaseURL    string
	HTTPClient *http.Client
	Header     http.Header
	Auth       AuthProvider
	// Retry controls automatic retries on transient failures. Zero value = defaults.
	Retry RetryOptions
	// Timeout is the per-attempt request timeout. Zero uses HTTPClient.Timeout
	// (or 30s if that is also zero). Context deadlines still win.
	Timeout time.Duration
	// MaxConcurrent bounds in-flight requests. 0 = unlimited.
	MaxConcurrent int
	// Dedupe coalesces identical in-flight safe (GET/HEAD/OPTIONS) requests. Default true.
	Dedupe bool
	// Idempotency auto-attaches Idempotency-Key on POST/PUT/PATCH/DELETE. Default true.
	Idempotency bool
	// Validation enables runtime request/response validation against the OpenAPI schema.
	Validation bool
	// Cache enables GET response caching with ETag/conditional requests. Nil = disabled.
	Cache *ResponseCache
	// RateLimiter controls request throughput. Nil = no rate limiting.
	RateLimiter RateLimiter
	// Logger provides structured logging for SDK lifecycle events.
	Logger Logger
	// Telemetry provides hooks for request lifecycle observability.
	Telemetry TelemetryHooks
	// Middleware runs around each HTTP attempt (after auth headers are applied).
	Middleware []Middleware
	// StreamMiddleware runs before streaming requests (header-only modifications).
	StreamMiddleware []StreamMiddleware
	// ResponseTransformers are applied in order after JSON decoding of successful responses.
	ResponseTransformers []ResponseTransformer
	// RequestInterceptors are applied in order before each request body is serialized.
	RequestInterceptors []RequestInterceptor
	// ResponseInterceptors are applied in order after each response body is deserialized.
	ResponseInterceptors []ResponseInterceptor

	sem     *Semaphore
	deduper *RequestDeduper
	// Deprecated simple fields kept for back-compat; prefer Auth.
	BearerToken  string
	APIKey       string
	APIKeyHeader string
}

// NewClient constructs a Client pointed at the spec's default base URL.
func NewClient() *Client {
	return &Client{
		BaseURL:      "http://petstore.swagger.io/v1",
		HTTPClient:   &http.Client{Timeout: 30 * time.Second},
		Header:       make(http.Header),
		Retry:        DefaultRetryOptions(),
		Timeout:      30 * time.Second,
		Dedupe:       true,
		Idempotency:  true,
		deduper:      NewRequestDeduper(),
		APIKeyHeader: "",
	}
}

// WithBaseURL overrides the default base URL.
func (c *Client) WithBaseURL(u string) *Client {
	c.BaseURL = strings.TrimRight(u, "/")
	return c
}

// WithBearerToken configures a static HTTP bearer token (sets Auth).
func (c *Client) WithBearerToken(token string) *Client {
	c.BearerToken = token
	c.Auth = StaticBearer(token)
	return c
}

// WithAuth sets a custom auth provider (called on every request).
func (c *Client) WithAuth(a AuthProvider) *Client {
	c.Auth = a
	return c
}

// WithAPIKey configures a static API key header.
func (c *Client) WithAPIKey(header, key string) *Client {
	c.APIKeyHeader = header
	c.APIKey = key
	c.Auth = APIKeyAuth{
		Header: header,
		GetKey: func(context.Context) (string, error) { return key, nil },
	}
	return c
}

// WithRetry overrides retry policy.
func (c *Client) WithRetry(r RetryOptions) *Client {
	c.Retry = r
	return c
}

// WithTimeout sets the per-attempt timeout.
func (c *Client) WithTimeout(d time.Duration) *Client {
	c.Timeout = d
	return c
}

// WithMaxConcurrent bounds in-flight requests (0 = unlimited).
func (c *Client) WithMaxConcurrent(n int) *Client {
	c.MaxConcurrent = n
	if n > 0 {
		c.sem = NewSemaphore(n)
	} else {
		c.sem = nil
	}
	return c
}

// WithDedupe enables/disables in-flight GET/HEAD/OPTIONS coalescing.
func (c *Client) WithDedupe(on bool) *Client {
	c.Dedupe = on
	return c
}

// Use appends middleware (applied in registration order).
func (c *Client) Use(mw ...Middleware) *Client {
	c.Middleware = append(c.Middleware, mw...)
	return c
}

// UseStream appends stream middleware (header-only modifications before streaming).
func (c *Client) UseStream(mw ...StreamMiddleware) *Client {
	c.StreamMiddleware = append(c.StreamMiddleware, mw...)
	return c
}

// WithIdempotency enables/disables auto Idempotency-Key on unsafe methods.
func (c *Client) WithIdempotency(on bool) *Client {
	c.Idempotency = on
	return c
}

// WithValidation enables/disables runtime request/response validation against the OpenAPI schema.
func (c *Client) WithValidation(on bool) *Client {
	c.Validation = on
	return c
}

// WithCache enables GET response caching with ETag/conditional requests.
// Pass a TTL of 0 to use the default (60s).
func (c *Client) WithCache(ttl time.Duration) *Client {
	if ttl <= 0 {
		ttl = 60 * time.Second
	}
	c.Cache = NewResponseCache(ttl)
	return c
}

// WithRateLimiter sets a rate limiter applied before each request.
func (c *Client) WithRateLimiter(limiter RateLimiter) *Client {
	c.RateLimiter = limiter
	return c
}

// WithTelemetry sets telemetry hooks for request lifecycle observability.
func (c *Client) WithTelemetry(hooks TelemetryHooks) *Client {
	c.Telemetry = hooks
	return c
}

// WithHTTPClient replaces the underlying *http.Client.
func (c *Client) WithHTTPClient(hc *http.Client) *Client {
	c.HTTPClient = hc
	return c
}

// WithResponseTransformers sets response transformers applied in order after JSON decoding.
func (c *Client) WithResponseTransformers(transformers ...ResponseTransformer) *Client {
	c.ResponseTransformers = append(c.ResponseTransformers, transformers...)
	return c

// WithRequestInterceptors sets request interceptors applied in order before each request body is serialized.
func (c *Client) WithRequestInterceptors(interceptors ...RequestInterceptor) *Client {
	c.RequestInterceptors = append(c.RequestInterceptors, interceptors...)
	return c
}

// WithResponseInterceptors sets response interceptors applied in order after each response body is deserialized.
func (c *Client) WithResponseInterceptors(interceptors ...ResponseInterceptor) *Client {
	c.ResponseInterceptors = append(c.ResponseInterceptors, interceptors...)
	return c
}
}

// DoJSON issues an HTTP request (concurrency + dedupe + retry + middleware),
// JSON-decodes a successful response into out (when non-nil), and returns a
// non-nil error for non-2xx statuses.
func (c *Client) DoJSON(ctx context.Context, method, path string, query url.Values, body any, out any) error {
	u := c.BaseURL + path
	if len(query) > 0 {
		u = u + "?" + query.Encode()
	}

	var bodyBytes []byte
	if body != nil {
	// Apply request interceptors before serializing the body.
	for _, i := range c.RequestInterceptors {
		body = i.Transform(body)
	}
		var err error
		bodyBytes, err = json.Marshal(body)
		if err != nil {
			return fmt.Errorf("marshal body: %w", err)
		}
	}

	// Concurrency gate (optional).
	if c.MaxConcurrent > 0 {
		if c.sem == nil {
			c.sem = NewSemaphore(c.MaxConcurrent)
		}
		if err := c.sem.Acquire(ctx); err != nil {
			return err
		}
		defer c.sem.Release()
	}

	// Rate limiting: wait for permission before proceeding.
	if c.RateLimiter != nil {
		if err := c.RateLimiter.Acquire(ctx); err != nil {
			return err
		}
	}

	// Logger: request start.
	if c.Logger != nil {
		c.Logger.Infof("[request] %s %s", method, path)
	}

	// Telemetry: request start.
	startTime := time.Now()
	if c.Telemetry != nil {
		c.Telemetry.OnRequestStart(method, path)
	}

	// --- ETag cache: check for GET requests ---
	isGet := strings.ToUpper(method) == "GET"
	var cachedEntry CacheEntry
	var hasCache bool
	if isGet && c.Cache != nil {
		cachedEntry, hasCache = c.Cache.Get(u)
		if hasCache {
			c.Header.Set("If-None-Match", cachedEntry.ETag)
			if c.Logger != nil {
				c.Logger.Debugf("[cache] HIT %s %s", method, path)
			}
			if c.Telemetry != nil {
				c.Telemetry.OnCacheHit(method, path)
			}
		} else {
			if c.Logger != nil {
				c.Logger.Debugf("[cache] MISS %s %s", method, path)
			}
			if c.Telemetry != nil {
				c.Telemetry.OnCacheMiss(method, path)
			}
		}
	}

	// Stable idempotency key for the whole retry loop (generated once).
	var idemKey string
	if c.Idempotency && IsIdempotencyCandidate(method) {
		idemKey = NewIdempotencyKey()
	}

	var respETag string

	run := func() ([]byte, int, error) {
		d, s, e, err := c.doWithRetry(ctx, method, u, bodyBytes, body != nil, idemKey)
		if err == nil {
			respETag = e
		}
		return d, s, err
	}

	var data []byte
	var status int
	var err error
	if c.Dedupe && isDedupeMethod(method) {
		if c.deduper == nil {
			c.deduper = NewRequestDeduper()
		}
		data, status, err = c.deduper.Do(method+" "+u, run)
	} else {
		data, status, err = run()
	}

	// Clean up the If-None-Match header we may have set.
	if hasCache {
		c.Header.Del("If-None-Match")
	}

	if err != nil {
		if c.Telemetry != nil {
			c.Telemetry.OnRequestError(method, path, time.Since(startTime).Milliseconds(), err)
		}
		return err
	}

	// Logger: response received.
	if c.Logger != nil {
		c.Logger.Infof("[response] %s %s -> %d", method, path, status)
	}

	// Telemetry: successful response.
	if c.Telemetry != nil {
		c.Telemetry.OnRequestEnd(method, path, time.Since(startTime).Milliseconds(), status)
	}

	// --- ETag cache: handle 304 Not Modified and update on 200 ---
	if isGet && c.Cache != nil {
		if status == http.StatusNotModified && hasCache {
			// Return cached data.
			data = cachedEntry.Data
			status = http.StatusOK
		} else if status >= 200 && status < 300 && respETag != "" {
			// Store response in cache for future conditional requests.
			c.Cache.Set(u, respETag, data)
		}
	}

	if out == nil || status == http.StatusNoContent || len(data) == 0 {
		return nil
	}
	// Apply response transformers to raw data before decoding.
	for _, t := range c.ResponseTransformers {
		transformed := t.Transform(data)
		if b, ok := transformed.([]byte); ok {
			data = b
		}
	}
	// Apply response interceptors before decoding.
	for _, i := range c.ResponseInterceptors {
		transformed := i.Transform(data)
		if b, ok := transformed.([]byte); ok {
			data = b
		}
	}
	if err := json.Unmarshal(data, out); err != nil {
		return fmt.Errorf("decode response: %w", err)
	}
	return nil
}

// DoStream performs a single request and returns the raw *http.Response without
// draining the body — use for SSE / chunked endpoints with StreamSse / StreamLines.
// The caller must close res.Body. Retries are not applied (streaming is not replayable).
func (c *Client) DoStream(ctx context.Context, method, path string, query url.Values, body any) (*http.Response, error) {
	u := c.BaseURL + path
	if len(query) > 0 {
		u = u + "?" + query.Encode()
	}
	var bodyBytes []byte
	if body != nil {
		var err error
		bodyBytes, err = json.Marshal(body)
		if err != nil {
			return nil, fmt.Errorf("marshal body: %w", err)
		}
	}
	if c.MaxConcurrent > 0 {
		if c.sem == nil {
			c.sem = NewSemaphore(c.MaxConcurrent)
		}
		if err := c.sem.Acquire(ctx); err != nil {
			return nil, err
		}
		// Release when body is closed — wrap via helper below is complex; release
		// immediately after headers for stream start. Callers with high fan-out
		// should set MaxConcurrent carefully for streams.
		defer c.sem.Release()
	}
	// Rate limiting: wait for permission before proceeding.
	if c.RateLimiter != nil {
		if err := c.RateLimiter.Acquire(ctx); err != nil {
			return nil, err
		}
	}
	var idemKey string
	if c.Idempotency && IsIdempotencyCandidate(method) {
		idemKey = NewIdempotencyKey()
	}
	return c.doOnceStream(ctx, method, u, bodyBytes, body != nil, idemKey)
}

func (c *Client) doWithRetry(ctx context.Context, method, u string, bodyBytes []byte, hasBody bool, idemKey string) ([]byte, int, string, error) {
	retry := c.Retry
	if retry.MaxRetries == 0 && retry.BaseDelay == 0 && len(retry.RetryOnStatuses) == 0 {
		retry = DefaultRetryOptions()
	}

	var lastErr error
	for attempt := 0; attempt <= retry.MaxRetries; attempt++ {
		if attempt > 0 {
			delay := backoffDelay(attempt-1, retry)
			timer := time.NewTimer(delay)
			select {
			case <-ctx.Done():
				timer.Stop()
				return nil, 0, "", ctx.Err()
			case <-timer.C:
			}
		}

		data, status, etag, err := c.doOnce(ctx, method, u, bodyBytes, hasBody, idemKey)
		if err == nil {
			return data, status, etag, nil
		}
		lastErr = err
		if !isRetriable(method, err, retry) || attempt == retry.MaxRetries {
			return nil, 0, "", err
		}
		// Logger: retry notification.
		if c.Logger != nil {
			c.Logger.Warnf("[retry] %s %s error=%v, attempt %d/%d", method, u, err, attempt+2, retry.MaxRetries+1)
		}
		// Telemetry: retry notification.
		if c.Telemetry != nil {
			c.Telemetry.OnRetry(method, u, attempt+1, err)
		}
	}
	return nil, 0, "", lastErr
}

func (c *Client) buildHeaders(ctx context.Context, method, u string, hasBody bool, idemKey string) (http.Header, error) {
	headers := make(http.Header)
	headers.Set("Accept", "application/json")
	if hasBody {
		headers.Set("Content-Type", "application/json")
	}
	for k, vs := range c.Header {
		for _, v := range vs {
			headers.Add(k, v)
		}
	}
	tmp, _ := http.NewRequestWithContext(ctx, method, u, nil)
	tmp.Header = headers
	if c.Auth != nil {
		if err := c.Auth.Apply(tmp); err != nil {
			return nil, err
		}
	} else {
		if c.BearerToken != "" {
			tmp.Header.Set("Authorization", "Bearer "+c.BearerToken)
		}
		if c.APIKey != "" && c.APIKeyHeader != "" {
			tmp.Header.Set(c.APIKeyHeader, c.APIKey)
		}
	}
	if idemKey != "" && tmp.Header.Get(IdempotencyHeader) == "" {
		tmp.Header.Set(IdempotencyHeader, idemKey)
	}
	return tmp.Header, nil
}

func (c *Client) doOnce(ctx context.Context, method, u string, bodyBytes []byte, hasBody bool, idemKey string) ([]byte, int, string, error) {
	reqCtx := ctx
	var cancel context.CancelFunc
	timeout := c.Timeout
	if timeout <= 0 && c.HTTPClient != nil {
		timeout = c.HTTPClient.Timeout
	}
	if timeout <= 0 {
		timeout = 30 * time.Second
	}
	if timeout > 0 {
		reqCtx, cancel = context.WithTimeout(ctx, timeout)
		defer cancel()
	}

	headers, err := c.buildHeaders(reqCtx, method, u, hasBody, idemKey)
	if err != nil {
		return nil, 0, "", err
	}

	mwReq := &MiddlewareRequest{
		Method:  method,
		URL:     u,
		Headers: headers,
		Body:    bodyBytes,
	}

	handler := ComposeMiddleware(c.Middleware, func(ctx context.Context, req *MiddlewareRequest) (*MiddlewareResponse, error) {
		var rdr io.Reader
		if len(req.Body) > 0 {
			rdr = bytes.NewReader(req.Body)
		}
		httpReq, err := http.NewRequestWithContext(ctx, req.Method, req.URL, rdr)
		if err != nil {
			return nil, err
		}
		httpReq.Header = req.Headers.Clone()
		res, err := c.HTTPClient.Do(httpReq)
		if err != nil {
			return nil, err
		}
		defer res.Body.Close()
		data, err := io.ReadAll(res.Body)
		if err != nil {
			return nil, err
		}
		return &MiddlewareResponse{StatusCode: res.StatusCode, Header: res.Header.Clone(), Body: data}, nil
	})

	mwRes, err := handler(reqCtx, mwReq)
	if err != nil {
		return nil, 0, "", err
	}
	etag := mwRes.Header.Get("Etag")
	if mwRes.StatusCode < 200 || mwRes.StatusCode >= 300 {
		// Pass through 304 as-is so DoJSON can handle it.
		if mwRes.StatusCode == http.StatusNotModified {
			return mwRes.Body, mwRes.StatusCode, etag, nil
		}
		return nil, 0, "", &APIError{StatusCode: mwRes.StatusCode, Body: mwRes.Body, URL: u}
	}
	return mwRes.Body, mwRes.StatusCode, etag, nil
}

func (c *Client) doOnceStream(ctx context.Context, method, u string, bodyBytes []byte, hasBody bool, idemKey string) (*http.Response, error) {
	headers, err := c.buildHeaders(ctx, method, u, hasBody, idemKey)
	if err != nil {
		return nil, err
	}
	// Apply stream middleware.
	for _, mw := range c.StreamMiddleware {
		mwReq := &MiddlewareRequest{Method: method, URL: u, Headers: headers.Clone(), Body: bodyBytes}
		if err := ctx.Err(); err != nil {
			return nil, err
		}
		if err := mw(ctx, mwReq); err != nil {
			return nil, err
		}
		headers = mwReq.Headers
	}
	if headers.Get("Accept") == "application/json" {
		headers.Set("Accept", "text/event-stream, application/json")
	}
	var rdr io.Reader
	if len(bodyBytes) > 0 {
		rdr = bytes.NewReader(bodyBytes)
	}
	httpReq, err := http.NewRequestWithContext(ctx, method, u, rdr)
	if err != nil {
		return nil, err
	}
	httpReq.Header = headers
	res, err := c.HTTPClient.Do(httpReq)
	if err != nil {
		return nil, err
	}
	if res.StatusCode < 200 || res.StatusCode >= 300 {
		defer res.Body.Close()
		data, _ := io.ReadAll(res.Body)
		return nil, &APIError{StatusCode: res.StatusCode, Body: data, URL: u}
	}
	return res, nil
}

// APIError is returned for non-2xx HTTP responses.
type APIError struct {
	StatusCode int
	Body       []byte
	URL        string
}

func (e *APIError) Error() string {
	return fmt.Sprintf("HTTP %d from %s: %s", e.StatusCode, e.URL, truncate(string(e.Body), 200))
}

// Status returns the HTTP status for errors that carry one.
func (e *APIError) Status() int { return e.StatusCode }

func truncate(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n] + "…"
}

// pathEscape escapes a single path segment.
func pathEscape(s string) string {
	return url.PathEscape(s)
}

func queryValues(pairs ...string) url.Values {
	q := url.Values{}
	for i := 0; i+1 < len(pairs); i += 2 {
		if pairs[i+1] != "" {
			q.Set(pairs[i], pairs[i+1])
		}
	}
	return q
}

func fmtInt(v int) string       { return strconv.Itoa(v) }
func fmtInt64(v int64) string   { return strconv.FormatInt(v, 10) }
func fmtBool(v bool) string     { return strconv.FormatBool(v) }
func fmtFloat(v float64) string { return strconv.FormatFloat(v, 'f', -1, 64) }

// anyString stringifies query/path values that aren't plain scalars.
func anyString(v any) string {
	switch t := v.(type) {
	case string:
		return t
	case fmt.Stringer:
		return t.String()
	default:
		return fmt.Sprint(v)
	}
}

// silence unused-import guards for packages used only in some generated shapes.
var (
	_ = rand.Float64
	_ = time.Now
)
