// Code generated by specforge. DO NOT EDIT.

package sdk

import "context"

// Semaphore bounds the number of in-flight requests.
type Semaphore struct {
	ch chan struct{}
}

// NewSemaphore creates a semaphore with the given maximum concurrency.
// panics if max <= 0.
func NewSemaphore(max int) *Semaphore {
	if max <= 0 {
		panic("max concurrent must be > 0")
	}
	return &Semaphore{ch: make(chan struct{}, max)}
}

// Acquire blocks until a slot is free or ctx is cancelled.
func (s *Semaphore) Acquire(ctx context.Context) error {
	select {
	case s.ch <- struct{}{}:
		return nil
	case <-ctx.Done():
		return ctx.Err()
	}
}

// Release frees a slot. Safe to call even if Acquire failed (no-op when empty).
func (s *Semaphore) Release() {
	select {
	case <-s.ch:
	default:
	}
}
