// Code generated by specforge. DO NOT EDIT.

package sdk

import (
	"strings"
	"sync"
)

// RequestDeduper coalesces identical in-flight safe requests so concurrent
// callers of the same GET share one round-trip.
type RequestDeduper struct {
	mu   sync.Mutex
	inflight map[string]*dedupeCall
}

type dedupeCall struct {
	wg     sync.WaitGroup
	data   []byte
	status int
	err    error
}

// NewRequestDeduper constructs an empty deduper.
func NewRequestDeduper() *RequestDeduper {
	return &RequestDeduper{inflight: make(map[string]*dedupeCall)}
}

func isDedupeMethod(method string) bool {
	switch strings.ToUpper(method) {
	case "GET", "HEAD", "OPTIONS":
		return true
	default:
		return false
	}
}

// Do runs fn, coalescing concurrent calls with the same key.
func (d *RequestDeduper) Do(key string, fn func() ([]byte, int, error)) ([]byte, int, error) {
	d.mu.Lock()
	if c, ok := d.inflight[key]; ok {
		d.mu.Unlock()
		c.wg.Wait()
		return c.data, c.status, c.err
	}
	c := &dedupeCall{}
	c.wg.Add(1)
	d.inflight[key] = c
	d.mu.Unlock()

	data, status, err := fn()
	c.data, c.status, c.err = data, status, err
	c.wg.Done()

	d.mu.Lock()
	delete(d.inflight, key)
	d.mu.Unlock()
	return data, status, err
}
