// Code generated by specforge. DO NOT EDIT.

package sdk

import (
	"crypto/rand"
	"fmt"
	"strings"
)

// IdempotencyHeader is the header name used for unsafe-method keys.
const IdempotencyHeader = "Idempotency-Key"

// IsIdempotencyCandidate reports whether method benefits from an idempotency key.
func IsIdempotencyCandidate(method string) bool {
	switch strings.ToUpper(method) {
	case "POST", "PUT", "PATCH", "DELETE":
		return true
	default:
		return false
	}
}

// NewIdempotencyKey returns a random RFC-4122 version-4 UUID string.
func NewIdempotencyKey() string {
	var b [16]byte
	if _, err := rand.Read(b[:]); err != nil {
		// Extremely unlikely; fall back to a timestamp-ish unique string.
		return fmt.Sprintf("key-%d", nonceFallback())
	}
	b[6] = (b[6] & 0x0f) | 0x40
	b[8] = (b[8] & 0x3f) | 0x80
	return fmt.Sprintf("%x-%x-%x-%x-%x", b[0:4], b[4:6], b[6:8], b[8:10], b[10:16])
}

var nonceCounter uint64

func nonceFallback() uint64 {
	nonceCounter++
	return nonceCounter
}
