// Code generated by specforge. DO NOT EDIT.

package sdk

// RequestInterceptor transforms the request body before it is serialized and sent.
// Return the (possibly modified) body.
type RequestInterceptor interface {
	Transform(body interface{}) interface{}
}

// ResponseInterceptor transforms the response body after it is deserialized.
// Return the (possibly modified) body.
type ResponseInterceptor interface {
	Transform(body interface{}) interface{}
}
