// Code generated by specforge. DO NOT EDIT.

package sdk

import (
	"fmt"
	"log"
	"os"
)

// Logger is the structured logging interface for SDK lifecycle events.
// Implement this to plug in your own logger; the SDK logs requests,
// responses, retries, and cache hits/misses.
type Logger interface {
	Debugf(format string, args ...any)
	Infof(format string, args ...any)
	Warnf(format string, args ...any)
	Errorf(format string, args ...any)
}

// ConsoleLogger delegates to the standard log package.
type ConsoleLogger struct {
	DebugLogger *log.Logger
	InfoLogger  *log.Logger
	WarnLogger  *log.Logger
	ErrorLogger *log.Logger
}

// NewConsoleLogger creates a Logger that writes to stderr via the standard log package.
func NewConsoleLogger() *ConsoleLogger {
	return &ConsoleLogger{
		DebugLogger: log.New(os.Stderr, "[DEBUG] ", log.LstdFlags),
		InfoLogger:  log.New(os.Stderr, "[INFO]  ", log.LstdFlags),
		WarnLogger:  log.New(os.Stderr, "[WARN]  ", log.LstdFlags),
		ErrorLogger: log.New(os.Stderr, "[ERROR] ", log.LstdFlags),
	}
}

func (l *ConsoleLogger) Debugf(format string, args ...any) {
	l.DebugLogger.Output(2, fmt.Sprintf(format, args...))
}

func (l *ConsoleLogger) Infof(format string, args ...any) {
	l.InfoLogger.Output(2, fmt.Sprintf(format, args...))
}

func (l *ConsoleLogger) Warnf(format string, args ...any) {
	l.WarnLogger.Output(2, fmt.Sprintf(format, args...))
}

func (l *ConsoleLogger) Errorf(format string, args ...any) {
	l.ErrorLogger.Output(2, fmt.Sprintf(format, args...))
}

// noopLogger discards all log messages.
type noopLogger struct{}

func (noopLogger) Debugf(string, ...any) {}
func (noopLogger) Infof(string, ...any)  {}
func (noopLogger) Warnf(string, ...any)  {}
func (noopLogger) Errorf(string, ...any) {}

// NoopLogger is a Logger that discards all messages.
var NoopLogger Logger = noopLogger{}
