// Code generated by specforge. DO NOT EDIT.

package sdk

import (
	"context"
	"net/http"
)

// MiddlewareRequest is the mutable request descriptor passed through middleware.
type MiddlewareRequest struct {
	Method  string
	URL     string
	Headers http.Header
	Body    []byte
}

// MiddlewareResponse is the raw response after the transport round-trip.
type MiddlewareResponse struct {
	StatusCode int
	Header     http.Header
	Body       []byte
}

// Middleware observes or rewrites a request/response. Call next to continue.
type Middleware func(ctx context.Context, req *MiddlewareRequest, next func(context.Context, *MiddlewareRequest) (*MiddlewareResponse, error)) (*MiddlewareResponse, error)

// ComposeMiddleware chains middlewares around a terminal dispatch function.
func ComposeMiddleware(
	middlewares []Middleware,
	dispatch func(context.Context, *MiddlewareRequest) (*MiddlewareResponse, error),
	) func(context.Context, *MiddlewareRequest) (*MiddlewareResponse, error) {
	h := dispatch
	// Apply in reverse so registration order is outer-to-inner left-to-right.
	for i := len(middlewares) - 1; i >= 0; i-- {
		mw := middlewares[i]
		next := h
		h = func(ctx context.Context, req *MiddlewareRequest) (*MiddlewareResponse, error) {
			return mw(ctx, req, next)
		}
	}
	return h
}

// StreamMiddleware can observe or modify a request before streaming begins.
// It cannot read the response body. Return a non-nil error to abort.
type StreamMiddleware func(ctx context.Context, req *MiddlewareRequest) error
