// Code generated by specforge. DO NOT EDIT.

package sdk

type Error struct {
	Code int `json:"code"`
	Message string `json:"message"`
}

type Pet struct {
	Id int `json:"id"`
	Name string `json:"name"`
	Tag string `json:"tag,omitempty"`
}

type Pets = []Pet

