// Code generated by specforge. DO NOT EDIT.

package sdk

import "context"

// CursorPage is the shape expected by CursorPaginate.
type CursorPage[T any] struct {
	Items      []T
	NextCursor *string
}

// CursorPaginate walks a cursor-based list endpoint until NextCursor is nil/empty.
//
//	err := CursorPaginate(ctx, func(ctx context.Context, cursor *string) (CursorPage[Pet], error) {
//	    // call a generated list method, mapping its response into CursorPage
//	    return page, nil
//	}, func(items []Pet) error {
//	    // handle each page
//	    return nil
//	})
func CursorPaginate[T any](
	ctx context.Context,
	fetch func(ctx context.Context, cursor *string) (CursorPage[T], error),
	handle func(items []T) error,
) error {
	var cursor *string
	for {
		if err := ctx.Err(); err != nil {
			return err
		}
		page, err := fetch(ctx, cursor)
		if err != nil {
			return err
		}
		if err := handle(page.Items); err != nil {
			return err
		}
		if page.NextCursor == nil || *page.NextCursor == "" {
			return nil
		}
		cursor = page.NextCursor
	}
}

// OffsetPage is the shape expected by OffsetPaginate.
type OffsetPage[T any] struct {
	Items []T
	Total *int
}

// OffsetPaginate walks an offset/limit list endpoint until a short page is returned.
func OffsetPaginate[T any](
	ctx context.Context,
	limit int,
	fetch func(ctx context.Context, offset, limit int) (OffsetPage[T], error),
	handle func(items []T) error,
) error {
	if limit <= 0 {
		limit = 50
	}
	offset := 0
	for {
		if err := ctx.Err(); err != nil {
			return err
		}
		page, err := fetch(ctx, offset, limit)
		if err != nil {
			return err
		}
		if err := handle(page.Items); err != nil {
			return err
		}
		if len(page.Items) < limit {
			return nil
		}
		offset += len(page.Items)
	}
}
