// Code generated by specforge. DO NOT EDIT.

package sdk

import (
	"context"
	"sync"
	"time"
)

// RateLimiter controls request throughput. The client calls Acquire before each
// request; the call blocks until the request is allowed to proceed.
type RateLimiter interface {
	Acquire(ctx context.Context) error
}

// TokenBucket implements a token-bucket rate limiter. Tokens refill at a constant
// rate up to a maximum. Each request consumes one token; when empty, Acquire
// blocks until a token is available.
type TokenBucket struct {
	mu         sync.Mutex
	tokens     float64
	maxTokens  float64
	refillRate float64 // tokens per second
	lastRefill time.Time
}

// NewTokenBucket creates a token bucket with the given burst capacity and refill rate (tokens/sec).
func NewTokenBucket(maxTokens int, refillRate float64) *TokenBucket {
	return &TokenBucket{
		tokens:     float64(maxTokens),
		maxTokens:  float64(maxTokens),
		refillRate: refillRate,
		lastRefill: time.Now(),
	}
}

// Acquire blocks until a token is available or ctx is cancelled.
func (tb *TokenBucket) Acquire(ctx context.Context) error {
	tb.mu.Lock()
	defer tb.mu.Unlock()
	tb.refill()
	for tb.tokens < 1 {
		// Wait for a refill.
		tb.mu.Unlock()
		select {
		case <-ctx.Done():
			return ctx.Err()
		case <-time.After(100 * time.Millisecond):
		}
		tb.mu.Lock()
		tb.refill()
	}
	tb.tokens -= 1
	return nil
}

func (tb *TokenBucket) refill() {
	now := time.Now()
	elapsed := now.Sub(tb.lastRefill).Seconds()
	tb.tokens = minFloat(tb.maxTokens, tb.tokens+elapsed*tb.refillRate)
	tb.lastRefill = now
}

// SlidingWindow implements a sliding-window rate limiter. Allows at most
// maxRequests within any rolling window. When the limit is reached, Acquire
// blocks until the oldest request in the window expires.
type SlidingWindow struct {
	mu          sync.Mutex
	requests    []time.Time
	maxRequests int
	window      time.Duration
}

// NewSlidingWindow creates a sliding window limiter with the given max requests and window duration.
func NewSlidingWindow(maxRequests int, window time.Duration) *SlidingWindow {
	return &SlidingWindow{
		maxRequests: maxRequests,
		window:      window,
	}
}

// Acquire blocks until a request slot is available or ctx is cancelled.
func (sw *SlidingWindow) Acquire(ctx context.Context) error {
	sw.mu.Lock()
	defer sw.mu.Unlock()
	sw.evict()
	for len(sw.requests) >= sw.maxRequests {
		// Wait until the oldest request expires.
		oldest := sw.requests[0]
		wait := sw.window - time.Since(oldest)
		sw.mu.Unlock()
		select {
		case <-ctx.Done():
			return ctx.Err()
		case <-time.After(wait):
		}
		sw.mu.Lock()
		sw.evict()
	}
	sw.requests = append(sw.requests, time.Now())
	return nil
}

func (sw *SlidingWindow) evict() {
	cutoff := time.Now().Add(-sw.window)
	n := 0
	for _, t := range sw.requests {
		if t.After(cutoff) {
			break
		}
		n++
	}
	sw.requests = sw.requests[n:]
}

func minFloat(a, b float64) float64 {
	if a < b {
		return a
	}
	return b
}
