// Code generated by specforge. DO NOT EDIT.

package sdk

import (
	"math/rand"
	"net"
	"net/http"
	"strings"
	"time"
)

// RetryOptions controls automatic retries around DoJSON.
type RetryOptions struct {
	// MaxRetries is attempts AFTER the first try. Default 2 (3 total tries).
	MaxRetries int
	// BaseDelay is the exponential base. Default 500ms.
	BaseDelay time.Duration
	// MaxDelay caps the per-attempt sleep. Default 8s.
	MaxDelay time.Duration
	// RetryOnStatuses lists HTTP statuses that should be retried.
	// Default: 408, 429, 502, 503, 504.
	RetryOnStatuses []int
}

// DefaultRetryOptions returns the recommended defaults.
func DefaultRetryOptions() RetryOptions {
	return RetryOptions{
		MaxRetries:      2,
		BaseDelay:       500 * time.Millisecond,
		MaxDelay:        8 * time.Second,
		RetryOnStatuses: []int{408, 429, 502, 503, 504},
	}
}

// isRetriableMethod is true for methods that are safe to replay by default.
func isRetriableMethod(method string) bool {
	switch strings.ToUpper(method) {
	case http.MethodGet, http.MethodHead, http.MethodPut, http.MethodDelete, http.MethodOptions:
		return true
	default:
		return false
	}
}

func isRetriable(method string, err error, opts RetryOptions) bool {
	if err == nil {
		return false
	}
	// Transport / timeout / temporary network errors: always retriable.
	if _, ok := err.(net.Error); ok {
		return true
	}
	if strings.Contains(err.Error(), "timeout") || strings.Contains(err.Error(), "connection reset") {
		return true
	}
	// HTTP status errors: only if method is safe and status is listed.
	if ae, ok := err.(*APIError); ok {
		if !isRetriableMethod(method) {
			return false
		}
		for _, s := range opts.RetryOnStatuses {
			if ae.StatusCode == s {
				return true
			}
		}
		return false
	}
	return false
}

// backoffDelay returns a full-jitter sleep for the given zero-based retry attempt.
func backoffDelay(attempt int, opts RetryOptions) time.Duration {
	base := opts.BaseDelay
	if base <= 0 {
		base = 500 * time.Millisecond
	}
	max := opts.MaxDelay
	if max <= 0 {
		max = 8 * time.Second
	}
	// ceiling = min(base * 2^attempt, max)
	ceiling := base
	for i := 0; i < attempt; i++ {
		if ceiling >= max/2 {
			ceiling = max
			break
		}
		ceiling *= 2
	}
	if ceiling > max {
		ceiling = max
	}
	if ceiling <= 0 {
		return 0
	}
	// Full jitter: random in [0, ceiling).
	return time.Duration(rand.Int63n(int64(ceiling)))
}
