// Code generated by specforge. DO NOT EDIT.

package sdk

import (
	"bufio"
	"bytes"
	"io"
	"net/http"
	"strings"
)

// ServerSentEvent is one SSE message (blank-line delimited).
type ServerSentEvent struct {
	Event string
	Data  string
	ID    string
}

// StreamLines yields text lines from an HTTP response body.
// The caller must close res.Body (StreamLines does not).
func StreamLines(res *http.Response) *bufio.Scanner {
	return bufio.NewScanner(res.Body)
}

// StreamSse parses a text/event-stream body into ServerSentEvent values.
// Call next() until false; then check Err(). Closes nothing — caller closes Body.
type SseIterator struct {
	sc   *bufio.Scanner
	cur  ServerSentEvent
	err  error
	done bool
}

// NewSseIterator starts an SSE iterator over res.Body.
func NewSseIterator(res *http.Response) *SseIterator {
	sc := bufio.NewScanner(res.Body)
	// Allow large events (1 MiB).
	buf := make([]byte, 0, 64*1024)
	sc.Buffer(buf, 1024*1024)
	return &SseIterator{sc: sc}
}

// Next advances to the next event. Returns false on EOF or error.
func (it *SseIterator) Next() bool {
	if it.done {
		return false
	}
	event := "message"
	var data []string
	var id string
	for it.sc.Scan() {
		line := it.sc.Text()
		if line == "" {
			if len(data) > 0 || event != "message" {
				it.cur = ServerSentEvent{
					Event: event,
					Data:  strings.Join(data, "\n"),
					ID:    id,
				}
				return true
			}
			event = "message"
			data = nil
			id = ""
			continue
		}
		if strings.HasPrefix(line, ":") {
			continue // comment
		}
		field, value, _ := strings.Cut(line, ":")
		value = strings.TrimPrefix(value, " ")
		switch field {
		case "event":
			event = value
		case "data":
			data = append(data, value)
		case "id":
			id = value
		case "retry":
			// ignored — caller owns reconnect policy
		}
	}
	if err := it.sc.Err(); err != nil {
		it.err = err
		it.done = true
		return false
	}
	// Flush trailing event without blank line terminator.
	if len(data) > 0 || event != "message" {
		it.cur = ServerSentEvent{
			Event: event,
			Data:  strings.Join(data, "\n"),
			ID:    id,
		}
		it.done = true
		return true
	}
	it.done = true
	return false
}

// Event returns the current event after a successful Next.
func (it *SseIterator) Event() ServerSentEvent { return it.cur }

// Err returns any scanner error.
func (it *SseIterator) Err() error { return it.err }

// DrainAndClose reads any remaining body and closes it.
func DrainAndClose(res *http.Response) {
	if res == nil || res.Body == nil {
		return
	}
	_, _ = io.Copy(io.Discard, res.Body)
	_ = res.Body.Close()
}

// ReadAllBody is a small helper for tests.
func ReadAllBody(r io.Reader) ([]byte, error) {
	var buf bytes.Buffer
	_, err := buf.ReadFrom(r)
	return buf.Bytes(), err
}
