// Code generated by specforge. DO NOT EDIT.

package sdk

import (
	"sync"
	"time"
)

// TelemetryHooks provides callbacks for observing the SDK request lifecycle.
// Implement any subset; nil hooks are never called.
type TelemetryHooks interface {
	// OnRequestStart fires just before the request is dispatched.
	OnRequestStart(method, path string)
	// OnRequestEnd fires after a successful response (2xx) with the elapsed duration.
	OnRequestEnd(method, path string, durationMs int64, status int)
	// OnRequestError fires when a request fails (network, timeout, non-retriable HTTP error).
	OnRequestError(method, path string, durationMs int64, err error)
	// OnRetry fires before a retry attempt (after backoff sleep).
	OnRetry(method, path string, attempt int, err error)
	// OnCacheHit fires when a GET request is served from the response cache.
	OnCacheHit(method, path string)
	// OnCacheMiss fires when a GET request misses the cache and goes to the network.
	OnCacheMiss(method, path string)
}

// MetricsCollector is a built-in TelemetryHooks implementation that tracks
// request counts, errors, durations, and retries.
type MetricsCollector struct {
	RequestCount  int64
	ErrorCount    int64
	TotalDuration time.Duration
	RetryCount    int64
	mu            sync.Mutex
}

// NewMetricsCollector creates an empty MetricsCollector.
func NewMetricsCollector() *MetricsCollector {
	return &MetricsCollector{}
}

func (m *MetricsCollector) OnRequestStart(method, path string) {
	m.mu.Lock()
	m.RequestCount++
	m.mu.Unlock()
}

func (m *MetricsCollector) OnRequestEnd(method, path string, durationMs int64, status int) {
	m.mu.Lock()
	m.TotalDuration += time.Duration(durationMs) * time.Millisecond
	if status >= 400 {
		m.ErrorCount++
	}
	m.mu.Unlock()
}

func (m *MetricsCollector) OnRequestError(method, path string, durationMs int64, err error) {
	m.mu.Lock()
	m.ErrorCount++
	m.TotalDuration += time.Duration(durationMs) * time.Millisecond
	m.mu.Unlock()
}

func (m *MetricsCollector) OnRetry(method, path string, attempt int, err error) {
	m.mu.Lock()
	m.RetryCount++
	m.mu.Unlock()
}

func (m *MetricsCollector) OnCacheHit(method, path string)  {}
func (m *MetricsCollector) OnCacheMiss(method, path string) {}

// Metrics is a snapshot of collected metrics.
type Metrics struct {
	RequestCount  int64
	ErrorCount    int64
	TotalDuration time.Duration
	AvgDuration   time.Duration
	RetryCount    int64
}

// GetMetrics returns a snapshot of the collected metrics.
func (m *MetricsCollector) GetMetrics() Metrics {
	m.mu.Lock()
	defer m.mu.Unlock()
	avg := time.Duration(0)
	if m.RequestCount > 0 {
		avg = m.TotalDuration / time.Duration(m.RequestCount)
	}
	return Metrics{
		RequestCount:  m.RequestCount,
		ErrorCount:    m.ErrorCount,
		TotalDuration: m.TotalDuration,
		AvgDuration:   avg,
		RetryCount:    m.RetryCount,
	}
}
