// Code generated by specforge. DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"fmt"
)

// ValidationError describes a single validation failure with a path and message.
type ValidationError struct {
	Path    string
	Message string
}

func (e *ValidationError) Error() string {
	return fmt.Sprintf("%s: %s", e.Path, e.Message)
}

// ValidationErrors is a slice of ValidationError that implements the error interface.
type ValidationErrors []ValidationError

func (e ValidationErrors) Error() string {
	if len(e) == 0 {
		return ""
	}
	msgs := make([]string, len(e))
	for i, v := range e {
		msgs[i] = v.Error()
	}
	out := ""
	for i, m := range msgs {
		if i > 0 {
			out += "; "
		}
		out += m
	}
	return out
}

// ValidateError validates v against the Error schema.
func ValidateError(v any) error {
	errs := validateObject(v, "")
	obj, ok := v.(map[string]any)
	if !ok {
		if b, err := json.Marshal(v); err == nil {
			var m map[string]any
			if err := json.Unmarshal(b, &m); err == nil {
				obj = m
				ok = true
			}
		}
	}
	if !ok {
		errs = append(errs, ValidationError{Path: "", Message: "expected object"})
	} else {
		if _, exists := obj["code"]; !exists {
			errs = append(errs, ValidationError{Path: "code", Message: "missing required field"})
		}
		if _, exists := obj["message"]; !exists {
			errs = append(errs, ValidationError{Path: "message", Message: "missing required field"})
		}
	}
	if len(errs) > 0 {
		return ValidationErrors(errs)
	}
	return nil
}

// ValidatePet validates v against the Pet schema.
func ValidatePet(v any) error {
	errs := validateObject(v, "")
	obj, ok := v.(map[string]any)
	if !ok {
		if b, err := json.Marshal(v); err == nil {
			var m map[string]any
			if err := json.Unmarshal(b, &m); err == nil {
				obj = m
				ok = true
			}
		}
	}
	if !ok {
		errs = append(errs, ValidationError{Path: "", Message: "expected object"})
	} else {
		if _, exists := obj["id"]; !exists {
			errs = append(errs, ValidationError{Path: "id", Message: "missing required field"})
		}
		if _, exists := obj["name"]; !exists {
			errs = append(errs, ValidationError{Path: "name", Message: "missing required field"})
		}
	}
	if len(errs) > 0 {
		return ValidationErrors(errs)
	}
	return nil
}

// ValidatePets validates v against the Pets schema.
func ValidatePets(v any) error {
	errs := validateObject(v, "")
	if len(errs) > 0 {
		return ValidationErrors(errs)
	}
	return nil
}

// validateObject performs basic structural validation on a value expected to be an object.
func validateObject(v any, path string) []ValidationError {
	var errs []ValidationError
	if v == nil {
		errs = append(errs, ValidationError{Path: path, Message: "expected object, got nil"})
		return errs
	}
	// Try to ensure it's a map.
	switch v.(type) {
	case map[string]any:
		// ok
	default:
		// Try JSON round-trip.
		if b, err := json.Marshal(v); err == nil {
			var m map[string]any
			if err := json.Unmarshal(b, &m); err != nil {
				errs = append(errs, ValidationError{Path: path, Message: fmt.Sprintf("expected object, got %T", v)})
			}
		} else {
			errs = append(errs, ValidationError{Path: path, Message: fmt.Sprintf("expected object, got %T", v)})
		}
	}
	return errs
}

