// Code generated by specforge. DO NOT EDIT.

package sdk

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"
)

// EndpointSchema describes the request and/or response schema for an endpoint.
type EndpointSchema struct {
	// RequestBody is the schema for the request body. Nil means no validation.
	RequestBody func(v any) error
	// ResponseBody is the schema for the response body. Nil means no validation.
	ResponseBody func(v any) error
}

// RouteSchemaMap maps "METHOD /path/pattern" to an EndpointSchema.
// Patterns use {param} placeholders for path segments.
type RouteSchemaMap map[string]*EndpointSchema

// matchesPath checks if actualPath matches the pattern.
// Pattern segments in {...} are treated as wildcards.
func matchesPath(pattern, actualPath string) bool {
	patternSegments := strings.Split(strings.Trim(pattern, "/"), "/")
	actualSegments := strings.Split(strings.Trim(actualPath, "/"), "/")
	if len(patternSegments) != len(actualSegments) {
		return false
	}
	for i, ps := range patternSegments {
		if strings.HasPrefix(ps, "{") && strings.HasSuffix(ps, "}") {
			continue
		}
		if ps != actualSegments[i] {
			return false
		}
	}
	return true
}

// ValidationMiddleware creates a middleware that validates request/response
// bodies against the OpenAPI schema. Validation errors are returned as errors.
//
// Usage:
//
//	schemas := RouteSchemaMap{
//		"POST /pets": {RequestBody: ValidatePet, ResponseBody: ValidatePet},
//		"GET /pets/{petId}": {ResponseBody: ValidatePet},
//	}
//	client.Use(ValidationMiddleware(schemas))
func ValidationMiddleware(schemas RouteSchemaMap) Middleware {
	return func(ctx context.Context, req *MiddlewareRequest, next func(context.Context, *MiddlewareRequest) (*MiddlewareResponse, error)) (*MiddlewareResponse, error) {
		method := strings.ToUpper(req.Method)
		// Strip query string for route matching.
		path := req.URL
		if idx := strings.Index(path, "?"); idx >= 0 {
			path = path[:idx]
		}

		// Find a matching route schema.
		routeKey := method + " " + path
		endpointSchema := schemas[routeKey]

		// Try pattern matching if exact match fails.
		if endpointSchema == nil {
			for pattern, schema := range schemas {
				spaceIdx := strings.Index(pattern, " ")
				if spaceIdx < 0 {
					continue
				}
				patternMethod := strings.ToUpper(pattern[:spaceIdx])
				patternPath := pattern[spaceIdx+1:]
				if patternMethod == method && matchesPath(patternPath, path) {
					endpointSchema = schema
					break
				}
			}
		}

		// Validate request body if a schema is defined.
		if endpointSchema != nil && endpointSchema.RequestBody != nil && len(req.Body) > 0 {
			var body any
			if err := json.Unmarshal(req.Body, &body); err == nil {
				if err := endpointSchema.RequestBody(body); err != nil {
					return nil, fmt.Errorf("[validation] %s %s request body: %w", method, path, err)
				}
			}
		}

		// Proceed with the request.
		resp, err := next(ctx, req)
		if err != nil {
			return nil, err
		}

		// Validate response body if a schema is defined.
		if endpointSchema != nil && endpointSchema.ResponseBody != nil && resp.StatusCode >= 200 && resp.StatusCode < 300 && len(resp.Body) > 0 {
			contentType := resp.Header.Get("Content-Type")
			if strings.Contains(contentType, "application/json") {
				var body any
				if err := json.Unmarshal(resp.Body, &body); err == nil {
					if err := endpointSchema.ResponseBody(body); err != nil {
						return nil, fmt.Errorf("[validation] %s %s response %d: %w", method, path, resp.StatusCode, err)
					}
				}
			}
		}

		return resp, nil
	}
}
