// Code generated by specforge. DO NOT EDIT.

//! Response caching with ETag/conditional request support.
//!
//! GET responses are cached; subsequent requests send `If-None-Match` and
//! return the cached body on 304 Not Modified.

use std::collections::HashMap;
use std::sync::Arc;
use std::time::{Duration, Instant};
use tokio::sync::Mutex;

/// A cached response entry: the ETag returned by the server, the raw body,
/// and the wall-clock time the entry was stored.
#[derive(Debug, Clone)]
pub struct CacheEntry {
    pub etag: String,
    pub data: Vec<u8>,
    pub timestamp: Instant,
}

/// Thread-safe in-memory response cache keyed by full URL.
///
/// Supports TTL-based expiry and ETag-based conditional requests
/// (`If-None-Match` / 304 Not Modified).
#[derive(Clone, Debug)]
pub struct ResponseCache {
    inner: Arc<Mutex<HashMap<String, CacheEntry>>>,
    ttl: Duration,
}

impl ResponseCache {
    /// Create a new cache with the given time-to-live.
    pub fn new(ttl: Duration) -> Self {
        Self {
            inner: Arc::new(Mutex::new(HashMap::new())),
            ttl,
        }
    }

    /// Return the cached entry for `url` if it exists and has not expired.
    pub async fn get(&self, url: &str) -> Option<CacheEntry> {
        let map = self.inner.lock().await;
        map.get(url).and_then(|entry| {
            if entry.timestamp.elapsed() < self.ttl {
                Some(entry.clone())
            } else {
                None // expired
            }
        })
    }

    /// Store a response under `url` with its ETag and body bytes.
    pub async fn set(&self, url: &str, etag: &str, data: &[u8]) {
        let mut map = self.inner.lock().await;
        // Evict expired entries opportunistically.
        map.retain(|_, e| e.timestamp.elapsed() < self.ttl);
        map.insert(
            url.to_string(),
            CacheEntry {
                etag: etag.to_string(),
                data: data.to_vec(),
                timestamp: Instant::now(),
            },
        );
    }

    /// Remove all cached entries.
    pub async fn clear(&self) {
        self.inner.lock().await.clear();
    }

    /// Number of entries currently in the cache (including possibly expired).
    pub async fn len(&self) -> usize {
        self.inner.lock().await.len()
    }
}
