// Code generated by specforge. DO NOT EDIT.

use std::sync::Arc;
use std::time::Duration;

use reqwest::header::{HeaderMap, HeaderName, HeaderValue, AUTHORIZATION};
use serde::de::DeserializeOwned;
use serde::Serialize;

use crate::concurrency::Semaphore;
	use crate::dedup::RequestDeduper;
	use crate::error::{Error, Result};
	use crate::idempotency::{is_idempotency_candidate, new_idempotency_key, IDEMPOTENCY_HEADER};
		use crate::middleware::{
		    compose, BoxFuture, Middleware, MiddlewareRequest, MiddlewareResponse, NextFn, StreamMiddleware,
		};
	use crate::retry::{backoff_delay, is_retriable_method, RetryOptions};
	use crate::streaming::SseStream;
	
	/// Credential provider applied on every request.
	#[derive(Clone)]
	pub enum Auth {
	    /// `Authorization: Bearer <token>` with a fixed token.
	    Bearer(String),
	    /// `Authorization: Bearer <token>` where the token is produced per call.
	    BearerFn(Arc<dyn Fn() -> std::result::Result<String, String> + Send + Sync>),
	    /// Named header API key with a fixed value.
	    ApiKey { header: String, key: String },
	    /// Named header API key produced per call.
	    ApiKeyFn {
	        header: String,
	        get_key: Arc<dyn Fn() -> std::result::Result<String, String> + Send + Sync>,
	    },
	    /// No auth.
	    None,
	}
	
	impl std::fmt::Debug for Auth {
	    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
	        match self {
	            Auth::Bearer(_) => write!(f, "Auth::Bearer(***)"),
	            Auth::BearerFn(_) => write!(f, "Auth::BearerFn(..)"),
	            Auth::ApiKey { header, .. } => write!(f, "Auth::ApiKey({header}, ***)"),
	            Auth::ApiKeyFn { header, .. } => write!(f, "Auth::ApiKeyFn({header}, ..)"),
	            Auth::None => write!(f, "Auth::None"),
	        }
	    }
	}
	
	impl Auth {
	    fn apply(&self, headers: &mut HeaderMap) -> Result<()> {
	        match self {
	            Auth::None => Ok(()),
	            Auth::Bearer(tok) => {
	                let value = HeaderValue::from_str(&format!("Bearer {tok}"))
	                    .map_err(|e| Error::Message(e.to_string()))?;
	                headers.insert(AUTHORIZATION, value);
	                Ok(())
	            }
	            Auth::BearerFn(f) => {
	                let tok = f().map_err(Error::Message)?;
	                let value = HeaderValue::from_str(&format!("Bearer {tok}"))
	                    .map_err(|e| Error::Message(e.to_string()))?;
	                headers.insert(AUTHORIZATION, value);
	                Ok(())
	            }
	            Auth::ApiKey { header, key } => {
	                let name = HeaderName::from_bytes(header.as_bytes())
	                    .map_err(|e| Error::Message(e.to_string()))?;
	                let value =
	                    HeaderValue::from_str(key).map_err(|e| Error::Message(e.to_string()))?;
	                headers.insert(name, value);
	                Ok(())
	            }
	            Auth::ApiKeyFn { header, get_key } => {
	                let key = get_key().map_err(Error::Message)?;
	                let name = HeaderName::from_bytes(header.as_bytes())
	                    .map_err(|e| Error::Message(e.to_string()))?;
	                let value =
	                    HeaderValue::from_str(&key).map_err(|e| Error::Message(e.to_string()))?;
	                headers.insert(name, value);
	                Ok(())
	            }
	        }
	    }
	}
	
	/// HTTP client for Swagger Petstore.
	#[derive(Clone)]
	pub struct Client {
	    base_url: String,
	    http: reqwest::Client,
	    auth: Auth,
	    default_headers: HeaderMap,
	    retry: RetryOptions,
	    /// Per-attempt timeout. `None` uses the underlying reqwest client default.
	    timeout: Option<Duration>,
	    semaphore: Option<Semaphore>,
	    dedupe: bool,
	    idempotency: bool,
		    deduper: RequestDeduper,
		    middlewares: Vec<Middleware>,
		    stream_middlewares: Vec<StreamMiddleware>,
		}
	
	impl std::fmt::Debug for Client {
	    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
	        f.debug_struct("Client")
	            .field("base_url", &self.base_url)
	            .field("auth", &self.auth)
	            .field("retry", &self.retry)
	            .field("timeout", &self.timeout)
	            .field("dedupe", &self.dedupe)
	            .field("idempotency", &self.idempotency)
	            .field("max_concurrent", &self.semaphore.as_ref().map(|_| "set"))
		            .field("middlewares", &self.middlewares.len())
		            .field("stream_middlewares", &self.stream_middlewares.len())
		            .finish()
		    }
		}
		
		impl Client {
		    /// Build a client with the spec's default base URL.
		    pub fn new() -> Result<Self> {
	        ClientBuilder::new().build()
	    }
	
	    /// Start a builder.
	    pub fn builder() -> ClientBuilder {
	        ClientBuilder::new()
	    }
	
	    pub fn base_url(&self) -> &str {
	        &self.base_url
	    }
	
		    /// Register middleware (applied in registration order).
		    pub fn use_middleware(&mut self, mw: Middleware) -> &mut Self {
		        self.middlewares.push(mw);
		        self
		    }

		    /// Register stream middleware (header-only modifications before streaming).
		    pub fn use_stream_middleware(&mut self, mw: StreamMiddleware) -> &mut Self {
		        self.stream_middlewares.push(mw);
		        self
		    }
	
	    /// Issue a JSON request with concurrency + dedupe + retry + middleware.
	    /// `body` is serialized when `Some`. On 2xx, the response is deserialized
	    /// into `T` (use `()` for empty bodies).
	    pub async fn request_json<T, B>(
	        &self,
	        method: reqwest::Method,
	        path: &str,
	        query: &[(&str, String)],
	        body: Option<&B>,
	    ) -> Result<T>
	    where
	        T: DeserializeOwned,
	        B: Serialize + ?Sized,
	    {
	        let url = format!("{}{}", self.base_url, path);
	        let body_bytes = match body {
	            Some(b) => Some(serde_json::to_vec(b)?),
	            None => None,
	        };
	
	        // Concurrency gate.
	        let _permit = if let Some(sem) = &self.semaphore {
	            Some(sem.acquire().await.map_err(|e| Error::Message(e.to_string()))?)
	        } else {
	            None
	        };
	
	        let query_owned: Vec<(String, String)> =
	            query.iter().map(|(k, v)| (k.to_string(), v.clone())).collect();
	
	        // One idempotency key for the whole retry loop.
	        let idem_key = if self.idempotency && is_idempotency_candidate(&method) {
	            Some(new_idempotency_key())
	        } else {
	            None
	        };
	
	        let (data, status) = if self.dedupe && RequestDeduper::is_safe_method(&method) {
	            let key = if query_owned.is_empty() {
	                format!("{method} {url}")
	            } else {
	                format!("{method} {url}?{query_owned:?}")
	            };
	            let this = self.clone();
	            let method_c = method.clone();
	            let url_c = url.clone();
	            let query_c = query_owned.clone();
	            let body_c = body_bytes.clone();
	            let idem_c = idem_key.clone();
	            self.deduper
	                .dedupe(key, move || {
	                    let this = this;
	                    let method = method_c;
	                    let url = url_c;
	                    let query = query_c;
	                    let body_bytes = body_c;
	                    let idem_key = idem_c;
	                    async move {
	                        this.do_with_retry(
	                            &method,
	                            &url,
	                            &query,
	                            body_bytes.as_deref(),
	                            idem_key.as_deref(),
	                        )
	                        .await
	                    }
	                })
	                .await?
	        } else {
	            self.do_with_retry(
	                &method,
	                &url,
	                &query_owned,
	                body_bytes.as_deref(),
	                idem_key.as_deref(),
	            )
	            .await?
	        };
	
	        if status == 204 || data.is_empty() {
	            return serde_json::from_str("null")
	                .or_else(|_| serde_json::from_str("{}"))
	                .map_err(Error::from);
	        }
	        Ok(serde_json::from_slice(&data)?)
	    }
	
	    /// Issue a streaming request (no retry). Returns the raw Response; use
	    /// [`SseStream`] for SSE parsing. Caller owns the body.
	    pub async fn request_stream(
	        &self,
	        method: reqwest::Method,
	        path: &str,
	        query: &[(&str, String)],
	        body: Option<&[u8]>,
	    ) -> Result<reqwest::Response> {
	        let url = format!("{}{}", self.base_url, path);
	        let query_owned: Vec<(String, String)> =
	            query.iter().map(|(k, v)| (k.to_string(), v.clone())).collect();
	        let full_url = if query_owned.is_empty() {
	            url
	        } else {
	            let q: String = query_owned
	                .iter()
	                .map(|(k, v)| format!("{}={}", k, urlencoding_lite(v)))
	                .collect::<Vec<_>>()
	                .join("&");
	            format!("{}?{}", url, q)
	        };
	        let mut headers = self.default_headers.clone();
	        self.auth.apply(&mut headers)?;
	        if body.is_some() {
	            headers.insert(
	                reqwest::header::CONTENT_TYPE,
	                HeaderValue::from_static("application/json"),
	            );
	        }
	        if !headers.contains_key(reqwest::header::ACCEPT) {
	            headers.insert(
	                reqwest::header::ACCEPT,
	                HeaderValue::from_static("text/event-stream, application/json"),
	            );
	        }
	        if self.idempotency && is_idempotency_candidate(&method) {
	            let name = HeaderName::from_bytes(IDEMPOTENCY_HEADER.as_bytes())
	                .map_err(|e| Error::Message(e.to_string()))?;
	            if !headers.contains_key(&name) {
	                headers.insert(
	                    name,
	                    HeaderValue::from_str(&new_idempotency_key())
	                        .map_err(|e| Error::Message(e.to_string()))?,
	                );
	            }
		        }
		        // Apply stream middleware.
		        let mut mw_req = MiddlewareRequest {
		            method: method.clone(),
		            url: full_url.clone(),
		            headers: headers.clone(),
		            body: body.map(|b| b.to_vec()),
		        };
		        for mw in &self.stream_middlewares {
		            mw(mw_req.clone()).await?;
		            headers = mw_req.headers.clone();
		        }
		        let mut builder = self.http.request(method, &full_url).headers(headers);
	        if let Some(b) = body {
	            builder = builder.body(b.to_vec());
	        }
	        if let Some(t) = self.timeout {
	            builder = builder.timeout(t);
	        }
	        let res = builder.send().await.map_err(Error::from)?;
	        if !res.status().is_success() {
	            let status = res.status().as_u16();
	            let bytes = res.bytes().await?;
	            return Err(Error::Http {
	                status,
	                body: String::from_utf8_lossy(&bytes).into_owned(),
	                url: full_url,
	            });
	        }
	        Ok(res)
	    }
	
	    /// Convenience: GET a path as an SSE stream.
	    pub async fn stream_sse(
	        &self,
	        path: &str,
	        query: &[(&str, String)],
	    ) -> Result<SseStream<impl futures_util::Stream<Item = std::result::Result<bytes::Bytes, reqwest::Error>> + Send + Unpin>> {
	        let res = self
	            .request_stream(reqwest::Method::GET, path, query, None)
	            .await?;
	        Ok(SseStream::new(res.bytes_stream()))
	    }
	
	    async fn do_with_retry(
	        &self,
	        method: &reqwest::Method,
	        url: &str,
	        query: &[(String, String)],
	        body_bytes: Option<&[u8]>,
	        idem_key: Option<&str>,
	    ) -> Result<(Vec<u8>, u16)> {
	        let mut last_err: Option<Error> = None;
	        let max = self.retry.max_retries;
	        for attempt in 0..=max {
	            if attempt > 0 {
	                let delay = backoff_delay(attempt - 1, &self.retry);
	                tokio::time::sleep(delay).await;
	            }
	            match self.do_once(method, url, query, body_bytes, idem_key).await {
	                Ok(v) => return Ok(v),
	                Err(e) => {
	                    let retriable = is_error_retriable(method, &e, &self.retry);
	                    last_err = Some(e);
	                    if !retriable || attempt == max {
	                        break;
	                    }
	                }
	            }
	        }
	        Err(last_err.unwrap_or_else(|| Error::Message("request failed".into())))
	    }
	
	    async fn do_once(
	        &self,
	        method: &reqwest::Method,
	        url: &str,
	        query: &[(String, String)],
	        body_bytes: Option<&[u8]>,
	        idem_key: Option<&str>,
	    ) -> Result<(Vec<u8>, u16)> {
	        // Build full URL with query for middleware visibility.
	        let full_url = if query.is_empty() {
	            url.to_string()
	        } else {
	            let q: String = query
	                .iter()
	                .map(|(k, v)| format!("{}={}", k, urlencoding_lite(v)))
	                .collect::<Vec<_>>()
	                .join("&");
	            format!("{}?{}", url, q)
	        };
	
	        let mut headers = self.default_headers.clone();
	        self.auth.apply(&mut headers)?;
	        if body_bytes.is_some() {
	            headers.insert(
	                reqwest::header::CONTENT_TYPE,
	                HeaderValue::from_static("application/json"),
	            );
	        }
	        if let Some(key) = idem_key {
	            let name = HeaderName::from_bytes(IDEMPOTENCY_HEADER.as_bytes())
	                .map_err(|e| Error::Message(e.to_string()))?;
	            if !headers.contains_key(&name) {
	                headers.insert(
	                    name,
	                    HeaderValue::from_str(key).map_err(|e| Error::Message(e.to_string()))?,
	                );
	            }
	        }
	
	        let mw_req = MiddlewareRequest {
	            method: method.clone(),
	            url: full_url.clone(),
	            headers,
	            body: body_bytes.map(|b| b.to_vec()),
	        };
	
	        let http = self.http.clone();
	        let timeout = self.timeout;
	        let dispatch: NextFn = Arc::new(move |req: MiddlewareRequest| {
	            let http = http.clone();
	            Box::pin(async move {
	                let mut builder = http.request(req.method, &req.url);
	                builder = builder.headers(req.headers);
	                if let Some(bytes) = req.body {
	                    builder = builder.body(bytes);
	                }
	                if let Some(t) = timeout {
	                    builder = builder.timeout(t);
	                }
	                let res = builder.send().await.map_err(|e| {
	                    if e.is_timeout() {
	                        Error::Timeout {
	                            timeout_ms: timeout.map(|d| d.as_millis() as u64).unwrap_or(0),
	                        }
	                    } else {
	                        Error::Transport(e)
	                    }
	                })?;
	                let status = res.status().as_u16();
	                let headers = res.headers().clone();
	                let body = res.bytes().await?.to_vec();
	                Ok(MiddlewareResponse { status, headers, body })
	            }) as BoxFuture
	        });
	
	        let handler = compose(&self.middlewares, dispatch);
	        let mw_res = handler(mw_req).await?;
	
	        if !(200..300).contains(&mw_res.status) {
	            return Err(Error::Http {
	                status: mw_res.status,
	                body: String::from_utf8_lossy(&mw_res.body).into_owned(),
	                url: full_url,
	            });
	        }
	        Ok((mw_res.body, mw_res.status))
	    }
	}
	
	fn urlencoding_lite(s: &str) -> String {
	    let mut out = String::with_capacity(s.len());
	    for b in s.bytes() {
	        match b {
	            b'A'..=b'Z' | b'a'..=b'z' | b'0'..=b'9' | b'-' | b'_' | b'.' | b'~' => {
	                out.push(b as char)
	            }
	            _ => out.push_str(&format!("%{:02X}", b)),
	        }
	    }
	    out
	}
	
	fn is_error_retriable(method: &reqwest::Method, err: &Error, opts: &RetryOptions) -> bool {
	    match err {
	        Error::Timeout { .. } => true,
	        Error::Transport(e) => e.is_timeout() || e.is_connect() || e.is_request(),
	        Error::Http { status, .. } => {
	            is_retriable_method(method) && opts.retry_on_statuses.contains(status)
	        }
	        Error::Serde(_) | Error::Message(_) => false,
	    }
	}
	
	impl Default for Client {
	    fn default() -> Self {
	        Self::new().expect("default client")
	    }
	}
	
	/// Builder for [`Client`].
	#[derive(Clone)]
	pub struct ClientBuilder {
	    base_url: String,
	    auth: Auth,
	    default_headers: HeaderMap,
	    retry: RetryOptions,
	    timeout: Option<Duration>,
	    max_concurrent: Option<usize>,
	    dedupe: bool,
	    idempotency: bool,
		    middlewares: Vec<Middleware>,
		    stream_middlewares: Vec<StreamMiddleware>,
		    /// Seeded from the first API-key security scheme in the spec, if any.
	    #[allow(dead_code)]
	    default_api_key_header: String,
	}
	
	impl std::fmt::Debug for ClientBuilder {
	    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
	        f.debug_struct("ClientBuilder")
	            .field("base_url", &self.base_url)
	            .field("auth", &self.auth)
	            .field("retry", &self.retry)
	            .field("timeout", &self.timeout)
	            .field("max_concurrent", &self.max_concurrent)
	            .field("dedupe", &self.dedupe)
	            .field("idempotency", &self.idempotency)
	            .field("middlewares", &self.middlewares.len())
	            .finish()
	    }
	}
	
	impl ClientBuilder {
	    pub fn new() -> Self {
	        Self {
	            base_url: "http://petstore.swagger.io/v1".to_string(),
	            auth: Auth::None,
	            default_headers: HeaderMap::new(),
	            retry: RetryOptions::default(),
	            timeout: Some(Duration::from_secs(30)),
	            max_concurrent: None,
	            dedupe: true,
	            idempotency: true,
		            middlewares: Vec::new(),
		            stream_middlewares: Vec::new(),
		            default_api_key_header: "".to_string(),
	        }
	    }
	
	    pub fn base_url(mut self, url: impl Into<String>) -> Self {
	        self.base_url = url.into().trim_end_matches('/').to_string();
	        self
	    }
	
	    pub fn bearer_token(mut self, token: impl Into<String>) -> Self {
	        self.auth = Auth::Bearer(token.into());
	        self
	    }
	
	    pub fn auth(mut self, auth: Auth) -> Self {
	        self.auth = auth;
	        self
	    }
	
	    pub fn api_key(mut self, header: impl Into<String>, key: impl Into<String>) -> Self {
	        self.auth = Auth::ApiKey {
	            header: header.into(),
	            key: key.into(),
	        };
	        self
	    }
	
	    pub fn retry(mut self, retry: RetryOptions) -> Self {
	        self.retry = retry;
	        self
	    }
	
	    pub fn timeout(mut self, timeout: Duration) -> Self {
	        self.timeout = Some(timeout);
	        self
	    }
	
	    pub fn no_timeout(mut self) -> Self {
	        self.timeout = None;
	        self
	    }
	
	    pub fn max_concurrent(mut self, n: usize) -> Self {
	        self.max_concurrent = Some(n);
	        self
	    }
	
	    pub fn dedupe(mut self, on: bool) -> Self {
	        self.dedupe = on;
	        self
	    }
	
	    pub fn idempotency(mut self, on: bool) -> Self {
	        self.idempotency = on;
	        self
	    }
	
		    pub fn middleware(mut self, mw: Middleware) -> Self {
		        self.middlewares.push(mw);
		        self
		    }

		    pub fn stream_middleware(mut self, mw: StreamMiddleware) -> Self {
		        self.stream_middlewares.push(mw);
		        self
		    }
		
		    pub fn build(self) -> Result<Client> {
	        let http = reqwest::Client::builder()
	            .user_agent("specforge-rust-sdk")
	            .build()?;
	        Ok(Client {
	            base_url: self.base_url,
	            http,
	            auth: self.auth,
	            default_headers: self.default_headers,
	            retry: self.retry,
	            timeout: self.timeout,
	            semaphore: self.max_concurrent.map(Semaphore::new),
	            dedupe: self.dedupe,
	            idempotency: self.idempotency,
		            deduper: RequestDeduper::new(),
		            middlewares: self.middlewares,
		            stream_middlewares: self.stream_middlewares,
		        })
	    }
	}
	
	impl Default for ClientBuilder {
	    fn default() -> Self {
	        Self::new()
	    }
	}
	