// Code generated by specforge. DO NOT EDIT.

use std::sync::Arc;
use tokio::sync::{Semaphore as TokioSemaphore, SemaphorePermit};

/// Async semaphore bounding in-flight requests.
#[derive(Clone, Debug)]
pub struct Semaphore {
    inner: Arc<TokioSemaphore>,
}

impl Semaphore {
    pub fn new(max: usize) -> Self {
        assert!(max > 0, "max concurrent must be > 0");
        Self {
            inner: Arc::new(TokioSemaphore::new(max)),
        }
    }

    pub async fn acquire(&self) -> Result<SemaphorePermit<'_>, tokio::sync::AcquireError> {
        self.inner.acquire().await
    }
}
