// Code generated by specforge. DO NOT EDIT.

use std::collections::HashMap;
use std::future::Future;
use std::pin::Pin;
use std::sync::Arc;

use tokio::sync::{Mutex, broadcast};

use crate::error::{Error, Result};

type BoxFut = Pin<Box<dyn Future<Output = Result<(Vec<u8>, u16)>> + Send>>;

/// Coalesces identical in-flight safe requests.
#[derive(Clone, Default)]
pub struct RequestDeduper {
    inflight: Arc<Mutex<HashMap<String, broadcast::Sender<std::result::Result<(Vec<u8>, u16), String>>>>>,
}

impl std::fmt::Debug for RequestDeduper {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "RequestDeduper")
    }
}

impl RequestDeduper {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn is_safe_method(method: &reqwest::Method) -> bool {
        matches!(
            *method,
            reqwest::Method::GET | reqwest::Method::HEAD | reqwest::Method::OPTIONS
        )
    }

    /// Run `f`, sharing the result with concurrent callers of the same key.
    pub async fn dedupe<F, Fut>(&self, key: String, f: F) -> Result<(Vec<u8>, u16)>
    where
        F: FnOnce() -> Fut + Send + 'static,
        Fut: Future<Output = Result<(Vec<u8>, u16)>> + Send + 'static,
    {
        let mut map = self.inflight.lock().await;
        if let Some(tx) = map.get(&key) {
            let mut rx = tx.subscribe();
            drop(map);
            match rx.recv().await {
                Ok(Ok(v)) => Ok(v),
                Ok(Err(msg)) => Err(Error::Message(msg)),
                Err(_) => Err(Error::Message("dedupe channel closed".into())),
            }
        } else {
            let (tx, _rx) = broadcast::channel(1);
            map.insert(key.clone(), tx.clone());
            drop(map);

            let result = f().await;
            let wire = match &result {
                Ok(v) => Ok(v.clone()),
                Err(e) => Err(e.to_string()),
            };
            let _ = tx.send(wire);

            let mut map = self.inflight.lock().await;
            map.remove(&key);
            result
        }
    }
}

// Silence unused when generated crates don't call the alias.
#[allow(dead_code)]
type _BoxFut = BoxFut;
