// Code generated by specforge. DO NOT EDIT.

use std::time::{SystemTime, UNIX_EPOCH};

/// Header name used for unsafe-method idempotency keys.
pub const IDEMPOTENCY_HEADER: &str = "Idempotency-Key";

/// True for methods that benefit from an idempotency key on retries.
pub fn is_idempotency_candidate(method: &reqwest::Method) -> bool {
    matches!(
        *method,
        reqwest::Method::POST
            | reqwest::Method::PUT
            | reqwest::Method::PATCH
            | reqwest::Method::DELETE
    )
}

/// Generate a fresh RFC-4122 v4 UUID string without extra deps.
pub fn new_idempotency_key() -> String {
    let mut bytes = [0u8; 16];
    // Mix time + address entropy; good enough for collision avoidance.
    let t = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_nanos())
        .unwrap_or(0);
    let mut state = t as u64
        ^ ((t >> 64) as u64)
        ^ std::process::id() as u64
        ^ ((&bytes as *const _) as u64);
    for b in &mut bytes {
        // xorshift64*
        state ^= state << 13;
        state ^= state >> 7;
        state ^= state << 17;
        *b = (state >> 8) as u8;
    }
    bytes[6] = (bytes[6] & 0x0f) | 0x40;
    bytes[8] = (bytes[8] & 0x3f) | 0x80;
    format!(
        "{:02x}{:02x}{:02x}{:02x}-{:02x}{:02x}-{:02x}{:02x}-{:02x}{:02x}-{:02x}{:02x}{:02x}{:02x}{:02x}{:02x}",
        bytes[0], bytes[1], bytes[2], bytes[3],
        bytes[4], bytes[5],
        bytes[6], bytes[7],
        bytes[8], bytes[9],
        bytes[10], bytes[11], bytes[12], bytes[13], bytes[14], bytes[15]
    )
}
