// Code generated by specforge. DO NOT EDIT.

/// Request interceptor: transform the request body before it is serialized
/// and sent. Return the (possibly modified) body.
pub trait RequestInterceptor: Send + Sync {
    /// Transform the request body. Return the modified body.
    fn transform(&self, body: serde_json::Value) -> serde_json::Value;
}

/// Response interceptor: transform the response body after it is deserialized.
/// Return the (possibly modified) body.
pub trait ResponseInterceptor: Send + Sync {
    /// Transform the response body. Return the modified body.
    fn transform(&self, body: serde_json::Value) -> serde_json::Value;
}
