// Code generated by specforge. DO NOT EDIT.

//! Generated OpenAPI client.

pub mod api;
pub mod client;
pub mod concurrency;
pub mod dedup;
pub mod error;
pub mod idempotency;
pub mod middleware;
pub mod models;
pub mod paginate;
pub mod retry;
pub mod streaming;

pub use client::{Auth, Client, ClientBuilder};
pub use concurrency::Semaphore;
pub use dedup::RequestDeduper;
pub use error::{Error, Result};
pub use idempotency::{{is_idempotency_candidate, new_idempotency_key, IDEMPOTENCY_HEADER}};
pub use middleware::{{Middleware, MiddlewareRequest, MiddlewareResponse, StreamMiddleware}};
pub use paginate::{cursor_paginate, offset_paginate, CursorPage, OffsetPage};
pub use retry::RetryOptions;
pub use streaming::{{ServerSentEvent, SseStream}};
