// Code generated by specforge. DO NOT EDIT.

//! Structured logging abstraction. Consumers plug in their own logger;
//! the SDK logs requests, responses, retries, and cache hits/misses.

use std::fmt;

/// Structured logging trait. Implement this to plug in your own logger.
pub trait Logger: Send + Sync + fmt::Debug {
    fn debug(&self, message: &str);
    fn info(&self, message: &str);
    fn warn(&self, message: &str);
    fn error(&self, message: &str);
}

/// Default logger that writes to stderr via `eprintln!`.
#[derive(Debug, Clone, Copy)]
pub struct ConsoleLogger;

impl Logger for ConsoleLogger {
    fn debug(&self, message: &str) {
        eprintln!("[DEBUG] {}", message);
    }
    fn info(&self, message: &str) {
        eprintln!("[INFO]  {}", message);
    }
    fn warn(&self, message: &str) {
        eprintln!("[WARN]  {}", message);
    }
    fn error(&self, message: &str) {
        eprintln!("[ERROR] {}", message);
    }
}

/// A no-op logger that discards all messages.
#[derive(Debug, Clone, Copy)]
pub struct NoopLogger;

impl Logger for NoopLogger {
    fn debug(&self, _: &str) {}
    fn info(&self, _: &str) {}
    fn warn(&self, _: &str) {}
    fn error(&self, _: &str) {}
}
