// Code generated by specforge. DO NOT EDIT.

use std::future::Future;
use std::pin::Pin;
use std::sync::Arc;

use reqwest::header::HeaderMap;

use crate::error::Result;

/// Mutable request descriptor passed through middleware.
#[derive(Debug, Clone)]
pub struct MiddlewareRequest {
    pub method: reqwest::Method,
    pub url: String,
    pub headers: HeaderMap,
    pub body: Option<Vec<u8>>,
}

/// Raw response after the transport round-trip.
#[derive(Debug, Clone)]
pub struct MiddlewareResponse {
    pub status: u16,
    pub headers: HeaderMap,
    pub body: Vec<u8>,
}

pub type BoxFuture = Pin<Box<dyn Future<Output = Result<MiddlewareResponse>> + Send>>;
pub type NextFn = Arc<dyn Fn(MiddlewareRequest) -> BoxFuture + Send + Sync>;

/// Middleware observes or rewrites a request/response. Call `next(req)` to continue.
pub type Middleware = Arc<dyn Fn(MiddlewareRequest, NextFn) -> BoxFuture + Send + Sync>;

/// Compose middlewares (registration order = outer-to-inner) around `dispatch`.
pub fn compose(middlewares: &[Middleware], dispatch: NextFn) -> NextFn {
    let mut h = dispatch;
    for mw in middlewares.iter().rev() {
        let mw = Arc::clone(mw);
        let next = Arc::clone(&h);
        h = Arc::new(move |req| mw(req, Arc::clone(&next)));
    }
    h
}

/// Streaming middleware can observe or rewrite request headers before streaming.
/// It cannot read the response body.
pub type StreamMiddleware = Arc<dyn Fn(MiddlewareRequest) -> Pin<Box<dyn Future<Output = Result<()>> + Send>> + Send + Sync>;
