// Code generated by specforge. DO NOT EDIT.

use crate::error::Result;

/// One page of a cursor-based list.
#[derive(Debug, Clone)]
pub struct CursorPage<T> {
    pub items: Vec<T>,
    pub next_cursor: Option<String>,
}

/// Walk a cursor list until `next_cursor` is `None`/empty.
///
/// ```ignore
/// cursor_paginate(
///     |cursor| async move { /* call generated list method */ Ok(page) },
///     |items| { /* handle */ Ok(()) },
/// ).await?;
/// ```
pub async fn cursor_paginate<T, Fut, F, H>(mut fetch: F, mut handle: H) -> Result<()>
where
    F: FnMut(Option<String>) -> Fut,
    Fut: std::future::Future<Output = Result<CursorPage<T>>>,
    H: FnMut(Vec<T>) -> Result<()>,
{
    let mut cursor: Option<String> = None;
    loop {
        let page = fetch(cursor).await?;
        handle(page.items)?;
        match page.next_cursor {
            Some(c) if !c.is_empty() => cursor = Some(c),
            _ => return Ok(()),
        }
    }
}

/// One page of an offset/limit list.
#[derive(Debug, Clone)]
pub struct OffsetPage<T> {
    pub items: Vec<T>,
    pub total: Option<u64>,
}

/// Walk an offset/limit list until a short page is returned.
pub async fn offset_paginate<T, Fut, F, H>(
    limit: u32,
    mut fetch: F,
    mut handle: H,
) -> Result<()>
where
    F: FnMut(u32, u32) -> Fut,
    Fut: std::future::Future<Output = Result<OffsetPage<T>>>,
    H: FnMut(Vec<T>) -> Result<()>,
{
    let limit = if limit == 0 { 50 } else { limit };
    let mut offset = 0u32;
    loop {
        let page = fetch(offset, limit).await?;
        let n = page.items.len() as u32;
        handle(page.items)?;
        if n < limit {
            return Ok(());
        }
        offset = offset.saturating_add(n);
    }
}
