// Code generated by specforge. DO NOT EDIT.

//! Rate limiting for controlling request throughput.

use async_trait::async_trait;
use tokio::sync::Mutex;

/// Rate limiter interface. The client calls `acquire()` before each request.
#[async_trait]
pub trait RateLimiter: Send + Sync {
    async fn acquire(&self) -> crate::error::Result<()>;
}

/// Token bucket rate limiter. Tokens refill at a constant rate up to a maximum.
pub struct TokenBucket {
    inner: Mutex<TokenBucketInner>,
}

struct TokenBucketInner {
    tokens: f64,
    max_tokens: f64,
    refill_rate: f64,
    last_refill: std::time::Instant,
}

impl TokenBucket {
    pub fn new(max_tokens: usize, refill_rate: f64) -> Self {
        Self {
            inner: Mutex::new(TokenBucketInner {
                tokens: max_tokens as f64,
                max_tokens: max_tokens as f64,
                refill_rate,
                last_refill: std::time::Instant::now(),
            }),
        }
    }

    fn refill(inner: &mut TokenBucketInner) {
        let now = std::time::Instant::now();
        let elapsed = now.duration_since(inner.last_refill).as_secs_f64();
        inner.tokens = (inner.max_tokens).min(inner.tokens + elapsed * inner.refill_rate);
        inner.last_refill = now;
    }
}

#[async_trait]
impl RateLimiter for TokenBucket {
    async fn acquire(&self) -> crate::error::Result<()> {
        loop {
            {
                let mut inner = self.inner.lock().await;
                Self::refill(&mut inner);
                if inner.tokens >= 1.0 {
                    inner.tokens -= 1.0;
                    return Ok(());
                }
            }
            tokio::time::sleep(std::time::Duration::from_millis(100)).await;
        }
    }
}

/// Sliding window rate limiter.
pub struct SlidingWindow {
    inner: Mutex<SlidingWindowInner>,
}

struct SlidingWindowInner {
    requests: Vec<std::time::Instant>,
    max_requests: usize,
    window: std::time::Duration,
}

impl SlidingWindow {
    pub fn new(max_requests: usize, window: std::time::Duration) -> Self {
        Self {
            inner: Mutex::new(SlidingWindowInner {
                requests: Vec::new(),
                max_requests,
                window,
            }),
        }
    }
}

#[async_trait]
impl RateLimiter for SlidingWindow {
    async fn acquire(&self) -> crate::error::Result<()> {
        loop {
            {
                let mut inner = self.inner.lock().await;
                let cutoff = std::time::Instant::now() - inner.window;
                inner.requests.retain(|t| *t > cutoff);
                if inner.requests.len() < inner.max_requests {
                    inner.requests.push(std::time::Instant::now());
                    return Ok(());
                }
                if let Some(oldest) = inner.requests.first() {
                    let wait = inner.window - std::time::Instant::now().duration_since(*oldest);
                    drop(inner);
                    tokio::time::sleep(wait).await;
                }
            }
        }
    }
}
