// Code generated by specforge. DO NOT EDIT.

use std::time::Duration;

/// Retry policy applied around each request.
#[derive(Debug, Clone)]
pub struct RetryOptions {
    /// Attempts AFTER the first try. Default 2 (3 total).
    pub max_retries: u32,
    /// Exponential base delay. Default 500ms.
    pub base_delay: Duration,
    /// Cap on per-attempt sleep. Default 8s.
    pub max_delay: Duration,
    /// HTTP statuses that should be retried. Default: 408, 429, 502, 503, 504.
    pub retry_on_statuses: Vec<u16>,
}

impl Default for RetryOptions {
    fn default() -> Self {
        Self {
            max_retries: 2,
            base_delay: Duration::from_millis(500),
            max_delay: Duration::from_secs(8),
            retry_on_statuses: vec![408, 429, 502, 503, 504],
        }
    }
}

/// True for methods safe to replay by default.
pub fn is_retriable_method(method: &reqwest::Method) -> bool {
    matches!(
        *method,
        reqwest::Method::GET
            | reqwest::Method::HEAD
            | reqwest::Method::PUT
            | reqwest::Method::DELETE
            | reqwest::Method::OPTIONS
    )
}

/// Full-jitter backoff for a zero-based retry attempt index.
pub fn backoff_delay(attempt: u32, opts: &RetryOptions) -> Duration {
    let mut ceiling = opts.base_delay;
    for _ in 0..attempt {
        if ceiling >= opts.max_delay / 2 {
            ceiling = opts.max_delay;
            break;
        }
        ceiling = ceiling.saturating_mul(2);
    }
    if ceiling > opts.max_delay {
        ceiling = opts.max_delay;
    }
    if ceiling.is_zero() {
        return Duration::ZERO;
    }
    let nanos = ceiling.as_nanos() as u64;
    // Cheap LCG-ish jitter without pulling in a rand crate.
    let seed = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_nanos() as u64)
        .unwrap_or(1)
        .wrapping_mul(6364136223846793005)
        .wrapping_add(attempt as u64);
    let jitter = if nanos == 0 { 0 } else { seed % nanos };
    Duration::from_nanos(jitter)
}
