// Code generated by specforge. DO NOT EDIT.

use std::pin::Pin;

use futures_util::Stream;
use futures_util::StreamExt;

use crate::error::{Error, Result};

/// One Server-Sent Event message.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ServerSentEvent {
    pub event: String,
    pub data: String,
    pub id: Option<String>,
}

/// Async SSE parser over a byte stream (e.g. `response.bytes_stream()`).
pub struct SseStream<S> {
    inner: Pin<Box<S>>,
    buffer: String,
    pending: Option<ServerSentEvent>,
    done: bool,
}

impl<S> SseStream<S>
where
    S: Stream<Item = std::result::Result<bytes::Bytes, reqwest::Error>> + Send + Unpin,
{
    pub fn new(inner: S) -> Self {
        Self {
            inner: Box::pin(inner),
            buffer: String::new(),
            pending: None,
            done: false,
        }
    }

    /// Pull the next event, or `None` on end-of-stream.
    pub async fn next_event(&mut self) -> Result<Option<ServerSentEvent>> {
        if let Some(ev) = self.pending.take() {
            return Ok(Some(ev));
        }
        if self.done {
            return Ok(None);
        }
        loop {
            if let Some(ev) = self.drain_one() {
                return Ok(Some(ev));
            }
            match self.inner.next().await {
                Some(Ok(chunk)) => {
                    self.buffer
                        .push_str(&String::from_utf8_lossy(&chunk));
                }
                Some(Err(e)) => return Err(Error::Transport(e)),
                None => {
                    self.done = true;
                    // Flush trailing event without blank-line terminator.
                    if let Some(ev) = self.drain_one_force() {
                        return Ok(Some(ev));
                    }
                    return Ok(None);
                }
            }
        }
    }

    fn drain_one(&mut self) -> Option<ServerSentEvent> {
        if let Some(idx) = self.buffer.find("\n\n") {
            let block = self.buffer[..idx].to_string();
            self.buffer = self.buffer[idx + 2..].to_string();
            return parse_sse_block(&block);
        }
        // Also handle CRLF blank lines.
        if let Some(idx) = self.buffer.find("\r\n\r\n") {
            let block = self.buffer[..idx].to_string();
            self.buffer = self.buffer[idx + 4..].to_string();
            return parse_sse_block(&block);
        }
        None
    }

    fn drain_one_force(&mut self) -> Option<ServerSentEvent> {
        if self.buffer.trim().is_empty() {
            return None;
        }
        let block = std::mem::take(&mut self.buffer);
        parse_sse_block(&block)
    }
}

fn parse_sse_block(block: &str) -> Option<ServerSentEvent> {
    let mut event = "message".to_string();
    let mut data: Vec<String> = Vec::new();
    let mut id: Option<String> = None;
    for line in block.lines() {
        let line = line.strip_suffix('\r').unwrap_or(line);
        if line.is_empty() || line.starts_with(':') {
            continue;
        }
        let (field, value) = match line.split_once(':') {
            Some((f, v)) => (f, v.strip_prefix(' ').unwrap_or(v)),
            None => (line, ""),
        };
        match field {
            "event" => event = value.to_string(),
            "data" => data.push(value.to_string()),
            "id" => id = Some(value.to_string()),
            "retry" => {}
            _ => {}
        }
    }
    if data.is_empty() && event == "message" {
        return None;
    }
    Some(ServerSentEvent {
        event,
        data: data.join("\n"),
        id,
    })
}
