// Code generated by specforge. DO NOT EDIT.

//! Telemetry hooks for request lifecycle observability.

/// Telemetry hooks for observing the SDK request lifecycle.
pub trait TelemetryHooks: Send + Sync + std::fmt::Debug {
    fn on_request_start(&self, _method: &str, _path: &str) {}
    fn on_request_end(&self, _method: &str, _path: &str, _duration_ms: u128, _status: u16) {}
    fn on_request_error(&self, _method: &str, _path: &str, _duration_ms: u128, _error: &crate::error::Error) {}
    fn on_retry(&self, _method: &str, _path: &str, _attempt: u32, _error: &crate::error::Error) {}
    fn on_cache_hit(&self, _method: &str, _path: &str) {}
    fn on_cache_miss(&self, _method: &str, _path: &str) {}
}

/// Built-in metrics collector.
#[derive(Debug, Clone, Default)]
pub struct MetricsCollector {
    inner: std::sync::Arc<tokio::sync::Mutex<MetricsInner>>,
}

#[derive(Debug, Clone, Default)]
struct MetricsInner {
    request_count: u64,
    error_count: u64,
    total_duration_ms: u64,
    retry_count: u64,
}

#[derive(Debug, Clone)]
pub struct Metrics {
    pub request_count: u64,
    pub error_count: u64,
    pub total_duration_ms: u64,
    pub avg_duration_ms: f64,
    pub retry_count: u64,
}

impl MetricsCollector {
    pub fn new() -> Self { Self::default() }
    pub async fn get_metrics(&self) -> Metrics {
        let m = self.inner.lock().await;
        Metrics {
            request_count: m.request_count,
            error_count: m.error_count,
            total_duration_ms: m.total_duration_ms,
            avg_duration_ms: if m.request_count > 0 { m.total_duration_ms as f64 / m.request_count as f64 } else { 0.0 },
            retry_count: m.retry_count,
        }
    }
}

impl TelemetryHooks for MetricsCollector {
    fn on_request_start(&self, _: &str, _: &str) {
        let inner = self.inner.clone();
        tokio::spawn(async move { inner.lock().await.request_count += 1; });
    }
    fn on_request_end(&self, _: &str, _: &str, dur_ms: u128, status: u16) {
        let inner = self.inner.clone();
        tokio::spawn(async move {
            let mut m = inner.lock().await;
            m.total_duration_ms += dur_ms as u64;
            if status >= 400 { m.error_count += 1; }
        });
    }
    fn on_request_error(&self, _: &str, _: &str, dur_ms: u128, _: &crate::error::Error) {
        let inner = self.inner.clone();
        tokio::spawn(async move {
            let mut m = inner.lock().await;
            m.error_count += 1;
            m.total_duration_ms += dur_ms as u64;
        });
    }
    fn on_retry(&self, _: &str, _: &str, _: u32, _: &crate::error::Error) {
        let inner = self.inner.clone();
        tokio::spawn(async move { inner.lock().await.retry_count += 1; });
    }
}
