// Code generated by specforge. DO NOT EDIT.

//! Runtime validation of values against the OpenAPI schema.
//!
//! Each model gets a `validate_<model>` function that checks required fields,
//! types, enum values, and recursively validates nested objects.

use serde_json::Value;

/// A single validation error with a JSON-path-style location and message.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ValidationError {
    /// JSON-pointer-style path to the offending value (e.g. `.items[2].name`).
    pub path: String,
    /// Human-readable description of what went wrong.
    pub message: String,
}

impl std::fmt::Display for ValidationError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}: {}", self.path, self.message)
    }
}

impl std::error::Error for ValidationError {}

/// Validate a JSON value as an object, returning any errors found.
fn validate_object_fields(
    value: &Value,
    required: &[&str],
    path: &str,
) -> Vec<ValidationError> {
    let mut errors = Vec::new();
    let obj = match value.as_object() {
        Some(o) => o,
        None => {
            errors.push(ValidationError {
                path: path.to_string(),
                message: format!("expected object, got {}", value_type_name(value)),
            });
            return errors;
        }
    };
    for field in required {
        if !obj.contains_key(*field) {
            errors.push(ValidationError {
                path: if path.is_empty() {
                    field.to_string()
                } else {
                    format!("{path}.{field}")
                },
                message: "missing required field".to_string(),
            });
        }
    }
    errors
}

/// Validate that a string field value is one of the allowed enum values.
fn validate_enum_field(
    value: &Value,
    field: &str,
    allowed: &[&str],
    path: &str,
) -> Vec<ValidationError> {
    let mut errors = Vec::new();
    let obj = match value.as_object() {
        Some(o) => o,
        None => return errors,
    };
    if let Some(val) = obj.get(field) {
        if let Some(s) = val.as_str() {
            if !allowed.contains(&s) {
                let field_path = if path.is_empty() {
                    field.to_string()
                } else {
                    format!("{path}.{field}")
                };
                errors.push(ValidationError {
                    path: field_path,
                    message: format!("invalid enum value: \"{s}\""),
                });
            }
        }
    }
    errors
}

fn value_type_name(v: &Value) -> &'static str {
    match v {
        Value::Null => "null",
        Value::Bool(_) => "boolean",
        Value::Number(_) => "number",
        Value::String(_) => "string",
        Value::Array(_) => "array",
        Value::Object(_) => "object",
    }
}

/// Validate a value against the `Error` schema.
pub fn validate_error(v: &Value) -> Result<(), Vec<ValidationError>> {
    let mut errors = Vec::new();
    errors.extend(validate_object_fields(v, &["code", "message"], ""));
    if errors.is_empty() { Ok(()) } else { Err(errors) }
}

/// Validate a value against the `Pet` schema.
pub fn validate_pet(v: &Value) -> Result<(), Vec<ValidationError>> {
    let mut errors = Vec::new();
    errors.extend(validate_object_fields(v, &["id", "name"], ""));
    if errors.is_empty() { Ok(()) } else { Err(errors) }
}

/// Validate a value against the `Pets` schema.
pub fn validate_pets(v: &Value) -> Result<(), Vec<ValidationError>> {
    let mut errors = Vec::new();
    if !v.is_object() {
        errors.push(ValidationError {
            path: String::new(),
            message: format!("expected object, got {}", value_type_name(v)),
        });
    }
    if errors.is_empty() { Ok(()) } else { Err(errors) }
}

