// Code generated by specforge. DO NOT EDIT.

//! Automatic request/response validation middleware that intercepts all
//! requests and validates bodies against the OpenAPI schema.

use std::collections::HashMap;
use std::sync::Arc;

use serde_json::Value;

use crate::error::{Error, Result};
use crate::middleware::{Middleware, MiddlewareRequest, MiddlewareResponse, NextFn};
use crate::validate::ValidationError;

/// Schema descriptor for an endpoint's request and/or response body validator.
pub struct EndpointSchema {
    /// Validator function for the request body. None means no validation.
    pub request_body: Option<fn(&Value) -> std::result::Result<(), Vec<ValidationError>>>,
    /// Validator function for the response body. None means no validation.
    pub response_body: Option<fn(&Value) -> std::result::Result<(), Vec<ValidationError>>>,
}

/// Route schema map keyed by "METHOD /path/pattern".
/// Patterns use `{param}` placeholders for path segments.
pub type RouteSchemaMap = HashMap<String, EndpointSchema>;

/// Check if `actual_path` matches the `pattern` path.
/// Pattern segments wrapped in `{...}` are treated as wildcards.
fn matches_path(pattern: &str, actual_path: &str) -> bool {
    let pattern_segments: Vec<&str> = pattern.trim_matches('/').split('/').filter(|s| !s.is_empty()).collect();
    let actual_segments: Vec<&str> = actual_path.trim_matches('/').split('/').filter(|s| !s.is_empty()).collect();
    if pattern_segments.len() != actual_segments.len() {
        return false;
    }
    for (ps, as_) in pattern_segments.iter().zip(actual_segments.iter()) {
        if ps.starts_with('{') && ps.ends_with('}') {
            continue; // wildcard
        }
        if ps != as_ {
            return false;
        }
    }
    true
}

/// Create a validation middleware that intercepts all requests and validates
/// request/response bodies against the OpenAPI schema.
///
/// # Usage
///
/// ```ignore
/// use std::collections::HashMap;
/// use sdk::validation_middleware::{validation_middleware, EndpointSchema, RouteSchemaMap};
/// use sdk::validate::validate_pet;
///
/// let mut schemas: RouteSchemaMap = HashMap::new();
/// schemas.insert(
///     "POST /pets".to_string(),
///     EndpointSchema {
///         request_body: Some(validate_pet),
///         response_body: Some(validate_pet),
///     },
/// );
/// schemas.insert(
///     "GET /pets/{petId}".to_string(),
///     EndpointSchema {
///         request_body: None,
///         response_body: Some(validate_pet),
///     },
/// );
///
/// client.use_middleware(validation_middleware(schemas));
/// ```
pub fn validation_middleware(schemas: RouteSchemaMap) -> Middleware {
    let schemas = Arc::new(schemas);
    Arc::new(move |req: MiddlewareRequest, next: NextFn| {
        let schemas = Arc::clone(&schemas);
        Box::pin(async move {
            let method = req.method.as_str().to_uppercase();
            let path = req.url.split('?').next().unwrap_or("").to_string();

            // Find a matching route schema.
            let route_key = format!("{} {}", method, path);
            let endpoint_schema = schemas.get(&route_key).or_else(|| {
                schemas.iter().find_map(|(pattern, schema)| {
                    let space_idx = pattern.find(' ')?;
                    let pattern_method = pattern[..space_idx].to_uppercase();
                    let pattern_path = &pattern[space_idx + 1..];
                    if pattern_method == method && matches_path(pattern_path, &path) {
                        Some(schema)
                    } else {
                        None
                    }
                })
            });

            // Validate request body if a schema is defined.
            if let Some(schema) = endpoint_schema {
                if let Some(validator) = schema.request_body {
                    if let Some(body_bytes) = &req.body {
                        if !body_bytes.is_empty() {
                            if let Ok(body) = serde_json::from_slice::<Value>(body_bytes) {
                                if let Err(errors) = validator(&body) {
                                    let msg: Vec<String> = errors.iter().map(|e| format!("{}: {}", e.path, e.message)).collect();
                                    return Err(Error::Message(format!(
                                        "[validation] {} {} request body: {}",
                                        method, path, msg.join("; ")
                                    )));
                                }
                            }
                        }
                    }
                }
            }

            // Proceed with the request.
            let resp = next(req).await?;

            // Validate response body if a schema is defined.
            if let Some(schema) = endpoint_schema {
                if let Some(validator) = schema.response_body {
                    if resp.status >= 200 && resp.status < 300 && !resp.body.is_empty() {
                        let is_json = resp.headers
                            .get("content-type")
                            .and_then(|v| v.to_str().ok())
                            .map(|ct| ct.contains("application/json"))
                            .unwrap_or(false);
                        if is_json {
                            if let Ok(body) = serde_json::from_slice::<Value>(&resp.body) {
                                if let Err(errors) = validator(&body) {
                                    let msg: Vec<String> = errors.iter().map(|e| format!("{}: {}", e.path, e.message)).collect();
                                    return Err(Error::Message(format!(
                                        "[validation] {} {} response {}: {}",
                                        method, path, resp.status, msg.join("; ")
                                    )));
                                }
                            }
                        }
                    }
                }
            }

            Ok(resp)
        })
    })
}
