//! Generate a working demo Petstore spec with realistic examples.
//!
//! The demo spec is a fully self-contained OpenAPI 3.0.3 YAML that can be
//! loaded directly into Swagger Editor. It includes realistic request/response
//! examples for every operation, making it useful as a reference or starting
//! point for new APIs.

/// Generate the demo Petstore spec as a YAML string.
pub fn generate_demo_spec() -> String {
    // We build the spec as a serde_json::Value for reliable escaping,
    // then serialize to YAML.
    let spec = build_demo_spec_json();
    serde_yaml::to_string(&spec).expect("demo spec serialization should not fail")
}

/// Build the demo Petstore spec as a JSON value.
fn build_demo_spec_json() -> serde_json::Value {
    serde_json::json!({
        "openapi": "3.0.3",
        "info": {
            "title": "SpecForge Demo Petstore API",
            "description": "A fully-featured Petstore API generated by specforge. This spec includes realistic examples for every operation and is designed to work with Swagger Editor.",
            "version": "1.0.0",
            "contact": {
                "name": "SpecForge Team",
                "url": "https://github.com/amafjarkasi/specforge-openapi-sdk-codegen"
            },
            "license": {
                "name": "MIT",
                "url": "https://opensource.org/licenses/MIT"
            }
        },
        "servers": [
            {
                "url": "https://petstore.example.com/v1",
                "description": "Production server"
            },
            {
                "url": "http://localhost:3000",
                "description": "Local development server"
            }
        ],
        "security": [
            { "BearerAuth": [] }
        ],
        "tags": [
            {
                "name": "pets",
                "description": "Pet management operations",
                "externalDocs": {
                    "description": "Find out more about pets",
                    "url": "https://example.com/docs/pets"
                }
            },
            {
                "name": "store",
                "description": "Store and order operations"
            },
            {
                "name": "users",
                "description": "User management"
            }
        ],
        "paths": {
            "/pets": {
                "get": {
                    "operationId": "listPets",
                    "tags": ["pets"],
                    "summary": "List all pets",
                    "description": "Returns a paginated list of pets. Supports filtering by species and cursor-based pagination.",
                    "parameters": [
                        {
                            "name": "limit",
                            "in": "query",
                            "required": false,
                            "description": "Maximum number of pets to return (1-100, default 20)",
                            "schema": {
                                "type": "integer",
                                "format": "int32",
                                "minimum": 1,
                                "maximum": 100,
                                "default": 20,
                                "example": 20
                            }
                        },
                        {
                            "name": "cursor",
                            "in": "query",
                            "required": false,
                            "description": "Pagination cursor from a previous response",
                            "schema": {
                                "type": "string",
                                "example": "eyJpZCI6MTAwfQ=="
                            }
                        },
                        {
                            "name": "species",
                            "in": "query",
                            "required": false,
                            "description": "Filter by species",
                            "schema": {
                                "$ref": "#/components/schemas/Species"
                            }
                        }
                    ],
                    "responses": {
                        "200": {
                            "description": "A paginated list of pets",
                            "content": {
                                "application/json": {
                                    "schema": {
                                        "$ref": "#/components/schemas/PetPage"
                                    },
                                    "example": {
                                        "items": [
                                            {
                                                "id": "pet-abc-123",
                                                "name": "Buddy",
                                                "species": "dog",
                                                "breed": "Golden Retriever",
                                                "age": 3,
                                                "rating": 4.8,
                                                "tags": [
                                                    { "name": "friendly", "color": "green" },
                                                    { "name": "trained", "color": "blue" }
                                                ],
                                                "createdAt": "2024-01-15T10:30:00Z"
                                            }
                                        ],
                                        "nextCursor": "eyJpZCI6InBldC1hYmMtMTIzIn0=",
                                        "hasMore": true
                                    }
                                }
                            }
                        },
                        "400": {
                            "$ref": "#/components/responses/BadRequest"
                        }
                    }
                },
                "post": {
                    "operationId": "createPet",
                    "tags": ["pets"],
                    "summary": "Create a new pet",
                    "description": "Adds a new pet to the store. The pet will be assigned a unique ID automatically.",
                    "requestBody": {
                        "required": true,
                        "description": "The pet to create",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/NewPet"
                                },
                                "example": {
                                    "name": "Max",
                                    "species": "dog",
                                    "breed": "Labrador",
                                    "age": 2,
                                    "tags": [
                                        { "name": "puppy", "color": "yellow" }
                                    ]
                                }
                            }
                        }
                    },
                    "responses": {
                        "201": {
                            "description": "Pet created successfully",
                            "content": {
                                "application/json": {
                                    "schema": {
                                        "$ref": "#/components/schemas/Pet"
                                    },
                                    "example": {
                                        "id": "pet-def-456",
                                        "name": "Max",
                                        "species": "dog",
                                        "breed": "Labrador",
                                        "age": 2,
                                        "rating": null,
                                        "tags": [
                                            { "name": "puppy", "color": "yellow" }
                                        ],
                                        "createdAt": "2024-06-01T14:20:00Z"
                                    }
                                }
                            }
                        },
                        "400": {
                            "$ref": "#/components/responses/BadRequest"
                        }
                    }
                }
            },
            "/pets/{petId}": {
                "get": {
                    "operationId": "getPet",
                    "tags": ["pets"],
                    "summary": "Get a pet by ID",
                    "description": "Returns the details of a single pet identified by its unique ID.",
                    "parameters": [
                        {
                            "$ref": "#/components/parameters/PetId"
                        }
                    ],
                    "responses": {
                        "200": {
                            "description": "Pet details",
                            "content": {
                                "application/json": {
                                    "schema": {
                                        "$ref": "#/components/schemas/Pet"
                                    },
                                    "example": {
                                        "id": "pet-abc-123",
                                        "name": "Buddy",
                                        "species": "dog",
                                        "breed": "Golden Retriever",
                                        "age": 3,
                                        "rating": 4.8,
                                        "tags": [
                                            { "name": "friendly", "color": "green" }
                                        ],
                                        "createdAt": "2024-01-15T10:30:00Z"
                                    }
                                }
                            }
                        },
                        "404": {
                            "$ref": "#/components/responses/NotFound"
                        }
                    }
                },
                "patch": {
                    "operationId": "updatePet",
                    "tags": ["pets"],
                    "summary": "Update a pet",
                    "description": "Partially updates an existing pet. Only the provided fields are updated.",
                    "parameters": [
                        {
                            "$ref": "#/components/parameters/PetId"
                        }
                    ],
                    "requestBody": {
                        "required": true,
                        "description": "Fields to update",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/UpdatePet"
                                },
                                "example": {
                                    "name": "Buddy Jr.",
                                    "age": 4
                                }
                            }
                        }
                    },
                    "responses": {
                        "200": {
                            "description": "Pet updated successfully",
                            "content": {
                                "application/json": {
                                    "schema": {
                                        "$ref": "#/components/schemas/Pet"
                                    },
                                    "example": {
                                        "id": "pet-abc-123",
                                        "name": "Buddy Jr.",
                                        "species": "dog",
                                        "breed": "Golden Retriever",
                                        "age": 4,
                                        "rating": 4.8,
                                        "tags": [
                                            { "name": "friendly", "color": "green" }
                                        ],
                                        "createdAt": "2024-01-15T10:30:00Z"
                                    }
                                }
                            }
                        },
                        "404": {
                            "$ref": "#/components/responses/NotFound"
                        }
                    }
                },
                "delete": {
                    "operationId": "deletePet",
                    "tags": ["pets"],
                    "summary": "Delete a pet",
                    "description": "Removes a pet from the store. This action cannot be undone.",
                    "parameters": [
                        {
                            "$ref": "#/components/parameters/PetId"
                        }
                    ],
                    "responses": {
                        "204": {
                            "description": "Pet deleted successfully"
                        },
                        "404": {
                            "$ref": "#/components/responses/NotFound"
                        }
                    }
                }
            },
            "/store/orders": {
                "post": {
                    "operationId": "createOrder",
                    "tags": ["store"],
                    "summary": "Place an order",
                    "description": "Places a new order for a pet. The order will be processed immediately.",
                    "requestBody": {
                        "required": true,
                        "description": "Order details",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/NewOrder"
                                },
                                "example": {
                                    "petId": "pet-abc-123",
                                    "quantity": 1,
                                    "shippingAddress": "123 Pet Street, Dogtown, CA 90210"
                                }
                            }
                        }
                    },
                    "responses": {
                        "201": {
                            "description": "Order placed successfully",
                            "content": {
                                "application/json": {
                                    "schema": {
                                        "$ref": "#/components/schemas/Order"
                                    },
                                    "example": {
                                        "id": 1001,
                                        "petId": "pet-abc-123",
                                        "quantity": 1,
                                        "status": "placed",
                                        "shippingAddress": "123 Pet Street, Dogtown, CA 90210",
                                        "placedAt": "2024-06-01T15:00:00Z"
                                    }
                                }
                            }
                        },
                        "400": {
                            "$ref": "#/components/responses/BadRequest"
                        }
                    }
                }
            },
            "/store/orders/{orderId}": {
                "get": {
                    "operationId": "getOrder",
                    "tags": ["store"],
                    "summary": "Get order details",
                    "description": "Returns the details of a specific order by its ID.",
                    "parameters": [
                        {
                            "name": "orderId",
                            "in": "path",
                            "required": true,
                            "description": "The order ID",
                            "schema": {
                                "type": "integer",
                                "format": "int64",
                                "example": 1001
                            }
                        }
                    ],
                    "responses": {
                        "200": {
                            "description": "Order details",
                            "content": {
                                "application/json": {
                                    "schema": {
                                        "$ref": "#/components/schemas/Order"
                                    },
                                    "example": {
                                        "id": 1001,
                                        "petId": "pet-abc-123",
                                        "quantity": 1,
                                        "status": "approved",
                                        "shippingAddress": "123 Pet Street, Dogtown, CA 90210",
                                        "placedAt": "2024-06-01T15:00:00Z"
                                    }
                                }
                            }
                        },
                        "404": {
                            "$ref": "#/components/responses/NotFound"
                        }
                    }
                }
            },
            "/users": {
                "post": {
                    "operationId": "createUser",
                    "tags": ["users"],
                    "summary": "Create a new user",
                    "description": "Registers a new user account in the system.",
                    "requestBody": {
                        "required": true,
                        "description": "User registration data",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/NewUser"
                                },
                                "example": {
                                    "username": "petlover42",
                                    "email": "petlover@example.com",
                                    "fullName": "Jane Smith"
                                }
                            }
                        }
                    },
                    "responses": {
                        "201": {
                            "description": "User created successfully",
                            "content": {
                                "application/json": {
                                    "schema": {
                                        "$ref": "#/components/schemas/User"
                                    },
                                    "example": {
                                        "id": "user-789",
                                        "username": "petlover42",
                                        "email": "petlover@example.com",
                                        "fullName": "Jane Smith",
                                        "role": "user",
                                        "createdAt": "2024-06-01T16:00:00Z"
                                    }
                                }
                            }
                        },
                        "400": {
                            "$ref": "#/components/responses/BadRequest"
                        }
                    }
                }
            },
            "/users/{userId}": {
                "get": {
                    "operationId": "getUser",
                    "tags": ["users"],
                    "summary": "Get a user by ID",
                    "description": "Returns the public profile of a user.",
                    "parameters": [
                        {
                            "name": "userId",
                            "in": "path",
                            "required": true,
                            "description": "The user ID",
                            "schema": {
                                "type": "string",
                                "example": "user-789"
                            }
                        }
                    ],
                    "responses": {
                        "200": {
                            "description": "User profile",
                            "content": {
                                "application/json": {
                                    "schema": {
                                        "$ref": "#/components/schemas/User"
                                    },
                                    "example": {
                                        "id": "user-789",
                                        "username": "petlover42",
                                        "email": "petlover@example.com",
                                        "fullName": "Jane Smith",
                                        "role": "user",
                                        "createdAt": "2024-06-01T16:00:00Z"
                                    }
                                }
                            }
                        },
                        "404": {
                            "$ref": "#/components/responses/NotFound"
                        }
                    }
                }
            },
            "/health": {
                "get": {
                    "operationId": "getHealth",
                    "tags": [],
                    "summary": "Health check",
                    "description": "Returns the health status of the API. Used for monitoring and load balancer checks.",
                    "responses": {
                        "200": {
                            "description": "Service is healthy",
                            "content": {
                                "application/json": {
                                    "schema": {
                                        "$ref": "#/components/schemas/HealthResponse"
                                    },
                                    "example": {
                                        "status": "ok",
                                        "timestamp": "2024-06-01T12:00:00Z",
                                        "version": "1.0.0"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "components": {
            "securitySchemes": {
                "BearerAuth": {
                    "type": "http",
                    "scheme": "bearer",
                    "bearerFormat": "JWT",
                    "description": "JWT Bearer token authentication"
                }
            },
            "parameters": {
                "PetId": {
                    "name": "petId",
                    "in": "path",
                    "required": true,
                    "description": "The unique identifier of the pet",
                    "schema": {
                        "type": "string",
                        "example": "pet-abc-123"
                    }
                }
            },
            "responses": {
                "BadRequest": {
                    "description": "The request was invalid or missing required fields",
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Error"
                            },
                            "example": {
                                "code": 400,
                                "message": "Validation failed: 'name' is required",
                                "details": {
                                    "field": "name",
                                    "constraint": "required"
                                }
                            }
                        }
                    }
                },
                "NotFound": {
                    "description": "The requested resource was not found",
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Error"
                            },
                            "example": {
                                "code": 404,
                                "message": "Pet not found with the given ID",
                                "details": null
                            }
                        }
                    }
                },
                "Unauthorized": {
                    "description": "Authentication is required",
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Error"
                            },
                            "example": {
                                "code": 401,
                                "message": "Bearer token is missing or invalid",
                                "details": null
                            }
                        }
                    }
                }
            },
            "schemas": {
                "Species": {
                    "description": "The species of a pet",
                    "type": "string",
                    "enum": ["dog", "cat", "bird", "reptile", "fish", "hamster"],
                    "example": "dog"
                },
                "Tag": {
                    "description": "A label attached to a pet for categorization",
                    "type": "object",
                    "required": ["name"],
                    "properties": {
                        "name": {
                            "description": "Tag name",
                            "type": "string",
                            "example": "friendly"
                        },
                        "color": {
                            "description": "Tag display color",
                            "type": "string",
                            "example": "green"
                        }
                    }
                },
                "Pet": {
                    "description": "A pet available in the store",
                    "type": "object",
                    "required": ["id", "name", "species", "createdAt"],
                    "properties": {
                        "id": {
                            "description": "Unique identifier for the pet",
                            "type": "string",
                            "example": "pet-abc-123"
                        },
                        "name": {
                            "description": "The pet's name",
                            "type": "string",
                            "example": "Buddy"
                        },
                        "species": {
                            "$ref": "#/components/schemas/Species"
                        },
                        "breed": {
                            "description": "The pet's breed (optional)",
                            "type": "string",
                            "nullable": true,
                            "example": "Golden Retriever"
                        },
                        "tags": {
                            "description": "Tags attached to the pet",
                            "type": "array",
                            "items": {
                                "$ref": "#/components/schemas/Tag"
                            }
                        },
                        "age": {
                            "description": "Pet age in years (nullable)",
                            "type": "integer",
                            "format": "int32",
                            "nullable": true,
                            "minimum": 0,
                            "example": 3
                        },
                        "rating": {
                            "description": "Average customer rating (1.0-5.0)",
                            "type": "number",
                            "format": "float",
                            "nullable": true,
                            "minimum": 1.0,
                            "maximum": 5.0,
                            "example": 4.8
                        },
                        "createdAt": {
                            "description": "Timestamp when the pet was added",
                            "type": "string",
                            "format": "date-time",
                            "example": "2024-01-15T10:30:00Z"
                        }
                    }
                },
                "NewPet": {
                    "description": "Data required to create a new pet",
                    "type": "object",
                    "required": ["name", "species"],
                    "properties": {
                        "name": {
                            "description": "The pet's name",
                            "type": "string",
                            "example": "Max"
                        },
                        "species": {
                            "$ref": "#/components/schemas/Species"
                        },
                        "breed": {
                            "description": "The pet's breed (optional)",
                            "type": "string",
                            "example": "Labrador"
                        },
                        "age": {
                            "description": "Pet age in years",
                            "type": "integer",
                            "format": "int32",
                            "minimum": 0,
                            "example": 2
                        },
                        "tags": {
                            "description": "Initial tags for the pet",
                            "type": "array",
                            "items": {
                                "$ref": "#/components/schemas/Tag"
                            }
                        }
                    }
                },
                "UpdatePet": {
                    "description": "Fields to update on an existing pet",
                    "type": "object",
                    "properties": {
                        "name": {
                            "description": "New name for the pet",
                            "type": "string",
                            "example": "Buddy Jr."
                        },
                        "breed": {
                            "description": "New breed",
                            "type": "string",
                            "nullable": true,
                            "example": "Labrador"
                        },
                        "age": {
                            "description": "New age in years",
                            "type": "integer",
                            "format": "int32",
                            "minimum": 0,
                            "example": 4
                        },
                        "tags": {
                            "description": "Replace all tags",
                            "type": "array",
                            "items": {
                                "$ref": "#/components/schemas/Tag"
                            }
                        }
                    }
                },
                "PetPage": {
                    "description": "A paginated list of pets",
                    "type": "object",
                    "required": ["items"],
                    "properties": {
                        "items": {
                            "description": "List of pets in this page",
                            "type": "array",
                            "items": {
                                "$ref": "#/components/schemas/Pet"
                            }
                        },
                        "nextCursor": {
                            "description": "Cursor for the next page (null if no more pages)",
                            "type": "string",
                            "nullable": true,
                            "example": "eyJpZCI6InBldC1hYmMtMTIzIn0="
                        },
                        "hasMore": {
                            "description": "Whether there are more pages available",
                            "type": "boolean",
                            "example": true
                        }
                    }
                },
                "Order": {
                    "description": "A pet order in the store",
                    "type": "object",
                    "required": ["id", "petId", "quantity", "status", "placedAt"],
                    "properties": {
                        "id": {
                            "description": "Unique order identifier",
                            "type": "integer",
                            "format": "int64",
                            "example": 1001
                        },
                        "petId": {
                            "description": "ID of the pet being ordered",
                            "type": "string",
                            "example": "pet-abc-123"
                        },
                        "quantity": {
                            "description": "Number of pets to order",
                            "type": "integer",
                            "minimum": 1,
                            "example": 1
                        },
                        "status": {
                            "$ref": "#/components/schemas/OrderStatus"
                        },
                        "shippingAddress": {
                            "description": "Delivery address",
                            "type": "string",
                            "nullable": true,
                            "example": "123 Pet Street, Dogtown, CA 90210"
                        },
                        "placedAt": {
                            "description": "Timestamp when the order was placed",
                            "type": "string",
                            "format": "date-time",
                            "example": "2024-06-01T15:00:00Z"
                        },
                        "shippedAt": {
                            "description": "Timestamp when the order was shipped (null if not yet shipped)",
                            "type": "string",
                            "format": "date-time",
                            "nullable": true
                        }
                    }
                },
                "NewOrder": {
                    "description": "Data required to place a new order",
                    "type": "object",
                    "required": ["petId", "quantity"],
                    "properties": {
                        "petId": {
                            "description": "ID of the pet to order",
                            "type": "string",
                            "example": "pet-abc-123"
                        },
                        "quantity": {
                            "description": "Number of pets to order",
                            "type": "integer",
                            "minimum": 1,
                            "example": 1
                        },
                        "shippingAddress": {
                            "description": "Delivery address",
                            "type": "string",
                            "example": "123 Pet Street, Dogtown, CA 90210"
                        }
                    }
                },
                "OrderStatus": {
                    "description": "Current status of an order",
                    "type": "string",
                    "enum": ["placed", "approved", "shipped", "delivered", "cancelled"],
                    "example": "placed"
                },
                "User": {
                    "description": "A registered user in the system",
                    "type": "object",
                    "required": ["id", "username", "email", "role", "createdAt"],
                    "properties": {
                        "id": {
                            "description": "Unique user identifier",
                            "type": "string",
                            "example": "user-789"
                        },
                        "username": {
                            "description": "Login username",
                            "type": "string",
                            "example": "petlover42"
                        },
                        "email": {
                            "description": "Email address",
                            "type": "string",
                            "format": "email",
                            "example": "petlover@example.com"
                        },
                        "fullName": {
                            "description": "Full display name",
                            "type": "string",
                            "nullable": true,
                            "example": "Jane Smith"
                        },
                        "role": {
                            "$ref": "#/components/schemas/UserRole"
                        },
                        "createdAt": {
                            "description": "Account creation timestamp",
                            "type": "string",
                            "format": "date-time",
                            "example": "2024-06-01T16:00:00Z"
                        }
                    }
                },
                "NewUser": {
                    "description": "Data required to register a new user",
                    "type": "object",
                    "required": ["username", "email"],
                    "properties": {
                        "username": {
                            "description": "Desired login username",
                            "type": "string",
                            "minLength": 3,
                            "maxLength": 30,
                            "example": "petlover42"
                        },
                        "email": {
                            "description": "Email address",
                            "type": "string",
                            "format": "email",
                            "example": "petlover@example.com"
                        },
                        "fullName": {
                            "description": "Full display name",
                            "type": "string",
                            "example": "Jane Smith"
                        },
                        "password": {
                            "description": "Account password (min 8 characters)",
                            "type": "string",
                            "format": "password",
                            "minLength": 8
                        }
                    }
                },
                "UserRole": {
                    "description": "The role of a user in the system",
                    "type": "string",
                    "enum": ["user", "admin", "moderator"],
                    "example": "user"
                },
                "HealthResponse": {
                    "description": "API health status response",
                    "type": "object",
                    "required": ["status"],
                    "properties": {
                        "status": {
                            "description": "Current health status",
                            "type": "string",
                            "enum": ["ok", "degraded", "down"],
                            "example": "ok"
                        },
                        "timestamp": {
                            "description": "Current server timestamp",
                            "type": "string",
                            "format": "date-time",
                            "example": "2024-06-01T12:00:00Z"
                        },
                        "version": {
                            "description": "API version",
                            "type": "string",
                            "example": "1.0.0"
                        }
                    }
                },
                "Error": {
                    "description": "Standard error response returned by the API",
                    "type": "object",
                    "required": ["code", "message"],
                    "properties": {
                        "code": {
                            "description": "HTTP status code",
                            "type": "integer",
                            "format": "int32",
                            "example": 400
                        },
                        "message": {
                            "description": "Human-readable error message",
                            "type": "string",
                            "example": "Validation failed: 'name' is required"
                        },
                        "details": {
                            "description": "Additional error details (nullable)",
                            "type": "object",
                            "nullable": true,
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn demo_spec_is_valid_yaml() {
        let yaml = generate_demo_spec();
        let parsed: serde_json::Value = serde_yaml::from_str(&yaml).unwrap();
        assert_eq!(parsed["openapi"], "3.0.3");
    }

    #[test]
    fn demo_spec_has_all_operations() {
        let yaml = generate_demo_spec();
        let parsed: serde_json::Value = serde_yaml::from_str(&yaml).unwrap();

        let paths = parsed["paths"].as_object().unwrap();
        assert!(paths.contains_key("/pets"));
        assert!(paths.contains_key("/pets/{petId}"));
        assert!(paths.contains_key("/store/orders"));
        assert!(paths.contains_key("/store/orders/{orderId}"));
        assert!(paths.contains_key("/users"));
        assert!(paths.contains_key("/users/{userId}"));
        assert!(paths.contains_key("/health"));
    }

    #[test]
    fn demo_spec_has_examples() {
        let yaml = generate_demo_spec();
        let parsed: serde_json::Value = serde_yaml::from_str(&yaml).unwrap();

        // Check that responses have examples
        let list_pets = &parsed["paths"]["/pets"]["get"];
        let resp_200 = &list_pets["responses"]["200"]["content"]["application/json"];
        assert!(
            resp_200.get("example").is_some(),
            "listPets response should have an example"
        );
    }

    #[test]
    fn demo_spec_has_components() {
        let yaml = generate_demo_spec();
        let parsed: serde_json::Value = serde_yaml::from_str(&yaml).unwrap();

        let schemas = parsed["components"]["schemas"].as_object().unwrap();
        assert!(schemas.contains_key("Pet"));
        assert!(schemas.contains_key("Error"));
        assert!(schemas.contains_key("Order"));
        assert!(schemas.contains_key("User"));
        assert!(schemas.contains_key("HealthResponse"));
    }

    #[test]
    fn demo_spec_all_schemas_have_descriptions() {
        let yaml = generate_demo_spec();
        let parsed: serde_json::Value = serde_yaml::from_str(&yaml).unwrap();

        let schemas = parsed["components"]["schemas"].as_object().unwrap();
        for (name, schema) in schemas {
            assert!(
                schema.get("description").is_some(),
                "schema '{name}' should have a description"
            );
        }
    }

    #[test]
    fn demo_spec_all_operations_have_operation_id() {
        let yaml = generate_demo_spec();
        let parsed: serde_json::Value = serde_yaml::from_str(&yaml).unwrap();

        let paths = parsed["paths"].as_object().unwrap();
        for (path, item) in paths {
            for method in &["get", "post", "put", "patch", "delete"] {
                if let Some(op) = item.get(*method) {
                    assert!(
                        op.get("operationId").is_some(),
                        "{method} {path} should have an operationId"
                    );
                }
            }
        }
    }
}
