//! specforge-core
pub mod analyzer;
pub mod changelog;
pub mod dashboard;
pub mod deprecation;
pub mod demo;
pub mod diff;
pub mod docs;
pub mod error;
pub mod evolution;
pub mod graph;
pub mod i18n;
pub mod infer;
pub mod ir;
pub mod lint;
pub mod lint_config;
pub mod merge;
pub mod mock;
pub mod resolve;
pub mod schema31;
pub mod security;
pub mod spec;
pub mod swagger_export;
pub mod testgen;
pub mod validate;
pub mod verify;
pub mod workspace;

pub use deprecation::{find_deprecations, generate_migration_guide, DeprecationInfo, DeprecationKind};
pub use diff::{diff, diff_detailed, format_colored, format_json, format_markdown, format_text, DiffFinding, DiffFormat, DiffJsonOutput, DiffResult, DiffSeverity, DiffSummary, PropertyChange, PropertyChangeKind, SchemaDiffDetail};
pub use error::{ResolveError, SpecError};
pub use i18n::I18nConfig;
pub use merge::merge_specs;
pub use testgen::{generate_tests, TestGenOptions, TestLang};
pub use ir::{Composition, CompositionKind, Discriminator, Document, EnumModel, EnumVariant, HttpMethod, IR_VERSION, Model, ObjectModel, Operation, Parameter, ParamLocation, Property, RequestBody, Response, Scalar, SchemaRegistry, SecurityScheme, Type, Webhook};
pub use demo::generate_demo_spec;
pub use lint::{lint_swagger_editor, Diagnostic, Severity};
pub use lint_config::{LintConfig, LintRule, RuleSeverity};
pub use resolve::{resolve, resolve_with_webhooks};
pub use spec::{detect_31_features, parse_bytes, parse_bytes_full, parse_file, parse_file_full, parse_str, parse_str_full, resolve_spec_path, scan_versions, ParsedSpec, Spec31Features, VersionInfo};
pub use validate::{validate, ValidationError};
pub use workspace::{init_workspace, WorkspaceConfig, WorkspaceInitResult, WorkspaceOutput, WorkspaceRunResult, WorkspaceSpec};
pub use changelog::{generate_changelog, ChangelogOptions};
pub use analyzer::{analyze_spec, AnalysisReport};
pub use graph::{generate_graph, GraphFormat};
pub use dashboard::generate_dashboard;
pub use security::{analyze_security, analyze_security_detailed, OperationSecurity, SecurityIssue, SecurityReport, SecuritySchemeInfo};
pub use infer::{infer_openapi, infer_schema, InferOptions};
pub use verify::{verify_api, VerifyOptions, VerifyResult};
pub use evolution::{track_evolution, format_json as evolution_format_json, format_markdown as evolution_format_markdown, format_text as evolution_format_text, EvolutionFormat, SchemaEvolution, VersionSnapshot};
pub use mock::MockServer;
pub use swagger_export::{export_spec, export_swagger_editor, ExportError, ExportFormat, ExportOptions};
