/* eslint-disable */
// Generated by specforge. DO NOT EDIT.

/**
 * Authentication providers. Pass one to `ApiClientOptions.auth`. Only schemes
 * declared by the spec are emitted; if the spec has no security requirements,
 * this module is minimal.
 */
export interface AnonymousAuthProvider {
  type: "anonymous";
}
export function anonymousAuth(): AnonymousAuthProvider {
  return { type: "anonymous" };
}


export type AuthProvider = AnonymousAuthProvider;

export async function applyAuth(
  headers: Record<string, string>,
  auth: AuthProvider,
): Promise<void> {
  switch (auth.type) {
    case "anonymous":
      return;
    default:
      // Exhaustiveness check: only valid when the union has 2+ members. With
      // anonymous-only specs, `auth` here is still the single-member type, so
      // the `never` assertion would fail to typecheck — emit a plain no-op.
      // no other auth schemes declared by this spec
      return;
  }
}
