/* eslint-disable */
// Generated by specforge. DO NOT EDIT.

/**
 * A cached response entry: the ETag returned by the server, the parsed data,
 * and the wall-clock time the entry was stored.
 */
export interface CacheEntry {
    etag: string;
    data: unknown;
    timestamp: number;
}

/**
 * In-memory response cache keyed by full URL. Supports TTL-based expiry and
 * ETag-based conditional requests (`If-None-Match` / 304 Not Modified).
 *
 *   const cache = new ResponseCache(60_000);
 *   const cached = cache.get(url);
 *   if (cached) headers["If-None-Match"] = cached.etag;
 *   // ... on 304: return cached.data
 *   // ... on 200: cache.set(url, etag, data)
 */
export class ResponseCache {
    private cache = new Map<string, CacheEntry>();
    private ttl: number;

    constructor(ttlMs: number = 60000) {
        this.ttl = ttlMs;
    }

    /** Return the cached entry for `url` if it exists and has not expired. */
    get(url: string): CacheEntry | undefined {
        const entry = this.cache.get(url);
        if (entry && Date.now() - entry.timestamp < this.ttl) {
            return entry;
        }
        // Expired — evict.
        this.cache.delete(url);
        return undefined;
    }

    /** Store a response under `url` with its ETag and parsed data. */
    set(url: string, etag: string, data: unknown): void {
        this.cache.set(url, { etag, data, timestamp: Date.now() });
    }

    /** Remove all cached entries. */
    clear(): void {
        this.cache.clear();
    }

    /** Number of entries currently in the cache (including expired). */
    get size(): number {
        return this.cache.size;
    }
}
