/* eslint-disable */
// Generated by specforge. DO NOT EDIT.

import { ApiError, configurationError, httpError, isApiError, networkError, timeoutError } from "./errors";
import { AuthProvider, applyAuth, anonymousAuth } from "./auth";
import { DEFAULT_RETRY_OPTIONS, backoffDelay, isRetriableMethod, sleep } from "./retry";
import type { RetryOptions } from "./retry";
import { Semaphore, createSemaphore, UNLIMITED } from "./concurrency";
import { RequestDeduper } from "./dedup";
import { IDEMPOTENCY_HEADER, isIdempotencyCandidate, newIdempotencyKey } from "./idempotency";
import { Middleware, MiddlewareRequest, composeMiddleware } from "./middleware";

export interface ApiClientOptions {
  /** Override the spec's base URL. Defaults to `http://petstore.swagger.io/v1`. */
  baseUrl?: string;
  /** Auth provider. Defaults to anonymous if the spec declares no security. */
  auth?: AuthProvider;
  /** Default request timeout in ms. Default 30_000. Overridable per-call. */
  timeoutMs?: number;
  /** Retry configuration. See RetryOptions. */
  retry?: RetryOptions;
  /** Max in-flight requests. Default: unlimited. Set to bound socket usage. */
  maxConcurrent?: number;
  /** Deduplicate identical in-flight safe (GET/HEAD/OPTIONS) requests. Default true. */
  dedupe?: boolean;
  /** Auto-attach Idempotency-Key to POST/PUT/PATCH/DELETE so retries are safe. Default true. */
  idempotency?: boolean;
  /** Observability/rewrite middleware, applied in registration order. */
  middleware?: Middleware[];
  /** Inject a custom fetch (e.g. for testing or undici). Default: global fetch. */
  fetch?: typeof fetch;
  /** Extra default headers merged onto every request. */
  defaultHeaders?: Record<string, string>;
}

/**
 * Core HTTP client. SDK methods (one per operation) build requests through this.
 * Errors are thrown as typed {@link ApiError} values; narrow with `.type`.
 *
 * Concurrency: async by default; `Promise.all([...])` fans out in parallel.
 * Set `maxConcurrent` to bound the fan-out. Identical in-flight safe requests
 * are deduplicated. POST/PUT/PATCH/DELETE get auto Idempotency-Key headers so
 * retries never double-execute server-side.
 */
export class ApiClient {
  readonly baseUrl: string;
  readonly auth: AuthProvider;
  readonly timeoutMs: number;
  readonly retry: Required<RetryOptions>;
  private readonly fetchImpl: typeof fetch;
  private readonly defaultHeaders: Record<string, string>;
  private readonly semaphore: Semaphore;
  private readonly deduper: RequestDeduper;
  private readonly useDedupe: boolean;
  private readonly useIdempotency: boolean;
  private middlewares: Middleware[] = [];

  constructor(opts: ApiClientOptions = {}) {
    this.baseUrl = (opts.baseUrl ?? "http://petstore.swagger.io/v1").replace(/\/$/, "");
    this.auth = opts.auth ?? anonymousAuth();
    this.timeoutMs = opts.timeoutMs ?? 30_000;
    this.retry = { ...DEFAULT_RETRY_OPTIONS, ...opts.retry };
    this.fetchImpl = opts.fetch ?? fetch;
    this.defaultHeaders = { "content-type": "application/json", ...opts.defaultHeaders };
    if (!("accept" in this.defaultHeaders)) this.defaultHeaders["accept"] = "application/json";
    this.semaphore = opts.maxConcurrent ? createSemaphore(opts.maxConcurrent) : UNLIMITED;
    this.deduper = new RequestDeduper();
    this.useDedupe = opts.dedupe ?? true;
    this.useIdempotency = opts.idempotency ?? true;
    if (opts.middleware) for (const m of opts.middleware) this.middlewares.push(m);
  }

  /** Register an observability/rewrite middleware. Returns `this` for chaining. */
  use(middleware: Middleware): this {
    this.middlewares.push(middleware);
    return this;
  }

  /** Issue a request and return the raw Response, applying concurrency,
   *  dedup, auth, retry, timeout, idempotency, and middleware. */
  async request(
    method: string,
    path: string,
    requestOptions?: RequestOptions,
  ): Promise<Response> {
    if (typeof path !== "string" || !path.startsWith("/")) {
      throw configurationError(`path must start with "/", got ${JSON.stringify(path)}`);
    }
    const url = this.baseUrl + path + (requestOptions?.query ? "?" + encodeQuery(requestOptions.query) : "");

    // The core dispatch loop (retry-aware). Split out so dedup can memoize it.
    const dispatch = async (): Promise<Response> => {
      const release = await this.semaphore.acquire();
      try {
        return await this.dispatchWithRetry(method, url, requestOptions);
      } finally {
        release();
      }
    };

    if (this.useDedupe) {
      return this.deduper.dedupe(method, url, dispatch);
    }
    return dispatch();
  }

  /** Retry loop around a single attempt. Holds a semaphore slot while running. */
  private async dispatchWithRetry(
    method: string,
    url: string,
    requestOptions: RequestOptions | undefined,
  ): Promise<Response> {
    const maxRetries = this.retry.maxRetries;
    for (let attempt = 0; attempt <= maxRetries; attempt++) {
      // Per-attempt headers: fresh copy + auth + idempotency key on first try.
      const headers: Record<string, string> = { ...this.defaultHeaders, ...requestOptions?.headers };
      await applyAuth(headers, this.auth);
      // Attach a fresh idempotency key on the first attempt of an unsafe method.
      // (Retries reuse the server's stored result via the SAME key, so we only
      // generate one and preserve it across attempts.)
      if (attempt === 0 && this.useIdempotency && isIdempotencyCandidate(method)) {
        if (!(IDEMPOTENCY_HEADER in headers)) headers[IDEMPOTENCY_HEADER] = newIdempotencyKey();
      }

      // Compose caller's signal with our timeout signal.
      const timeoutMs = requestOptions?.timeoutMs ?? this.timeoutMs;
      const callerSignal = requestOptions?.signal;
      const ownController = "AbortController" in globalThis ? new AbortController() : undefined;
      const startedAt = Date.now();
      const timer = ownController ? setTimeout(() => ownController.abort(), timeoutMs) : undefined;
      // If the caller aborts, propagate to our controller too.
      const onCallerAbort = callerSignal ? () => ownController?.abort() : undefined;
      callerSignal?.addEventListener("abort", onCallerAbort!, { once: true });

      // Build the request descriptor for middleware.
      const mwReq: MiddlewareRequest = {
        method,
        url,
        headers,
        body: serializeBody(requestOptions),
        signal: ownController?.signal,
      };

      // Wrap fetch with the middleware chain.
      const handler = composeMiddleware(this.middlewares, (req) =>
        this.fetchImpl(req.url, {
          method: req.method,
          headers: req.headers,
          body: req.body,
          signal: req.signal,
        }),
      );

      try {
        const response = await handler(mwReq);
        if (timer) clearTimeout(timer);
        callerSignal?.removeEventListener("abort", onCallerAbort!);

        if (response.ok) return response;

        const shouldRetry =
          attempt < maxRetries &&
          isRetriableMethod(method) &&
          this.retry.retryOnStatuses.includes(response.status);
        if (shouldRetry) {
          await sleep(backoffDelay(attempt, this.retry));
          continue;
        }

        const body = await parseBody(response);
        throw httpError(response.status, body, url, response.statusText || `HTTP ${response.status}`);
      } catch (e) {
        if (timer) clearTimeout(timer);
        callerSignal?.removeEventListener("abort", onCallerAbort!);
        if (isApiError(e)) throw e;
        // Distinguish caller-cancelled from our-timeout from network.
        if (callerSignal?.aborted) throw networkError(e, "request aborted by caller");
        if (e instanceof DOMException && e.name === "AbortError") {
          throw timeoutError(Date.now() - startedAt);
        }
        if (attempt < maxRetries && isRetriableMethod(method)) {
          await sleep(backoffDelay(attempt, this.retry));
          continue;
        }
        throw networkError(e, (e as Error)?.message ?? "network error");
      }
    }
    throw configurationError("exhausted retries without a response");
  }

  /** Convenience: request + parse JSON body. Throws typed errors on !ok. */
  async requestJson<T>(method: string, path: string, requestOptions?: RequestOptions): Promise<T> {
    const response = await this.request(method, path, requestOptions);
    return (await parseBody(response)) as T;
  }
}

/** A query value. Scalars and arrays are rendered directly; objects/unknown
 *  (e.g. deepObject-style structured params) are JSON-encoded. The value type
 *  is intentionally permissive (`unknown`) because OpenAPI query params can be
 *  arbitrary structured schemas; the encoder stringifies anything non-scalar. */
export type QueryRecord = Record<string, unknown>;

export interface RequestOptions {
  query?: QueryRecord;
  headers?: Record<string, string>;
  /** JSON body (serialized automatically), or a pre-built BodyInit (FormData,
   *  Blob, etc.) for multipart uploads / raw payloads. */
  body?: unknown;
  /** Per-call timeout override in ms. */
  timeoutMs?: number;
  /** Caller-provided cancellation signal. Aborting rejects the promise. */
  signal?: AbortSignal;
}

/** URL-encode a query record, skipping undefined/null. Array values repeat the
 *  key (?k=a&k=b); scalars use a single occurrence; objects are JSON-encoded. */
export function encodeQuery(query: QueryRecord): string {
  const sp = new URLSearchParams();
  for (const [k, v] of Object.entries(query)) {
    if (v === undefined || v === null) continue;
    if (Array.isArray(v)) {
      for (const item of v) sp.append(k, encodeQueryItem(item));
    } else {
      sp.set(k, encodeQueryItem(v));
    }
  }
  return sp.toString();
}

function encodeQueryItem(v: unknown): string {
  if (typeof v === "string" || typeof v === "number" || typeof v === "boolean") return String(v);
  return JSON.stringify(v);
}

/** Serialize a request body: pass through BodyInit (FormData/Blob/string),
 *  JSON-encode plain objects, drop undefined. */
function serializeBody(requestOptions: RequestOptions | undefined): BodyInit | undefined {
  const body = requestOptions?.body;
  if (body === undefined || body === null) return undefined;
  // BodyInit covers FormData, Blob, ArrayBuffer, URLSearchParams, ReadableStream, string.
  if (typeof body === "string") return body;
  if (typeof (body as BodyInit).toString === "function" && isBodyInit(body)) return body as BodyInit;
  return JSON.stringify(body);
}

function isBodyInit(v: unknown): boolean {
  return (
    v instanceof FormData ||
    v instanceof Blob ||
    v instanceof ArrayBuffer ||
    v instanceof URLSearchParams ||
    (typeof ReadableStream !== "undefined" && v instanceof ReadableStream)
  );
}

async function parseBody(response: Response): Promise<unknown> {
  const text = await response.text();
  if (!text) return undefined;
  try {
    return JSON.parse(text);
  } catch {
    return text;
  }
}

export type { ApiError };
