/* eslint-disable */
// Generated by specforge. DO NOT EDIT.

import { ApiError, configurationError, httpError, isApiError, networkError, timeoutError } from "./errors";
import { AuthProvider, applyAuth, anonymousAuth } from "./auth";
import { DEFAULT_RETRY_OPTIONS, backoffDelay, isRetriableMethod, sleep } from "./retry";
import type { RetryOptions } from "./retry";
import { Semaphore, createSemaphore, UNLIMITED } from "./concurrency";
import { RequestDeduper } from "./dedup";
import { IDEMPOTENCY_HEADER, isIdempotencyCandidate, newIdempotencyKey } from "./idempotency";
import { Middleware, MiddlewareRequest, composeMiddleware } from "./middleware";
import { validateRequest, validateResponse, type SchemaType, type ValidationError } from "./validate";
import { ResponseCache } from "./cache";
import { type Logger, ConsoleLogger } from "./logging";
import { type RequestInterceptor, type ResponseInterceptor } from "./interceptors";

/**
 * Transform response data before it reaches the application. Transformers are
 * applied in order after response validation (when enabled) and before the
 * value is returned to the caller.
 */
export interface ResponseTransformer {
  /** Return a new value derived from `response`, or `response` unchanged. */
  transform(response: unknown): unknown;
}

export interface ApiClientOptions {
  /** Override the spec's base URL. Defaults to `http://petstore.swagger.io/v1`. */
  baseUrl?: string;
  /** Auth provider. Defaults to anonymous if the spec declares no security. */
  auth?: AuthProvider;
  /** Default request timeout in ms. Default 30_000. Overridable per-call. */
  timeoutMs?: number;
  /** Retry configuration. See RetryOptions. */
  retry?: RetryOptions;
  /** Max in-flight requests. Default: unlimited. Set to bound socket usage. */
  maxConcurrent?: number;
  /** Deduplicate identical in-flight safe (GET/HEAD/OPTIONS) requests. Default true. */
  dedupe?: boolean;
  /** Auto-attach Idempotency-Key to POST/PUT/PATCH/DELETE so retries are safe. Default true. */
  idempotency?: boolean;
  /** Observability/rewrite middleware, applied in registration order. */
  middleware?: Middleware[];
  /** Inject a custom fetch (e.g. for testing or undici). Default: global fetch. */
  fetch?: typeof fetch;
  /** Extra default headers merged onto every request. */
  defaultHeaders?: Record<string, string>;
  /** Enable runtime request/response validation against the OpenAPI schema. Default false. */
  validate?: boolean;
  /** Pre-configured ResponseCache instance. Takes precedence over `cacheTtlMs`. */
  cache?: ResponseCache;
  /** Enable GET response caching with ETag/conditional requests. Sets the TTL in ms. */
  cacheTtlMs?: number;
  /** Response transformers applied after validation, in order. */
  responseTransformers?: ResponseTransformer[];
  /** Structured logger for SDK lifecycle events (requests, retries, cache). */
  logger?: Logger;
  /** Request interceptors applied before each request body is serialized. */
  requestInterceptors?: RequestInterceptor[];
  /** Response interceptors applied after each response body is deserialized. */
  responseInterceptors?: ResponseInterceptor[];
}

/**
 * Core HTTP client. SDK methods (one per operation) build requests through this.
 * Errors are thrown as typed {@link ApiError} values; narrow with `.type`.
 *
 * Concurrency: async by default; `Promise.all([...])` fans out in parallel.
 * Set `maxConcurrent` to bound the fan-out. Identical in-flight safe requests
 * are deduplicated. POST/PUT/PATCH/DELETE get auto Idempotency-Key headers so
 * retries never double-execute server-side.
 */
export class ApiClient {
  readonly baseUrl: string;
  readonly auth: AuthProvider;
  readonly timeoutMs: number;
  readonly retry: Required<RetryOptions>;
  private readonly fetchImpl: typeof fetch;
  private readonly defaultHeaders: Record<string, string>;
  private readonly semaphore: Semaphore;
  private readonly deduper: RequestDeduper;
  private readonly useDedupe: boolean;
  private readonly useIdempotency: boolean;
  private middlewares: Middleware[] = [];
  /** When true, operations validate request/response bodies against the schema. */
  readonly validate: boolean;
  /** Optional response cache for GET requests with ETag support. */
  readonly cache?: ResponseCache;
  /** Response transformers applied after validation, in order. */
  private readonly responseTransformers: ResponseTransformer[];
  /** Structured logger for SDK lifecycle events. */
  private readonly logger: Logger;
  /** Request interceptors applied before each request body is serialized. */
  private readonly requestInterceptors: RequestInterceptor[];
  /** Response interceptors applied after each response body is deserialized. */
  private readonly responseInterceptors: ResponseInterceptor[];

  constructor(opts: ApiClientOptions = {}) {
    this.baseUrl = (opts.baseUrl ?? "http://petstore.swagger.io/v1").replace(/\/$/, "");
    this.auth = opts.auth ?? anonymousAuth();
    this.timeoutMs = opts.timeoutMs ?? 30_000;
    this.retry = { ...DEFAULT_RETRY_OPTIONS, ...opts.retry };
    this.fetchImpl = opts.fetch ?? fetch;
    this.defaultHeaders = { "content-type": "application/json", ...opts.defaultHeaders };
    if (!("accept" in this.defaultHeaders)) this.defaultHeaders["accept"] = "application/json";
    this.semaphore = opts.maxConcurrent ? createSemaphore(opts.maxConcurrent) : UNLIMITED;
    this.deduper = new RequestDeduper();
    this.useDedupe = opts.dedupe ?? true;
    this.useIdempotency = opts.idempotency ?? true;
    this.validate = opts.validate ?? false;
    this.cache = opts.cache ?? (opts.cacheTtlMs !== undefined ? new ResponseCache(opts.cacheTtlMs) : undefined);
    this.responseTransformers = opts.responseTransformers ?? [];
    this.logger = opts.logger ?? new ConsoleLogger();
    this.requestInterceptors = opts.requestInterceptors ?? [];
    this.responseInterceptors = opts.responseInterceptors ?? [];
    if (opts.middleware) for (const m of opts.middleware) this.middlewares.push(m);
  }

  /** Register an observability/rewrite middleware. Returns `this` for chaining. */
  use(middleware: Middleware): this {
    this.middlewares.push(middleware);
    return this;
  }

  /** Issue a request and return the raw Response, applying concurrency,
   *  dedup, auth, retry, timeout, idempotency, and middleware. */
  async request(
    method: string,
    path: string,
    requestOptions?: RequestOptions,
  ): Promise<Response> {
    if (typeof path !== "string" || !path.startsWith("/")) {
      throw configurationError(`path must start with "/", got ${JSON.stringify(path)}`);
    }
    const url = this.baseUrl + path + (requestOptions?.query ? "?" + encodeQuery(requestOptions.query) : "");

    // --- ETag cache: check for GET requests before dispatching ---
    const isGet = method.toUpperCase() === "GET";
    const cachedEntry = isGet && this.cache ? this.cache.get(url) : undefined;
    if (cachedEntry) {
      this.logger.debug(`[cache] HIT ${method} ${path}`);
    } else if (isGet && this.cache) {
      this.logger.debug(`[cache] MISS ${method} ${path}`);
    }
    const mergedHeaders: Record<string, string> | undefined =
      cachedEntry
        ? { ...requestOptions?.headers, "If-None-Match": cachedEntry.etag }
        : requestOptions?.headers;

    // The core dispatch loop (retry-aware). Split out so dedup can memoize it.
    const dispatch = async (): Promise<Response> => {
      const release = await this.semaphore.acquire();
      try {
        return await this.dispatchWithRetry(method, url, { ...requestOptions, headers: mergedHeaders });
      } finally {
        release();
      }
    };

    let response: Response;
    if (this.useDedupe) {
      response = await this.deduper.dedupe(method, url, dispatch);
    } else {
      response = await dispatch();
    }

    // --- ETag cache: handle 304 Not Modified and update on 200 ---
    if (isGet && this.cache) {
      if (response.status === 304 && cachedEntry) {
        // Return cached data as a synthetic Response.
        return new Response(JSON.stringify(cachedEntry.data), {
          status: 200,
          statusText: "OK (cached)",
          headers: { "content-type": "application/json", "x-cache": "HIT" },
        });
      }
      if (response.ok) {
        const etag = response.headers.get("etag");
        if (etag) {
          // Buffer the body so we can both return it and cache it.
          const cloned = response.clone();
          const body = await cloned.text();
          try {
            this.cache.set(url, etag, JSON.parse(body));
          } catch {
            // Non-JSON body — cache the raw text.
            this.cache.set(url, etag, body);
          }
        }
      }
    }

    return response;
  }

  /** Retry loop around a single attempt. Holds a semaphore slot while running. */
  private async dispatchWithRetry(
    method: string,
    url: string,
    requestOptions: RequestOptions | undefined,
  ): Promise<Response> {
    const perCallRetry = requestOptions?.retry;
    const maxRetries = perCallRetry?.maxRetries ?? this.retry.maxRetries;
    const retryable = perCallRetry?.retryable ?? isRetriableMethod(method);
    for (let attempt = 0; attempt <= maxRetries; attempt++) {
      // Per-attempt headers: fresh copy + auth + idempotency key on first try.
      const headers: Record<string, string> = { ...this.defaultHeaders, ...requestOptions?.headers };
      await applyAuth(headers, this.auth);
      // Attach a fresh idempotency key on the first attempt of an unsafe method.
      // (Retries reuse the server's stored result via the SAME key, so we only
      // generate one and preserve it across attempts.)
      if (attempt === 0 && this.useIdempotency && isIdempotencyCandidate(method)) {
        if (!(IDEMPOTENCY_HEADER in headers)) headers[IDEMPOTENCY_HEADER] = newIdempotencyKey();
      }

      // Compose caller's signal with our timeout signal.
      const timeoutMs = requestOptions?.timeoutMs ?? this.timeoutMs;
      const callerSignal = requestOptions?.signal;
      const ownController = "AbortController" in globalThis ? new AbortController() : undefined;
      const startedAt = Date.now();
      const timer = ownController ? setTimeout(() => ownController.abort(), timeoutMs) : undefined;
      // If the caller aborts, propagate to our controller too.
      const onCallerAbort = callerSignal ? () => ownController?.abort() : undefined;
      callerSignal?.addEventListener("abort", onCallerAbort!, { once: true });

      this.logger.info(`[request] ${method} ${url}${attempt > 0 ? ` (attempt ${attempt + 1})` : ""}`);

      // Build the request descriptor for middleware.
      const mwReq: MiddlewareRequest = {
        method,
        url,
        headers,
        body: serializeBody(requestOptions),
        signal: ownController?.signal,
      };

      // Wrap fetch with the middleware chain.
      const handler = composeMiddleware(this.middlewares, (req) =>
        this.fetchImpl(req.url, {
          method: req.method,
          headers: req.headers,
          body: req.body,
          signal: req.signal,
        }),
      );

      try {
        const response = await handler(mwReq);
        if (timer) clearTimeout(timer);
        callerSignal?.removeEventListener("abort", onCallerAbort!);

        if (response.ok) {
          this.logger.info(`[response] ${method} ${url} -> ${response.status}`);
          return response;
        }

        const shouldRetry =
          attempt < maxRetries &&
          retryable &&
          this.retry.retryOnStatuses.includes(response.status);
        if (shouldRetry) {
          this.logger.warn(`[retry] ${method} ${url} status=${response.status}, attempt ${attempt + 2}/${maxRetries + 1}`);
          await sleep(backoffDelay(attempt, this.retry));
          continue;
        }

        const body = await parseBody(response);
        throw httpError(response.status, body, url, response.statusText || `HTTP ${response.status}`);
      } catch (e) {
        if (timer) clearTimeout(timer);
        callerSignal?.removeEventListener("abort", onCallerAbort!);
        if (isApiError(e)) throw e;
        // Distinguish caller-cancelled from our-timeout from network.
        if (callerSignal?.aborted) throw networkError(e, "request aborted by caller");
        if (e instanceof DOMException && e.name === "AbortError") {
          throw timeoutError(Date.now() - startedAt);
        }
        if (attempt < maxRetries && retryable) {
          this.logger.warn(`[retry] ${method} ${url} error=${(e as Error)?.message}, attempt ${attempt + 2}/${maxRetries + 1}`);
          await sleep(backoffDelay(attempt, this.retry));
          continue;
        }
        throw networkError(e, (e as Error)?.message ?? "network error");
      }
    }
    throw configurationError("exhausted retries without a response");
  }

  /** Convenience: request + parse JSON body. Throws typed errors on !ok. */
  async requestJson<T>(method: string, path: string, requestOptions?: RequestOptions): Promise<T> {
    // Apply request interceptors to the body before sending.
    let body = requestOptions?.body;
    for (const interceptor of this.requestInterceptors) {
      body = interceptor.transform(body);
    }
    const interceptedOptions = requestOptions ? { ...requestOptions, body } : undefined;
    const response = await this.request(method, path, interceptedOptions);
    let result = (await parseBody(response)) as T;
    // Apply response interceptors after parsing.
    for (const interceptor of this.responseInterceptors) {
      result = interceptor.transform(result) as T;
    }
    for (const t of this.responseTransformers) {
      result = t.transform(result) as T;
    }
    return result;
  }
}

/** A query value. Scalars and arrays are rendered directly; objects/unknown
 *  (e.g. deepObject-style structured params) are JSON-encoded. The value type
 *  is intentionally permissive (`unknown`) because OpenAPI query params can be
 *  arbitrary structured schemas; the encoder stringifies anything non-scalar. */
export type QueryRecord = Record<string, unknown>;

export interface RequestOptions {
  query?: QueryRecord;
  headers?: Record<string, string>;
  /** JSON body (serialized automatically), or a pre-built BodyInit (FormData,
   *  Blob, etc.) for multipart uploads / raw payloads. */
  body?: unknown;
  /** Per-call timeout override in ms. */
  timeoutMs?: number;
  /** Caller-provided cancellation signal. Aborting rejects the promise. */
  signal?: AbortSignal;
  retry?: { maxRetries?: number; retryable?: boolean };
}

/** URL-encode a query record, skipping undefined/null. Array values repeat the
 *  key (?k=a&k=b); scalars use a single occurrence; objects are JSON-encoded. */
export function encodeQuery(query: QueryRecord): string {
  const sp = new URLSearchParams();
  for (const [k, v] of Object.entries(query)) {
    if (v === undefined || v === null) continue;
    if (Array.isArray(v)) {
      for (const item of v) sp.append(k, encodeQueryItem(item));
    } else {
      sp.set(k, encodeQueryItem(v));
    }
  }
  return sp.toString();
}

function encodeQueryItem(v: unknown): string {
  if (typeof v === "string" || typeof v === "number" || typeof v === "boolean") return String(v);
  return JSON.stringify(v);
}

/** Serialize a request body: pass through BodyInit (FormData/Blob/string),
 *  JSON-encode plain objects, drop undefined. */
function serializeBody(requestOptions: RequestOptions | undefined): BodyInit | undefined {
  const body = requestOptions?.body;
  if (body === undefined || body === null) return undefined;
  // BodyInit covers FormData, Blob, ArrayBuffer, URLSearchParams, ReadableStream, string.
  if (typeof body === "string") return body;
  if (typeof (body as BodyInit).toString === "function" && isBodyInit(body)) return body as BodyInit;
  return JSON.stringify(body);
}

function isBodyInit(v: unknown): boolean {
  return (
    v instanceof FormData ||
    v instanceof Blob ||
    v instanceof ArrayBuffer ||
    v instanceof URLSearchParams ||
    (typeof ReadableStream !== "undefined" && v instanceof ReadableStream)
  );
}

async function parseBody(response: Response): Promise<unknown> {
  const text = await response.text();
  if (!text) return undefined;
  try {
    return JSON.parse(text);
  } catch {
    return text;
  }
}

export type { ApiError };
