/* eslint-disable */
// Generated by specforge. DO NOT EDIT.

/**
 * A minimal async semaphore for bounding concurrent requests. FIFO, resolved on
 * the microtask queue (no timers), works in browsers/Node/workers/edge.
 *
 *   const sem = createSemaphore(5);
 *   const release = await sem.acquire();
 *   try { // do request
 *   } finally { release(); }
 */
export interface Semaphore {
  /** Block until a slot is free; return a function that releases the slot. */
  acquire(): Promise<() => void>;
  /** Number of currently-held slots. */
  readonly active: number;
  /** Number of waiters. */
  readonly waiting: number;
}

export function createSemaphore(max: number): Semaphore {
  if (!Number.isFinite(max) || max <= 0) {
    throw new RangeError(`maxConcurrent must be a positive finite number, got ${max}`);
  }
  let active = 0;
  const waiters: Array<() => void> = [];

  const release = () => {
    if (active === 0) return;
    active--;
    while (active < max && waiters.length > 0) {
      const resolve = waiters.shift()!;
      active++;
      resolve();
    }
  };

  return {
    acquire: () =>
      new Promise<() => void>((resolve) => {
        if (active < max) {
          active++;
          resolve(release);
          return;
        }
        waiters.push(() => resolve(release));
      }),
    get active() {
      return active;
    },
    get waiting() {
      return waiters.length;
    },
  };
}

/** A semaphore that never blocks — used when `maxConcurrent` is unset. */
export const UNLIMITED: Semaphore = {
  acquire: async () => () => {},
  get active() {
    return 0;
  },
  get waiting() {
    return 0;
  },
};
