/* eslint-disable */
// Generated by specforge. DO NOT EDIT.

/**
 * In-flight request deduplication. When two callers issue the same safe
 * (GET/HEAD) request before the first settles, they share one fetch promise.
 * Unsafe methods are never deduped — they always execute independently.
 */
type BufferedResponse = {
  status: number;
  statusText: string;
  headers: Headers;
  body: ArrayBuffer;
};

export class RequestDeduper {
  private readonly inFlight = new Map<string, Promise<BufferedResponse>>();

  /** If a matching safe request is in flight, return its promise; otherwise
   *  run `run()` and cache it until it settles.
   *
   *  The body is buffered once and each waiter receives a fresh `Response`
   *  built from that buffer (a single fetch body can only be consumed once). */
  dedupe(method: string, url: string, run: () => Promise<Response>): Promise<Response> {
    if (!isSafeMethod(method)) return run();
    const key = `${method} ${url}`;
    let shared = this.inFlight.get(key);
    if (!shared) {
      shared = run()
        .then(async (res) => ({
          status: res.status,
          statusText: res.statusText,
          headers: res.headers,
          body: await res.arrayBuffer(),
        }))
        .finally(() => this.inFlight.delete(key));
      this.inFlight.set(key, shared);
    }
    return shared.then(
      (parts) =>
        new Response(parts.body.slice(0), {
          status: parts.status,
          statusText: parts.statusText,
          headers: parts.headers,
        }),
    );
  }

  get size(): number {
    return this.inFlight.size;
  }
}

export function isSafeMethod(method: string): boolean {
  const m = method.toUpperCase();
  return m === "GET" || m === "HEAD" || m === "OPTIONS";
}
