/* eslint-disable */
// Generated by specforge. DO NOT EDIT.

/**
 * Typed SDK errors, modeled as a discriminated union on the `type` field.
 * Narrow with a switch on `.type` for exhaustive handling.
 *
 *   try { await client.pets.listPets() }
 *   catch (e) {
 *     const err = e as ApiError;
 *     switch (err.type) {
 *       case "http":      ... break;
 *       case "network":   ... break;
 *       case "timeout":   ... break;
 *       default: const _: never = err; // exhaustiveness check
 *     }
 *   }
 */
export type ApiError =
  | HttpError
  | NetworkError
  | TimeoutError
  | ConfigurationError;

export interface HttpError {
  /** Discriminant. Always "http". */
  type: "http";
  /** HTTP status code returned by the server. */
  status: number;
  /** Raw response body (parsed JSON if possible, otherwise text). */
  body: unknown;
  /** The request URL that failed. */
  url: string;
  /** Human-readable status text, e.g. "Not Found". */
  message: string;
}

export interface NetworkError {
  /** Discriminant. Always "network". */
  type: "network";
  /** The underlying fetch error. */
  cause: unknown;
  message: string;
}

export interface TimeoutError {
  /** Discriminant. Always "timeout". */
  type: "timeout";
  /** Elapsed milliseconds before the request was aborted. */
  elapsedMs: number;
  message: string;
}

export interface ConfigurationError {
  /** Discriminant. Always "configuration". */
  type: "configuration";
  message: string;
}

/** True if `e` is one of our typed errors. */
export function isApiError(e: unknown): e is ApiError {
  return (
    typeof e === "object" &&
    e !== null &&
    "type" in e &&
    typeof (e as { type: unknown }).type === "string" &&
    ["http", "network", "timeout", "configuration"].includes(
      (e as { type: string }).type,
    )
  );
}

export function httpError(
  status: number,
  body: unknown,
  url: string,
  message: string,
): HttpError {
  return { type: "http", status, body, url, message };
}

export function networkError(cause: unknown, message: string): NetworkError {
  return { type: "network", cause, message };
}

export function timeoutError(elapsedMs: number): TimeoutError {
  return { type: "timeout", elapsedMs, message: `Request timed out after ${elapsedMs}ms` };
}

export function configurationError(message: string): ConfigurationError {
  return { type: "configuration", message };
}
