/* eslint-disable */
// Generated by specforge. DO NOT EDIT.

/**
 * Idempotency key generation and header handling. Pairing unsafe-method
 * requests (POST/PUT/PATCH) with a unique Idempotency-Key makes retries safe:
 * if the same key reaches the server twice, it returns the original result
 * instead of executing twice.
 */
export const IDEMPOTENCY_HEADER = "Idempotency-Key";

/** True for methods where an idempotency key adds safety (per the spec's retry). */
export function isIdempotencyCandidate(method: string): boolean {
  const m = method.toUpperCase();
  return m === "POST" || m === "PUT" || m === "PATCH" || m === "DELETE";
}

/**
 * Generate a fresh idempotency key. Uses crypto.randomUUID when available
 * (browsers, Node 19+, edge), falling back to a crypto.getRandomValues-based
 * RFC-4122 v4 key.
 */
export function newIdempotencyKey(): string {
  const g = globalThis as { crypto?: Crypto };
  if (g.crypto?.randomUUID) return g.crypto.randomUUID();
  if (g.crypto?.getRandomValues) {
    const bytes = new Uint8Array(16);
    g.crypto.getRandomValues(bytes);
    bytes[6] = (bytes[6]! & 0x0f) | 0x40;
    bytes[8] = (bytes[8]! & 0x3f) | 0x80;
    const h = [...bytes].map((b) => b.toString(16).padStart(2, "0"));
    return `${h.slice(0, 4).join("")}-${h.slice(4, 6).join("")}-${h.slice(6, 8).join("")}-${h.slice(8, 10).join("")}-${h.slice(10, 16).join("")}`;
  }
  // Last-resort fallback (non-crypto). Adequate for collision avoidance only.
  return `key-${Date.now()}-${Math.random().toString(36).slice(2)}`;
}
