/* eslint-disable */
// Generated by specforge. DO NOT EDIT.

/**
 * Request interceptor: transform the request body before it is serialized
 * and sent. Return the (possibly modified) body.
 */
export interface RequestInterceptor {
  /** Transform the request body. Return the modified body. */
  transform(body: unknown): unknown;
}

/**
 * Response interceptor: transform the response body after it is deserialized.
 * Return the (possibly modified) body.
 */
export interface ResponseInterceptor {
  /** Transform the response body. Return the modified body. */
  transform(body: unknown): unknown;
}
