/* eslint-disable */
// Generated by specforge. DO NOT EDIT.

/**
 * Structured logging interface. Implement this to plug in your own logger.
 * All methods receive a message string and optional structured context.
 */
export interface Logger {
  debug(message: string, ...args: unknown[]): void;
  info(message: string, ...args: unknown[]): void;
  warn(message: string, ...args: unknown[]): void;
  error(message: string, ...args: unknown[]): void;
}

/**
 * Default logger that delegates to console.debug/info/warn/error.
 */
export class ConsoleLogger implements Logger {
  debug(message: string, ...args: unknown[]): void {
    console.debug(message, ...args);
  }
  info(message: string, ...args: unknown[]): void {
    console.info(message, ...args);
  }
  warn(message: string, ...args: unknown[]): void {
    console.warn(message, ...args);
  }
  error(message: string, ...args: unknown[]): void {
    console.error(message, ...args);
  }
}

/** A no-op logger that discards all messages. */
export const NoopLogger: Logger = {
  debug() {},
  info() {},
  warn() {},
  error() {},
};
