/* eslint-disable */
// Generated by specforge. DO NOT EDIT.

/**
 * Middleware: observe or rewrite requests and responses. Registered in order;
 * each middleware wraps the next. Throw from a middleware to fail the request.
 *
 *   client.use(async (req, next) => {
 *     const start = Date.now();
 *     const res = await next(req);
 *     console.log(req.method, req.url, res.status, Date.now() - start, "ms");
 *     return res;
 *   });
 */
export interface MiddlewareRequest {
  method: string;
  url: string;
  headers: Record<string, string>;
  body?: BodyInit;
  signal?: AbortSignal;
}

export interface Middleware {
  (req: MiddlewareRequest, next: (req: MiddlewareRequest) => Promise<Response>): Promise<Response>;
}

/** Compose middlewares into a single handler around a terminal `dispatch`. */
export function composeMiddleware(
  middlewares: Middleware[],
  dispatch: (req: MiddlewareRequest) => Promise<Response>,
): (req: MiddlewareRequest) => Promise<Response> {
  // Apply in reverse so the first registered middleware runs outermost.
  let handler = dispatch;
  for (let i = middlewares.length - 1; i >= 0; i--) {
    const mw = middlewares[i]!;
    const next = handler;
    handler = (req) => mw(req, next);
  }
  return handler;
}
