/* eslint-disable */
// Generated by specforge. DO NOT EDIT.

/**
 * Pagination helpers. Use `cursorPaginator` when a list endpoint returns
 * `{ items, nextCursor }`; use `offsetPaginator` for `?offset=&limit=` APIs.
 *
 *   for await (const page of cursorPaginator((cursor) => client.pets.listPets({ cursor }))) {
 *     for (const pet of page.items) { ... }
 *   }
 */
export interface CursorPage<T> {
  items: T[];
  nextCursor: string | null;
}

export async function* cursorPaginator<T>(
  fetchPage: (cursor: string | undefined) => Promise<CursorPage<T>>,
): AsyncGenerator<CursorPage<T>> {
  let cursor: string | undefined = undefined;
  while (true) {
    const page = await fetchPage(cursor);
    yield page;
    if (!page.nextCursor) return;
    cursor = page.nextCursor;
  }
}

export interface OffsetPage<T> {
  items: T[];
  total?: number;
}

export async function* offsetPaginator<T>(
  fetchPage: (offset: number, limit: number) => Promise<OffsetPage<T>>,
  opts: { limit?: number } = {},
): AsyncGenerator<OffsetPage<T>> {
  const limit = opts.limit ?? 50;
  let offset = 0;
  while (true) {
    const page = await fetchPage(offset, limit);
    yield page;
    if (page.items.length < limit) return;
    offset += page.items.length;
  }
}
