/* eslint-disable */
// Generated by specforge. DO NOT EDIT.

/**
 * Rate limiter interface. The client calls `acquire()` before each request;
 * the returned promise resolves when the request is allowed to proceed.
 */
export interface RateLimiter {
  /** Block until the request is allowed. Reject to abort. */
  acquire(): Promise<void>;
}

/**
 * Token bucket rate limiter. Tokens refill at a constant rate up to a maximum.
 * Each request consumes one token; when empty, `acquire()` waits for a refill.
 */
export class TokenBucket implements RateLimiter {
  private tokens: number;
  private readonly maxTokens: number;
  private readonly refillRate: number; // tokens per second
  private lastRefill: number;

  constructor(maxTokens: number, refillRate: number) {
    this.maxTokens = maxTokens;
    this.tokens = maxTokens;
    this.refillRate = refillRate;
    this.lastRefill = Date.now();
  }

  async acquire(): Promise<void> {
    this.refill();
    while (this.tokens < 1) {
      // Wait for the next refill.
      const waitMs = Math.ceil((1 - this.tokens) / this.refillRate * 1000);
      await new Promise((resolve) => setTimeout(resolve, Math.max(waitMs, 10)));
      this.refill();
    }
    this.tokens -= 1;
  }

  private refill(): void {
    const now = Date.now();
    const elapsed = (now - this.lastRefill) / 1000;
    this.tokens = Math.min(this.maxTokens, this.tokens + elapsed * this.refillRate);
    this.lastRefill = now;
  }
}

/**
 * Sliding window rate limiter. Allows at most `maxRequests` within any rolling
 * `windowMs`. When the limit is reached, `acquire()` waits until the oldest
 * request in the window expires.
 */
export class SlidingWindow implements RateLimiter {
  private readonly requests: number[] = [];
  private readonly maxRequests: number;
  private readonly windowMs: number;

  constructor(maxRequests: number, windowMs: number) {
    this.maxRequests = maxRequests;
    this.windowMs = windowMs;
  }

  async acquire(): Promise<void> {
    this.evict();
    if (this.requests.length >= this.maxRequests) {
      const oldest = this.requests[0]!;
      const waitMs = this.windowMs - (Date.now() - oldest);
      if (waitMs > 0) {
        await new Promise((resolve) => setTimeout(resolve, waitMs));
      }
      this.evict();
    }
    this.requests.push(Date.now());
  }

  private evict(): void {
    const cutoff = Date.now() - this.windowMs;
    while (this.requests.length > 0 && this.requests[0]! <= cutoff) {
      this.requests.shift();
    }
  }
}
