/* eslint-disable */
// Generated by specforge. DO NOT EDIT.

export interface RetryOptions {
  /** Max retry attempts after the initial request. Default 2. */
  maxRetries?: number;
  /** Base delay in ms; actual delay = random(0, baseDelay * 2^attempt). Default 500. */
  baseDelayMs?: number;
  /** Cap on per-attempt delay. Default 8_000. */
  maxDelayMs?: number;
  /** Override which HTTP statuses are retried. Default [408, 429, 502, 503, 504]. */
  retryOnStatuses?: number[];
}

export const DEFAULT_RETRY_OPTIONS: Required<RetryOptions> = {
  maxRetries: 2,
  baseDelayMs: 500,
  maxDelayMs: 8_000,
  retryOnStatuses: [408, 429, 502, 503, 504],
};

/** Sleep for `ms` milliseconds. Uses setTimeout so it works in any runtime. */
export function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

/** Compute a full-jitter backoff delay (see AWS Architecture Blog: Exponential Backoff). */
export function backoffDelay(attempt: number, opts: Required<RetryOptions>): number {
  const ceiling = Math.min(opts.baseDelayMs * 2 ** attempt, opts.maxDelayMs);
  return Math.floor(Math.random() * ceiling);
}

/** True if a request method is safe to retry by default. */
export function isRetriableMethod(method: string): boolean {
  const m = method.toUpperCase();
  return m === "GET" || m === "HEAD" || m === "PUT" || m === "DELETE";
}
