/* eslint-disable */
// Generated by specforge. DO NOT EDIT.

import type { ResponseCache } from "./cache";
import type { RateLimiter } from "./ratelimit";
import type { Logger } from "./logging";
import type { TelemetryHooks } from "./telemetry";

/**
 * Typed service container grouping all injectable SDK dependencies.
 * Use `createContainer()` to build one; pass it to `ApiClientOptions.container`
 * to apply all services at once.
 *
 * Every field is optional: unspecified services use the SDK defaults
 * (global fetch, no cache, no rate limiter, console logger, no telemetry).
 *
 * @example
 * ```ts
 * const container = createContainer({
 *   httpClient: myCustomFetch,
 *   logger: new ConsoleLogger(),
 *   rateLimiter: new TokenBucket(10, 5),
 * });
 * const client = new ApiClient({ container });
 * ```
 */
export interface ServiceContainer {
  /** Custom fetch implementation (e.g. for testing, undici, or cloud workers). */
  httpClient?: typeof fetch;
  /** Pre-configured response cache for GET requests with ETag support. */
  cache?: ResponseCache;
  /** Rate limiter applied before each request. */
  rateLimiter?: RateLimiter;
  /** Structured logger for SDK lifecycle events. */
  logger?: Logger;
  /** Telemetry hooks for request lifecycle observability. */
  telemetry?: TelemetryHooks;
}

/**
 * Create a typed service container. All fields default to `undefined`
 * (the SDK applies its own defaults for unspecified services).
 */
export function createContainer(opts: ServiceContainer = {}): ServiceContainer {
  return { ...opts };
}
