/* eslint-disable */
// Generated by specforge. DO NOT EDIT.

/**
 * Streaming helpers for endpoints that return `text/event-stream` or chunked
 * bodies. Consume as async iterators:
 *
 *   const res = await client.request("GET", "/events");
 *   for await (const chunk of streamBytes(res)) { ... }            // raw bytes
 *   for await (const event of streamSse(res)) { ... }              // parsed SSE
 */

/** Iterate over raw Uint8Array chunks of a streaming Response body. */
export async function* streamBytes(response: Response): AsyncGenerator<Uint8Array> {
  if (!response.body) throw new Error("response has no streaming body");
  const reader = response.body.getReader();
  try {
    while (true) {
      const { done, value } = await reader.read();
      if (done) return;
      if (value) yield value;
    }
  } finally {
    reader.releaseLock();
  }
}

/** Iterate over decoded text lines of a streaming Response body. */
export async function* streamLines(response: Response): AsyncGenerator<string> {
  const decoder = new TextDecoder();
  let buffer = "";
  for await (const chunk of streamBytes(response)) {
    buffer += decoder.decode(chunk, { stream: true });
    let nl: number;
    while ((nl = buffer.indexOf("\n")) >= 0) {
      const line = buffer.slice(0, nl).replace(/\r$/, "");
      buffer = buffer.slice(nl + 1);
      yield line;
    }
  }
  buffer += decoder.decode();
  if (buffer.length > 0) yield buffer;
}

export interface ServerSentEvent {
  /** The `event:` field, or "message" if absent. */
  event: string;
  /** The `data:` fields joined by newlines. */
  data: string;
  /** The `id:` field if present. */
  id?: string;
}

/**
 * Parse a Server-Sent Events stream. Handles `event:`, `data:`, `id:`, and
 * `retry:` fields, multi-line `data:`, and dispatches on blank-line separators.
 */
export async function* streamSse(response: Response): AsyncGenerator<ServerSentEvent> {
  let event = "message";
  let data: string[] = [];
  let id: string | undefined;
  for await (const line of streamLines(response)) {
    if (line === "") {
      if (data.length > 0 || event !== "message") {
        yield { event, data: data.join("\n"), id };
      }
      event = "message";
      data = [];
      id = undefined;
      continue;
    }
    if (line.startsWith(":")) continue; // comment
    const colon = line.indexOf(":");
    const field = colon >= 0 ? line.slice(0, colon) : line;
    const value = colon >= 0 ? line.slice(colon + 1).replace(/^ /, "") : "";
    switch (field) {
      case "event":
        event = value;
        break;
      case "data":
        data.push(value);
        break;
      case "id":
        id = value;
        break;
      case "retry":
        // Intentionally ignored; retry interval is handled by the caller.
        break;
    }
  }
}
