/* eslint-disable */
// Generated by specforge. DO NOT EDIT.

/**
 * Telemetry hooks for observing the SDK request lifecycle.
 * Implement any subset; unused hooks are simply not called.
 */
export interface TelemetryHooks {
  /** Called just before the request is dispatched. */
  onRequestStart?(method: string, path: string): void;
  /** Called after a successful response (2xx) with the elapsed duration. */
  onRequestEnd?(method: string, path: string, durationMs: number, status: number): void;
  /** Called when a request fails (network, timeout, non-retriable HTTP error). */
  onRequestError?(method: string, path: string, durationMs: number, error: unknown): void;
  /** Called before a retry attempt (after backoff sleep). */
  onRetry?(method: string, path: string, attempt: number, error: unknown): void;
  /** Called when a GET request is served from the response cache. */
  onCacheHit?(method: string, path: string): void;
  /** Called when a GET request misses the cache and goes to the network. */
  onCacheMiss?(method: string, path: string): void;
}

/**
 * Built-in metrics collector that tracks request counts, errors, durations,
 * and retries. Use `getMetrics()` to obtain a snapshot.
 */
export class MetricsCollector implements TelemetryHooks {
  private requestCount = 0;
  private errorCount = 0;
  private totalDurationMs = 0;
  private retryCount = 0;

  onRequestStart(_method: string, _path: string): void {
    this.requestCount++;
  }

  onRequestEnd(_method: string, _path: string, durationMs: number, status: number): void {
    this.totalDurationMs += durationMs;
    if (status >= 400) this.errorCount++;
  }

  onRequestError(_method: string, _path: string, durationMs: number, _error: unknown): void {
    this.errorCount++;
    this.totalDurationMs += durationMs;
  }

  onRetry(_method: string, _path: string, _attempt: number, _error: unknown): void {
    this.retryCount++;
  }

  /** Return a snapshot of the collected metrics. */
  getMetrics(): Metrics {
    return {
      requestCount: this.requestCount,
      errorCount: this.errorCount,
      totalDurationMs: this.totalDurationMs,
      avgDurationMs: this.requestCount > 0 ? this.totalDurationMs / this.requestCount : 0,
      retryCount: this.retryCount,
    };
  }
}

export interface Metrics {
  requestCount: number;
  errorCount: number;
  totalDurationMs: number;
  avgDurationMs: number;
  retryCount: number;
}
