/* eslint-disable */
// Generated by specforge. DO NOT EDIT.

// ─── Schema descriptor types ────────────────────────────────────────────────

export type SchemaField = { type: SchemaType; required: boolean };
export type SchemaObject = { kind: "object"; fields: Record<string, SchemaField> };
export type SchemaRef = { kind: "ref"; name: string };
export type SchemaString = { kind: "string" };
export type SchemaNumber = { kind: "number" };
export type SchemaBoolean = { kind: "boolean" };
export type SchemaEnum = { kind: "enum"; values: readonly string[] };
export type SchemaArray = { kind: "array"; items: SchemaType };
export type SchemaType =
  | SchemaString
  | SchemaNumber
  | SchemaBoolean
  | SchemaEnum
  | SchemaArray
  | SchemaRef
  | SchemaObject;

// ─── Validation result ──────────────────────────────────────────────────────

export interface ValidationError {
  path: string;
  message: string;
}

// ─── Per-model validators ───────────────────────────────────────────────────

export const ErrorSchema: SchemaObject = {
  kind: "object",
  fields: {
    "code": { type: { kind: "number" }, required: true },
    "message": { type: { kind: "string" }, required: true },
  },
};

export function validateError(value: unknown, path = ""): ValidationError[] {
  const errors: ValidationError[] = [];
  validateValue(value, ErrorSchema, path, errors);
  return errors;
}

export const PetSchema: SchemaObject = {
  kind: "object",
  fields: {
    "id": { type: { kind: "number" }, required: true },
    "name": { type: { kind: "string" }, required: true },
    "tag": { type: { kind: "string" }, required: false },
  },
};

export function validatePet(value: unknown, path = ""): ValidationError[] {
  const errors: ValidationError[] = [];
  validateValue(value, PetSchema, path, errors);
  return errors;
}

export const PetsSchema: SchemaObject = {
  kind: "object",
  fields: {
  },
};

export function validatePets(value: unknown, path = ""): ValidationError[] {
  const errors: ValidationError[] = [];
  validateValue(value, PetsSchema, path, errors);
  return errors;
}


// ─── Generic validation runtime ─────────────────────────────────────────────

function validateString(value: unknown, path: string, errors: ValidationError[]): void {
  if (typeof value !== "string") {
    errors.push({ path, message: `expected string, got ${typeof value}` });
  }
}

function validateNumber(value: unknown, path: string, errors: ValidationError[]): void {
  if (typeof value !== "number") {
    errors.push({ path, message: `expected number, got ${typeof value}` });
  }
}

function validateBoolean(value: unknown, path: string, errors: ValidationError[]): void {
  if (typeof value !== "boolean") {
    errors.push({ path, message: `expected boolean, got ${typeof value}` });
  }
}

function validateEnum(value: unknown, values: readonly string[], path: string, errors: ValidationError[]): void {
  if (typeof value !== "string") {
    errors.push({ path, message: `expected string, got ${typeof value}` });
    return;
  }
  if (!(values as string[]).includes(value)) {
    errors.push({ path, message: `expected one of [${values.join(", ")}], got "${value}"` });
  }
}

function validateArray(value: unknown, itemSchema: SchemaType, path: string, errors: ValidationError[]): void {
  if (!Array.isArray(value)) {
    errors.push({ path, message: `expected array, got ${typeof value}` });
    return;
  }
  for (let i = 0; i < value.length; i++) {
    validateValue(value[i], itemSchema, `${path}[${i}]`, errors);
  }
}

function validateObject(value: unknown, schema: SchemaObject, path: string, errors: ValidationError[]): void {
  if (typeof value !== "object" || value === null || Array.isArray(value)) {
    errors.push({ path, message: `expected object, got ${value === null ? "null" : typeof value}` });
    return;
  }
  const obj = value as Record<string, unknown>;
  for (const [key, field] of Object.entries(schema.fields)) {
    const fieldPath = path ? `${path}.${key}` : key;
    if (obj[key] === undefined) {
      if (field.required) {
        errors.push({ path: fieldPath, message: "missing required field" });
      }
      continue;
    }
    validateValue(obj[key], field.type, fieldPath, errors);
  }
}

/** Resolve a SchemaType, following refs to the models map. */
function resolveSchema(schema: SchemaType, models: Record<string, SchemaObject>): SchemaObject | null {
  if (schema.kind === "object") return schema;
  if (schema.kind === "ref") return models[schema.name] ?? null;
  return null;
}

/**
 * Generic validation: dispatch on the schema kind to check the value.
 * Accumulates errors into the provided array. Used by per-model validators
 * and by validateRequest / validateResponse.
 */
export function validateValue(
  value: unknown,
  schema: SchemaType,
  path: string,
  errors: ValidationError[],
): void {
  if (value === undefined || value === null) return;

  switch (schema.kind) {
    case "string":
      validateString(value, path, errors);
      break;
    case "number":
      validateNumber(value, path, errors);
      break;
    case "boolean":
      validateBoolean(value, path, errors);
      break;
    case "enum":
      validateEnum(value, schema.values, path, errors);
      break;
    case "array":
      validateArray(value, schema.items, path, errors);
      break;
    case "object":
      validateObject(value, schema, path, errors);
      break;
    case "ref":
      // Refs are resolved at the call site; this path shouldn't normally be hit
      // from validateValue since callers resolve refs first.
      break;
  }
}

// ─── Request / Response validation ──────────────────────────────────────────

/**
 * Validate a request body against a schema. Returns an empty array when valid.
 * Call with the method, path, body, and a SchemaType descriptor.
 */
export function validateRequest(
  method: string,
  path: string,
  body: unknown,
  schema: SchemaType | undefined,
): ValidationError[] {
  if (!schema || body === undefined || body === null) return [];
  const errors: ValidationError[] = [];
  validateValue(body, schema, "body", errors);
  if (errors.length > 0) {
    const err = new Error(
      `[validate] ${method} ${path} request body: ${errors.map((e) => `${e.path}: ${e.message}`).join("; ")}`,
    );
    (err as any).validationErrors = errors;
    throw err;
  }
  return errors;
}

/**
 * Validate a response body against a schema. Returns an empty array when valid.
 * Call with the method, path, status, body, and a SchemaType descriptor.
 */
export function validateResponse(
  method: string,
  path: string,
  status: number,
  body: unknown,
  schema: SchemaType | undefined,
): ValidationError[] {
  if (!schema || body === undefined || body === null) return [];
  const errors: ValidationError[] = [];
  validateValue(body, schema, "body", errors);
  if (errors.length > 0) {
    const err = new Error(
      `[validate] ${method} ${path} response ${status}: ${errors.map((e) => `${e.path}: ${e.message}`).join("; ")}`,
    );
    (err as any).validationErrors = errors;
    throw err;
  }
  return errors;
}
