/* eslint-disable */
// Generated by specforge. DO NOT EDIT.

import { Middleware, MiddlewareRequest } from "./middleware";
import { SchemaType, ValidationError, validateValue } from "./validate";

/**
 * Schema descriptor for an endpoint's request and/or response body.
 */
export interface EndpointSchema {
  /** Schema for the request body. Undefined means no request body validation. */
  requestBody?: SchemaType;
  /** Schema for the response body. Undefined means no response body validation. */
  responseBody?: SchemaType;
}

/**
 * A route schema map keyed by "METHOD /path/pattern".
 * Patterns use `{param}` placeholders for path segments.
 */
export interface RouteSchemaMap {
  [route: string]: EndpointSchema;
}

/**
 * Validate that `actualPath` matches the `pattern` path.
 * Pattern segments wrapped in `{...}` are treated as wildcards.
 * Returns true when every segment matches (exact or wildcard).
 */
function matchesPath(pattern: string, actualPath: string): boolean {
  const patternSegments = pattern.split("/").filter(Boolean);
  const actualSegments = actualPath.split("/").filter(Boolean);
  if (patternSegments.length !== actualSegments.length) return false;
  for (let i = 0; i < patternSegments.length; i++) {
    const ps = patternSegments[i]!;
    if (ps.startsWith("{") && ps.endsWith("}")) continue; // wildcard
    if (ps !== actualSegments[i]) return false;
  }
  return true;
}

/**
 * Create a validation middleware that intercepts all requests and validates
 * request/response bodies against the OpenAPI schema.
 *
 * Usage:
 * ```ts
 * import { createValidationMiddleware, RouteSchemaMap } from "./validation-middleware";
 *
 * const schemas: RouteSchemaMap = {
 *   "POST /pets": { requestBody: PetSchema, responseBody: PetSchema },
 *   "GET /pets/{petId}": { responseBody: PetSchema },
 * };
 *
 * client.use(createValidationMiddleware(schemas));
 * ```
 *
 * The middleware validates request bodies before dispatch and response bodies
 * after a successful response. Validation errors are thrown as Error objects
 * with a `validationErrors` property containing the details.
 */
export function createValidationMiddleware(schemas: RouteSchemaMap): Middleware {
  return async (req: MiddlewareRequest, next: (req: MiddlewareRequest) => Promise<Response>): Promise<Response> => {
    const method = req.method.toUpperCase();
    // Strip query string for route matching.
    const path = req.url.split("?")[0] || "";

    // Find a matching route schema.
    const routeKey = `${method} ${path}`;
    let endpointSchema = schemas[routeKey];

    // Try pattern matching if exact match fails.
    if (!endpointSchema) {
      for (const [pattern, schema] of Object.entries(schemas)) {
        const spaceIdx = pattern.indexOf(" ");
        if (spaceIdx < 0) continue;
        const patternMethod = pattern.substring(0, spaceIdx).toUpperCase();
        const patternPath = pattern.substring(spaceIdx + 1);
        if (patternMethod === method && matchesPath(patternPath, path)) {
          endpointSchema = schema;
          break;
        }
      }
    }

    // Validate request body if a schema is defined.
    if (endpointSchema?.requestBody && req.body !== undefined && req.body !== null) {
      let body: unknown;
      if (typeof req.body === "string") {
        try { body = JSON.parse(req.body); } catch { body = req.body; }
      } else if (
        typeof ReadableStream !== "undefined" && req.body instanceof ReadableStream ||
        typeof Blob !== "undefined" && req.body instanceof Blob ||
        typeof ArrayBuffer !== "undefined" && req.body instanceof ArrayBuffer ||
        typeof FormData !== "undefined" && req.body instanceof FormData
      ) {
        // Cannot validate non-JSON body types; skip.
      } else {
        body = req.body;
      }
      if (body !== undefined && body !== null && typeof body !== "string") {
        const errors: ValidationError[] = [];
        validateValue(body, endpointSchema.requestBody, "body", errors);
        if (errors.length > 0) {
          const err = new Error(
            `[validation] ${method} ${path} request body: ${errors.map((e) => `${e.path}: ${e.message}`).join("; ")}`,
          );
          (err as any).validationErrors = errors;
          throw err;
        }
      }
    }

    // Proceed with the request.
    const response = await next(req);

    // Validate response body if a schema is defined and the response is JSON.
    if (endpointSchema?.responseBody && response.ok) {
      const contentType = response.headers.get("content-type") || "";
      if (contentType.includes("application/json")) {
        const cloned = response.clone();
        try {
          const text = await cloned.text();
          if (text) {
            const body = JSON.parse(text);
            const errors: ValidationError[] = [];
            validateValue(body, endpointSchema.responseBody, "body", errors);
            if (errors.length > 0) {
              const err = new Error(
                `[validation] ${method} ${path} response ${response.status}: ${errors.map((e) => `${e.path}: ${e.message}`).join("; ")}`,
              );
              (err as any).validationErrors = errors;
              throw err;
            }
          }
        } catch (e) {
          if ((e as any).validationErrors) throw e;
          // Non-JSON or parse error -- skip response validation.
        }
      }
    }

    return response;
  };
}
