// Code generated by specforge. DO NOT EDIT.

use crate::client::Client;
use crate::error::Result;
use crate::models::*;

/// List all pets
pub async fn list_pets(client: &Client, limit: Option<i32>) -> Result<Pets> {
    let path = "/pets".to_string();
    let mut query: Vec<(&str, String)> = Vec::new();
    if let Some(ref v) = limit {
        query.push(("limit", v.to_string()));
    }
    client.request_json::<Pets, _>(reqwest::Method::GET, &path, &query, None::<&()>).await
}

/// Create a pet
pub async fn create_pets(client: &Client) -> Result<()> {
    let path = "/pets".to_string();
    let query: Vec<(&str, String)> = Vec::new();
    let _: () = client
        .request_json::<(), _>(reqwest::Method::POST, &path, &query, None::<&()>)
        .await
        .or_else(|e| match &e {
            crate::error::Error::Http { status, .. } if *status == 204 => Ok(()),
            crate::error::Error::Serde(_) => Ok(()),
            _ => Err(e),
        })?;
    Ok(())
}

/// Info for a specific pet
pub async fn show_pet_by_id(client: &Client, pet_id: impl Into<String>) -> Result<Pet> {
    let pet_id = pet_id.into();
    let path = { fn path_seg(v: impl std::fmt::Display) -> String { v.to_string().replace('/', "%2F") } format!("/pets/{}", path_seg(&pet_id)) };
    let query: Vec<(&str, String)> = Vec::new();
    client.request_json::<Pet, _>(reqwest::Method::GET, &path, &query, None::<&()>).await
}

