use serde_json::Value;
use specforge_plugin::{GeneratedFile, Plugin, PluginResult};

/// Example plugin that emits a project README summarizing the generated SDK.
pub struct ReadmePlugin;

impl Default for ReadmePlugin {
    fn default() -> Self {
        Self
    }
}

impl Plugin for ReadmePlugin {
    fn generate(&self, ir_json: &str) -> PluginResult {
        let doc: Value = match serde_json::from_str(ir_json) {
            Ok(v) => v,
            Err(e) => {
                return PluginResult {
                    files: vec![],
                    errors: vec![format!("failed to parse IR: {e}")],
                }
            }
        };
        let title = doc["title"].as_str().unwrap_or("API");
        let version = doc["version"].as_str().unwrap_or("0.0.0");
        let op_count = doc["operations"].as_array().map(|a| a.len()).unwrap_or(0);
        let schema_count = doc["schemas"]["models"]
            .as_object()
            .map(|m| m.len())
            .unwrap_or(0);

        let content = format!(
            "# {title} v{version}\n\n\
             Generated by specforge plugin example.\n\n\
             - {op_count} operations\n\
             - {schema_count} schemas\n"
        );

        PluginResult {
            files: vec![GeneratedFile {
                path: "README.md".to_string(),
                content,
            }],
            errors: vec![],
        }
    }
}
