//! Emit the static SDK runtime: typed errors (discriminated unions), the
//! fetch-based client core, pluggable auth, retry with backoff, and pagination
//! helpers. These files are emitted once per generation and are the same
//! regardless of the spec (they're parameterized by config at runtime, not at
//! codegen time).

use std::path::{Path, PathBuf};

use specforge_core::Document;

use crate::util::path_str;

/// Emit all runtime files under `src/`. Returns the relative paths written.
pub fn emit(doc: &Document, out_dir: &Path) -> std::io::Result<Vec<String>> {
    let items = collect(doc, out_dir)?;
    let mut written = Vec::new();
    for (rel, abs, content) in &items {
        if let Some(parent) = abs.parent() {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::write(abs, content)?;
        written.push(rel.clone());
    }
    Ok(written)
}

/// Collect all runtime files (relative path, absolute path, content) for parallel writing.
pub fn collect(doc: &Document, out_dir: &Path) -> std::io::Result<Vec<(String, PathBuf, String)>> {
    let src = out_dir.join("src");
    let mut files = Vec::new();

    files.push((path_str(&src.join("errors.ts"), out_dir), src.join("errors.ts"), errors_source()));
    files.push((path_str(&src.join("auth.ts"), out_dir), src.join("auth.ts"), auth_source(doc)));
    files.push((path_str(&src.join("retry.ts"), out_dir), src.join("retry.ts"), retry_source()));
    files.push((path_str(&src.join("paginate.ts"), out_dir), src.join("paginate.ts"), paginate_source()));
    files.push((path_str(&src.join("concurrency.ts"), out_dir), src.join("concurrency.ts"), concurrency_source()));
    files.push((path_str(&src.join("dedup.ts"), out_dir), src.join("dedup.ts"), dedup_source()));
    files.push((path_str(&src.join("idempotency.ts"), out_dir), src.join("idempotency.ts"), idempotency_source()));
    files.push((path_str(&src.join("middleware.ts"), out_dir), src.join("middleware.ts"), middleware_source()));
    files.push((path_str(&src.join("interceptors.ts"), out_dir), src.join("interceptors.ts"), interceptors_source()));
    files.push((path_str(&src.join("streaming.ts"), out_dir), src.join("streaming.ts"), streaming_source()));
    files.push((path_str(&src.join("validate.ts"), out_dir), src.join("validate.ts"), validate_source(doc)));
    files.push((path_str(&src.join("cache.ts"), out_dir), src.join("cache.ts"), cache_source()));
    files.push((path_str(&src.join("ratelimit.ts"), out_dir), src.join("ratelimit.ts"), ratelimit_source()));
    files.push((path_str(&src.join("telemetry.ts"), out_dir), src.join("telemetry.ts"), telemetry_source()));
    files.push((path_str(&src.join("logging.ts"), out_dir), src.join("logging.ts"), logging_source()));
    files.push((path_str(&src.join("validation-middleware.ts"), out_dir), src.join("validation-middleware.ts"), validation_middleware_source()));
    files.push((path_str(&src.join("service_container.ts"), out_dir), src.join("service_container.ts"), service_container_source()));
    files.push((path_str(&src.join("client.ts"), out_dir), src.join("client.ts"), client_source(doc)));

    Ok(files)
}

/// `errors.ts` — typed errors as a discriminated union (the 2026 best practice
/// over throwing untyped Error subclasses). Each variant carries a stable
/// `type` discriminant so consumers can narrow exhaustively.
fn errors_source() -> String {
    r#"/* eslint-disable */
// Generated by specforge. DO NOT EDIT.

/**
 * Typed SDK errors, modeled as a discriminated union on the `type` field.
 * Narrow with a switch on `.type` for exhaustive handling.
 *
 *   try { await client.pets.listPets() }
 *   catch (e) {
 *     const err = e as ApiError;
 *     switch (err.type) {
 *       case "http":      ... break;
 *       case "network":   ... break;
 *       case "timeout":   ... break;
 *       default: const _: never = err; // exhaustiveness check
 *     }
 *   }
 */
export type ApiError =
  | HttpError
  | NetworkError
  | TimeoutError
  | ConfigurationError;

export interface HttpError {
  /** Discriminant. Always "http". */
  type: "http";
  /** HTTP status code returned by the server. */
  status: number;
  /** Raw response body (parsed JSON if possible, otherwise text). */
  body: unknown;
  /** The request URL that failed. */
  url: string;
  /** Human-readable status text, e.g. "Not Found". */
  message: string;
}

export interface NetworkError {
  /** Discriminant. Always "network". */
  type: "network";
  /** The underlying fetch error. */
  cause: unknown;
  message: string;
}

export interface TimeoutError {
  /** Discriminant. Always "timeout". */
  type: "timeout";
  /** Elapsed milliseconds before the request was aborted. */
  elapsedMs: number;
  message: string;
}

export interface ConfigurationError {
  /** Discriminant. Always "configuration". */
  type: "configuration";
  message: string;
}

/** True if `e` is one of our typed errors. */
export function isApiError(e: unknown): e is ApiError {
  return (
    typeof e === "object" &&
    e !== null &&
    "type" in e &&
    typeof (e as { type: unknown }).type === "string" &&
    ["http", "network", "timeout", "configuration"].includes(
      (e as { type: string }).type,
    )
  );
}

export function httpError(
  status: number,
  body: unknown,
  url: string,
  message: string,
): HttpError {
  return { type: "http", status, body, url, message };
}

export function networkError(cause: unknown, message: string): NetworkError {
  return { type: "network", cause, message };
}

export function timeoutError(elapsedMs: number): TimeoutError {
  return { type: "timeout", elapsedMs, message: `Request timed out after ${elapsedMs}ms` };
}

export function configurationError(message: string): ConfigurationError {
  return { type: "configuration", message };
}
"#
    .to_string()
}

/// `auth.ts` — pluggable auth providers. Bearer / API key are emitted when the
/// spec declares them; the runtime also exposes a no-op `AnonymousAuthProvider`.
fn auth_source(doc: &Document) -> String {
    let wants_bearer = doc
        .security
        .iter()
        .any(|s| matches!(s, specforge_core::SecurityScheme::HttpBearer));
    let api_key_header = doc.security.iter().find_map(|s| {
        if let specforge_core::SecurityScheme::ApiKey { header } = s {
            Some(header.clone())
        } else {
            None
        }
    });
    let wants_apikey = api_key_header.is_some();
    let api_header_name = api_key_header.unwrap_or_default();

    let bearer_block = if wants_bearer {
        r#"
export interface BearerAuthProvider {
  /** Discriminant. Always "bearer". */
  type: "bearer";
  /** Return the bearer token (e.g. a JWT). Called on every request. */
  getToken(): string | Promise<string>;
}

export function bearerAuth(getToken: () => string | Promise<string>): BearerAuthProvider {
  return { type: "bearer", getToken };
}
"#
        .to_string()
    } else {
        String::new()
    };

    let apikey_block = if wants_apikey {
        format!(
            r#"
export interface ApiKeyAuthProvider {{
  /** Discriminant. Always "apikey". */
  type: "apikey";
  /** Return the API key value to send in the `{header}` header. */
  getApiKey(): string | Promise<string>;
}}

export function apiKeyAuth(getApiKey: () => string | Promise<string>): ApiKeyAuthProvider {{
  return {{ type: "apikey", getApiKey }};
}}
"#,
            header = api_header_name,
        )
    } else {
        String::new()
    };

    // Build the applyAuth switch body from only the schemes that exist, so the
    // emitted cases always match the AuthProvider union (TS would otherwise
    // flag unreachable/non-comparable cases).
    let mut cases = String::from("    case \"anonymous\":\n      return;\n");
    if wants_bearer {
        cases.push_str(
            "    case \"bearer\":\n      headers[\"Authorization\"] = `Bearer ${await auth.getToken()}`;\n      return;\n",
        );
    }
    if wants_apikey {
        cases.push_str(&format!(
            "    case \"apikey\":\n      headers[\"{api_header}\"] = await auth.getApiKey();\n      return;\n",
            api_header = api_header_name,
        ));
    }

    format!(
        r#"/* eslint-disable */
// Generated by specforge. DO NOT EDIT.

/**
 * Authentication providers. Pass one to `ApiClientOptions.auth`. Only schemes
 * declared by the spec are emitted; if the spec has no security requirements,
 * this module is minimal.
 */
export interface AnonymousAuthProvider {{
  type: "anonymous";
}}
export function anonymousAuth(): AnonymousAuthProvider {{
  return {{ type: "anonymous" }};
}}
{bearer}
{apikey}
export type AuthProvider = AnonymousAuthProvider{bearer_union}{apikey_union};

export async function applyAuth(
  headers: Record<string, string>,
  auth: AuthProvider,
): Promise<void> {{
  switch (auth.type) {{
{cases}    default:
      // Exhaustiveness check: only valid when the union has 2+ members. With
      // anonymous-only specs, `auth` here is still the single-member type, so
      // the `never` assertion would fail to typecheck — emit a plain no-op.
      {never_assert}
      return;
  }}
}}
"#,
        bearer = bearer_block,
        apikey = apikey_block,
        bearer_union = if wants_bearer { " | BearerAuthProvider" } else { "" },
        apikey_union = if wants_apikey { " | ApiKeyAuthProvider" } else { "" },
        cases = cases,
        never_assert = if wants_bearer || wants_apikey {
            "const _: never = auth;"
        } else {
            "// no other auth schemes declared by this spec"
        },
    )
}

/// `retry.ts` — exponential backoff with full jitter, configurable. Idempotent
/// methods (GET/HEAD/PUT/DELETE) are retried by default; POST is not.
fn retry_source() -> String {
    r#"/* eslint-disable */
// Generated by specforge. DO NOT EDIT.

export interface RetryOptions {
  /** Max retry attempts after the initial request. Default 2. */
  maxRetries?: number;
  /** Base delay in ms; actual delay = random(0, baseDelay * 2^attempt). Default 500. */
  baseDelayMs?: number;
  /** Cap on per-attempt delay. Default 8_000. */
  maxDelayMs?: number;
  /** Override which HTTP statuses are retried. Default [408, 429, 502, 503, 504]. */
  retryOnStatuses?: number[];
}

export const DEFAULT_RETRY_OPTIONS: Required<RetryOptions> = {
  maxRetries: 2,
  baseDelayMs: 500,
  maxDelayMs: 8_000,
  retryOnStatuses: [408, 429, 502, 503, 504],
};

/** Sleep for `ms` milliseconds. Uses setTimeout so it works in any runtime. */
export function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

/** Compute a full-jitter backoff delay (see AWS Architecture Blog: Exponential Backoff). */
export function backoffDelay(attempt: number, opts: Required<RetryOptions>): number {
  const ceiling = Math.min(opts.baseDelayMs * 2 ** attempt, opts.maxDelayMs);
  return Math.floor(Math.random() * ceiling);
}

/** True if a request method is safe to retry by default. */
export function isRetriableMethod(method: string): boolean {
  const m = method.toUpperCase();
  return m === "GET" || m === "HEAD" || m === "PUT" || m === "DELETE";
}
"#
    .to_string()
}

/// `paginate.ts` — async iterator helpers for cursor- and offset-based pages.
/// Consumers can `for await` over any list endpoint whose response exposes a
/// `nextCursor` field (cursor) or use `offsetPaginator` for offset APIs.
fn paginate_source() -> String {
    r#"/* eslint-disable */
// Generated by specforge. DO NOT EDIT.

/**
 * Pagination helpers. Use `cursorPaginator` when a list endpoint returns
 * `{ items, nextCursor }`; use `offsetPaginator` for `?offset=&limit=` APIs.
 *
 *   for await (const page of cursorPaginator((cursor) => client.pets.listPets({ cursor }))) {
 *     for (const pet of page.items) { ... }
 *   }
 */
export interface CursorPage<T> {
  items: T[];
  nextCursor: string | null;
}

export async function* cursorPaginator<T>(
  fetchPage: (cursor: string | undefined) => Promise<CursorPage<T>>,
): AsyncGenerator<CursorPage<T>> {
  let cursor: string | undefined = undefined;
  while (true) {
    const page = await fetchPage(cursor);
    yield page;
    if (!page.nextCursor) return;
    cursor = page.nextCursor;
  }
}

export interface OffsetPage<T> {
  items: T[];
  total?: number;
}

export async function* offsetPaginator<T>(
  fetchPage: (offset: number, limit: number) => Promise<OffsetPage<T>>,
  opts: { limit?: number } = {},
): AsyncGenerator<OffsetPage<T>> {
  const limit = opts.limit ?? 50;
  let offset = 0;
  while (true) {
    const page = await fetchPage(offset, limit);
    yield page;
    if (page.items.length < limit) return;
    offset += page.items.length;
  }
}
"#
    .to_string()
}

/// `concurrency.ts` — a per-client async semaphore bounding in-flight requests.
fn concurrency_source() -> String {
    r#"/* eslint-disable */
// Generated by specforge. DO NOT EDIT.

/**
 * A minimal async semaphore for bounding concurrent requests. FIFO, resolved on
 * the microtask queue (no timers), works in browsers/Node/workers/edge.
 *
 *   const sem = createSemaphore(5);
 *   const release = await sem.acquire();
 *   try { // do request
 *   } finally { release(); }
 */
export interface Semaphore {
  /** Block until a slot is free; return a function that releases the slot. */
  acquire(): Promise<() => void>;
  /** Number of currently-held slots. */
  readonly active: number;
  /** Number of waiters. */
  readonly waiting: number;
}

export function createSemaphore(max: number): Semaphore {
  if (!Number.isFinite(max) || max <= 0) {
    throw new RangeError(`maxConcurrent must be a positive finite number, got ${max}`);
  }
  let active = 0;
  const waiters: Array<() => void> = [];

  const release = () => {
    if (active === 0) return;
    active--;
    while (active < max && waiters.length > 0) {
      const resolve = waiters.shift()!;
      active++;
      resolve();
    }
  };

  return {
    acquire: () =>
      new Promise<() => void>((resolve) => {
        if (active < max) {
          active++;
          resolve(release);
          return;
        }
        waiters.push(() => resolve(release));
      }),
    get active() {
      return active;
    },
    get waiting() {
      return waiters.length;
    },
  };
}

/** A semaphore that never blocks — used when `maxConcurrent` is unset. */
export const UNLIMITED: Semaphore = {
  acquire: async () => () => {},
  get active() {
    return 0;
  },
  get waiting() {
    return 0;
  },
};
"#
    .to_string()
}

/// `dedup.ts` — request deduplication: identical in-flight GETs share one
/// request. Keyed on method + URL (safe methods only, per HTTP semantics).
fn dedup_source() -> String {
    r#"/* eslint-disable */
// Generated by specforge. DO NOT EDIT.

/**
 * In-flight request deduplication. When two callers issue the same safe
 * (GET/HEAD) request before the first settles, they share one fetch promise.
 * Unsafe methods are never deduped — they always execute independently.
 */
type BufferedResponse = {
  status: number;
  statusText: string;
  headers: Headers;
  body: ArrayBuffer;
};

export class RequestDeduper {
  private readonly inFlight = new Map<string, Promise<BufferedResponse>>();

  /** If a matching safe request is in flight, return its promise; otherwise
   *  run `run()` and cache it until it settles.
   *
   *  The body is buffered once and each waiter receives a fresh `Response`
   *  built from that buffer (a single fetch body can only be consumed once). */
  dedupe(method: string, url: string, run: () => Promise<Response>): Promise<Response> {
    if (!isSafeMethod(method)) return run();
    const key = `${method} ${url}`;
    let shared = this.inFlight.get(key);
    if (!shared) {
      shared = run()
        .then(async (res) => ({
          status: res.status,
          statusText: res.statusText,
          headers: res.headers,
          body: await res.arrayBuffer(),
        }))
        .finally(() => this.inFlight.delete(key));
      this.inFlight.set(key, shared);
    }
    return shared.then(
      (parts) =>
        new Response(parts.body.slice(0), {
          status: parts.status,
          statusText: parts.statusText,
          headers: parts.headers,
        }),
    );
  }

  get size(): number {
    return this.inFlight.size;
  }
}

export function isSafeMethod(method: string): boolean {
  const m = method.toUpperCase();
  return m === "GET" || m === "HEAD" || m === "OPTIONS";
}
"#
    .to_string()
}

/// `idempotency.ts` — auto-generate Idempotency-Key headers for unsafe methods
/// so retries are safe server-side (Stripe/GitHub-style).
fn idempotency_source() -> String {
    r#"/* eslint-disable */
// Generated by specforge. DO NOT EDIT.

/**
 * Idempotency key generation and header handling. Pairing unsafe-method
 * requests (POST/PUT/PATCH) with a unique Idempotency-Key makes retries safe:
 * if the same key reaches the server twice, it returns the original result
 * instead of executing twice.
 */
export const IDEMPOTENCY_HEADER = "Idempotency-Key";

/** True for methods where an idempotency key adds safety (per the spec's retry). */
export function isIdempotencyCandidate(method: string): boolean {
  const m = method.toUpperCase();
  return m === "POST" || m === "PUT" || m === "PATCH" || m === "DELETE";
}

/**
 * Generate a fresh idempotency key. Uses crypto.randomUUID when available
 * (browsers, Node 19+, edge), falling back to a crypto.getRandomValues-based
 * RFC-4122 v4 key.
 */
export function newIdempotencyKey(): string {
  const g = globalThis as { crypto?: Crypto };
  if (g.crypto?.randomUUID) return g.crypto.randomUUID();
  if (g.crypto?.getRandomValues) {
    const bytes = new Uint8Array(16);
    g.crypto.getRandomValues(bytes);
    bytes[6] = (bytes[6]! & 0x0f) | 0x40;
    bytes[8] = (bytes[8]! & 0x3f) | 0x80;
    const h = [...bytes].map((b) => b.toString(16).padStart(2, "0"));
    return `${h.slice(0, 4).join("")}-${h.slice(4, 6).join("")}-${h.slice(6, 8).join("")}-${h.slice(8, 10).join("")}-${h.slice(10, 16).join("")}`;
  }
  // Last-resort fallback (non-crypto). Adequate for collision avoidance only.
  return `key-${Date.now()}-${Math.random().toString(36).slice(2)}`;
}
"#
    .to_string()
}

/// `middleware.ts` — request/response interceptor chain for observability
/// (logging, metrics, tracing) without forking the client.
fn middleware_source() -> String {
    r#"/* eslint-disable */
// Generated by specforge. DO NOT EDIT.

/**
 * Middleware: observe or rewrite requests and responses. Registered in order;
 * each middleware wraps the next. Throw from a middleware to fail the request.
 *
 *   client.use(async (req, next) => {
 *     const start = Date.now();
 *     const res = await next(req);
 *     console.log(req.method, req.url, res.status, Date.now() - start, "ms");
 *     return res;
 *   });
 */
export interface MiddlewareRequest {
  method: string;
  url: string;
  headers: Record<string, string>;
  body?: BodyInit;
  signal?: AbortSignal;
}

export interface Middleware {
  (req: MiddlewareRequest, next: (req: MiddlewareRequest) => Promise<Response>): Promise<Response>;
}

/** Compose middlewares into a single handler around a terminal `dispatch`. */
export function composeMiddleware(
  middlewares: Middleware[],
  dispatch: (req: MiddlewareRequest) => Promise<Response>,
): (req: MiddlewareRequest) => Promise<Response> {
  // Apply in reverse so the first registered middleware runs outermost.
  let handler = dispatch;
  for (let i = middlewares.length - 1; i >= 0; i--) {
    const mw = middlewares[i]!;
    const next = handler;
    handler = (req) => mw(req, next);
  }
  return handler;
}
"#
    .to_string()
}

/// `interceptors.ts` — simple request/response body transform hooks. Simpler
/// than middleware: just transform the body before serialization or after
/// deserialization, without the full middleware chain.
fn interceptors_source() -> String {
    r#"/* eslint-disable */
// Generated by specforge. DO NOT EDIT.

/**
 * Request interceptor: transform the request body before it is serialized
 * and sent. Return the (possibly modified) body.
 */
export interface RequestInterceptor {
  /** Transform the request body. Return the modified body. */
  transform(body: unknown): unknown;
}

/**
 * Response interceptor: transform the response body after it is deserialized.
 * Return the (possibly modified) body.
 */
export interface ResponseInterceptor {
  /** Transform the response body. Return the modified body. */
  transform(body: unknown): unknown;
}
"#
    .to_string()
}

/// `streaming.ts` — async iterators over streaming responses (SSE and chunked
/// bodies). Useful for real-time/chat/completion endpoints.
fn streaming_source() -> String {
    r#"/* eslint-disable */
// Generated by specforge. DO NOT EDIT.

/**
 * Streaming helpers for endpoints that return `text/event-stream` or chunked
 * bodies. Consume as async iterators:
 *
 *   const res = await client.request("GET", "/events");
 *   for await (const chunk of streamBytes(res)) { ... }            // raw bytes
 *   for await (const event of streamSse(res)) { ... }              // parsed SSE
 */

/** Iterate over raw Uint8Array chunks of a streaming Response body. */
export async function* streamBytes(response: Response): AsyncGenerator<Uint8Array> {
  if (!response.body) throw new Error("response has no streaming body");
  const reader = response.body.getReader();
  try {
    while (true) {
      const { done, value } = await reader.read();
      if (done) return;
      if (value) yield value;
    }
  } finally {
    reader.releaseLock();
  }
}

/** Iterate over decoded text lines of a streaming Response body. */
export async function* streamLines(response: Response): AsyncGenerator<string> {
  const decoder = new TextDecoder();
  let buffer = "";
  for await (const chunk of streamBytes(response)) {
    buffer += decoder.decode(chunk, { stream: true });
    let nl: number;
    while ((nl = buffer.indexOf("\n")) >= 0) {
      const line = buffer.slice(0, nl).replace(/\r$/, "");
      buffer = buffer.slice(nl + 1);
      yield line;
    }
  }
  buffer += decoder.decode();
  if (buffer.length > 0) yield buffer;
}

export interface ServerSentEvent {
  /** The `event:` field, or "message" if absent. */
  event: string;
  /** The `data:` fields joined by newlines. */
  data: string;
  /** The `id:` field if present. */
  id?: string;
}

/**
 * Parse a Server-Sent Events stream. Handles `event:`, `data:`, `id:`, and
 * `retry:` fields, multi-line `data:`, and dispatches on blank-line separators.
 */
export async function* streamSse(response: Response): AsyncGenerator<ServerSentEvent> {
  let event = "message";
  let data: string[] = [];
  let id: string | undefined;
  for await (const line of streamLines(response)) {
    if (line === "") {
      if (data.length > 0 || event !== "message") {
        yield { event, data: data.join("\n"), id };
      }
      event = "message";
      data = [];
      id = undefined;
      continue;
    }
    if (line.startsWith(":")) continue; // comment
    const colon = line.indexOf(":");
    const field = colon >= 0 ? line.slice(0, colon) : line;
    const value = colon >= 0 ? line.slice(colon + 1).replace(/^ /, "") : "";
    switch (field) {
      case "event":
        event = value;
        break;
      case "data":
        data.push(value);
        break;
      case "id":
        id = value;
        break;
      case "retry":
        // Intentionally ignored; retry interval is handled by the caller.
        break;
    }
  }
}
"#
    .to_string()
}

/// `validate.ts` — runtime request/response validation against the OpenAPI schema.
/// Provides generic validation infrastructure plus per-model schema descriptors
/// and validators generated from the IR.
fn validate_source(doc: &Document) -> String {
    use specforge_core::Model;
    use crate::name::pascal;

    // Schema types + generic validator runtime.
    let mut out = String::from(
        r#"/* eslint-disable */
// Generated by specforge. DO NOT EDIT.

// ─── Schema descriptor types ────────────────────────────────────────────────

export type SchemaField = { type: SchemaType; required: boolean };
export type SchemaObject = { kind: "object"; fields: Record<string, SchemaField> };
export type SchemaRef = { kind: "ref"; name: string };
export type SchemaString = { kind: "string" };
export type SchemaNumber = { kind: "number" };
export type SchemaBoolean = { kind: "boolean" };
export type SchemaEnum = { kind: "enum"; values: readonly string[] };
export type SchemaArray = { kind: "array"; items: SchemaType };
export type SchemaType =
  | SchemaString
  | SchemaNumber
  | SchemaBoolean
  | SchemaEnum
  | SchemaArray
  | SchemaRef
  | SchemaObject;

// ─── Validation result ──────────────────────────────────────────────────────

export interface ValidationError {
  path: string;
  message: string;
}

// ─── Per-model validators ───────────────────────────────────────────────────

"#,
    );

    // Generate per-model validator + schema.
    for (_, model) in doc.schemas.iter() {
        let name = pascal(model.name());
        match model {
            Model::Object(o) => {
                // Schema descriptor.
                out.push_str(&format!("export const {name}Schema: SchemaObject = {{\n"));
                out.push_str("  kind: \"object\",\n");
                out.push_str("  fields: {\n");
                for prop in &o.properties {
                    let schema_ty = ts_schema_type(&prop.ty);
                    let req = if prop.required { "true" } else { "false" };
                    out.push_str(&format!(
                        "    \"{}\": {{ type: {}, required: {} }},\n",
                        escape_ts_string(&prop.name),
                        schema_ty,
                        req
                    ));
                }
                out.push_str("  },\n");
                out.push_str("};\n\n");

                // Validator function.
                out.push_str(&format!(
                    "export function validate{model}(value: unknown, path = \"\"): ValidationError[] {{\n",
                    model = name
                ));
                out.push_str(&format!(
                    "  return validateValue(value, {name}Schema, path);\n"
                ));
                out.push_str("}\n\n");
            }
            Model::Enum(e) => {
                let vals: Vec<String> = e
                    .variants
                    .iter()
                    .map(|v| format!("\"{}\"", escape_ts_string(&v.value)))
                    .collect();
                out.push_str(&format!(
                    "const {name}Values: readonly string[] = [{}] as const;\n\n",
                    vals.join(", ")
                ));
                out.push_str(&format!(
                    "export function validate{model}(value: unknown, path = \"\"): ValidationError[] {{\n",
                    model = name
                ));
                out.push_str("  const errors: ValidationError[] = [];\n");
                out.push_str(&format!(
                    "  validateEnum(value, {name}Values, path, errors);\n"
                ));
                out.push_str("  return errors;\n");
                out.push_str("}\n\n");
            }
        }
    }

    // Generic validator runtime.
    out.push_str(
        r#"
// ─── Generic validation runtime ─────────────────────────────────────────────

function validateString(value: unknown, path: string, errors: ValidationError[]): void {
  if (typeof value !== "string") {
    errors.push({ path, message: `expected string, got ${typeof value}` });
  }
}

function validateNumber(value: unknown, path: string, errors: ValidationError[]): void {
  if (typeof value !== "number") {
    errors.push({ path, message: `expected number, got ${typeof value}` });
  }
}

function validateBoolean(value: unknown, path: string, errors: ValidationError[]): void {
  if (typeof value !== "boolean") {
    errors.push({ path, message: `expected boolean, got ${typeof value}` });
  }
}

function validateEnum(value: unknown, values: readonly string[], path: string, errors: ValidationError[]): void {
  if (typeof value !== "string") {
    errors.push({ path, message: `expected string, got ${typeof value}` });
    return;
  }
  if (!(values as string[]).includes(value)) {
    errors.push({ path, message: `expected one of [${values.join(", ")}], got "${value}"` });
  }
}

function validateArray(value: unknown, itemSchema: SchemaType, path: string, errors: ValidationError[]): void {
  if (!Array.isArray(value)) {
    errors.push({ path, message: `expected array, got ${typeof value}` });
    return;
  }
  for (let i = 0; i < value.length; i++) {
    validateValue(value[i], itemSchema, `${path}[${i}]`, errors);
  }
}

function validateObject(value: unknown, schema: SchemaObject, path: string, errors: ValidationError[]): void {
  if (typeof value !== "object" || value === null || Array.isArray(value)) {
    errors.push({ path, message: `expected object, got ${value === null ? "null" : typeof value}` });
    return;
  }
  const obj = value as Record<string, unknown>;
  for (const [key, field] of Object.entries(schema.fields)) {
    const fieldPath = path ? `${path}.${key}` : key;
    if (obj[key] === undefined) {
      if (field.required) {
        errors.push({ path: fieldPath, message: "missing required field" });
      }
      continue;
    }
    validateValue(obj[key], field.type, fieldPath, errors);
  }
}

/** Resolve a SchemaType, following refs to the models map. */
function resolveSchema(schema: SchemaType, models: Record<string, SchemaObject>): SchemaObject | null {
  if (schema.kind === "object") return schema;
  if (schema.kind === "ref") return models[schema.name] ?? null;
  return null;
}

/**
 * Generic validation: dispatch on the schema kind to check the value.
 * Accumulates errors into the provided array. Used by per-model validators
 * and by validateRequest / validateResponse.
 */
export function validateValue(
  value: unknown,
  schema: SchemaType,
  path: string,
  errors: ValidationError[],
): void {
  if (value === undefined || value === null) return;

  switch (schema.kind) {
    case "string":
      validateString(value, path, errors);
      break;
    case "number":
      validateNumber(value, path, errors);
      break;
    case "boolean":
      validateBoolean(value, path, errors);
      break;
    case "enum":
      validateEnum(value, schema.values, path, errors);
      break;
    case "array":
      validateArray(value, schema.items, path, errors);
      break;
    case "object":
      validateObject(value, schema, path, errors);
      break;
    case "ref":
      // Refs are resolved at the call site; this path shouldn't normally be hit
      // from validateValue since callers resolve refs first.
      break;
  }
}

// ─── Request / Response validation ──────────────────────────────────────────

/**
 * Validate a request body against a schema. Returns an empty array when valid.
 * Call with the method, path, body, and a SchemaType descriptor.
 */
export function validateRequest(
  method: string,
  path: string,
  body: unknown,
  schema: SchemaType | undefined,
): ValidationError[] {
  if (!schema || body === undefined || body === null) return [];
  const errors: ValidationError[] = [];
  validateValue(body, schema, "body", errors);
  if (errors.length > 0) {
    const err = new Error(
      `[validate] ${method} ${path} request body: ${errors.map((e) => `${e.path}: ${e.message}`).join("; ")}`,
    );
    (err as any).validationErrors = errors;
    throw err;
  }
  return errors;
}

/**
 * Validate a response body against a schema. Returns an empty array when valid.
 * Call with the method, path, status, body, and a SchemaType descriptor.
 */
export function validateResponse(
  method: string,
  path: string,
  status: number,
  body: unknown,
  schema: SchemaType | undefined,
): ValidationError[] {
  if (!schema || body === undefined || body === null) return [];
  const errors: ValidationError[] = [];
  validateValue(body, schema, "body", errors);
  if (errors.length > 0) {
    const err = new Error(
      `[validate] ${method} ${path} response ${status}: ${errors.map((e) => `${e.path}: ${e.message}`).join("; ")}`,
    );
    (err as any).validationErrors = errors;
    throw err;
  }
  return errors;
}
"#,
    );

    out
}

/// `validation-middleware.ts` -- automatic request/response validation middleware
/// that intercepts all requests and validates bodies against the OpenAPI schema.
fn validation_middleware_source() -> String {
    r#"/* eslint-disable */
// Generated by specforge. DO NOT EDIT.

import { Middleware, MiddlewareRequest } from "./middleware";
import { SchemaType, ValidationError, validateValue } from "./validate";

/**
 * Schema descriptor for an endpoint's request and/or response body.
 */
export interface EndpointSchema {
  /** Schema for the request body. Undefined means no request body validation. */
  requestBody?: SchemaType;
  /** Schema for the response body. Undefined means no response body validation. */
  responseBody?: SchemaType;
}

/**
 * A route schema map keyed by "METHOD /path/pattern".
 * Patterns use `{param}` placeholders for path segments.
 */
export interface RouteSchemaMap {
  [route: string]: EndpointSchema;
}

/**
 * Validate that `actualPath` matches the `pattern` path.
 * Pattern segments wrapped in `{...}` are treated as wildcards.
 * Returns true when every segment matches (exact or wildcard).
 */
function matchesPath(pattern: string, actualPath: string): boolean {
  const patternSegments = pattern.split("/").filter(Boolean);
  const actualSegments = actualPath.split("/").filter(Boolean);
  if (patternSegments.length !== actualSegments.length) return false;
  for (let i = 0; i < patternSegments.length; i++) {
    const ps = patternSegments[i]!;
    if (ps.startsWith("{") && ps.endsWith("}")) continue; // wildcard
    if (ps !== actualSegments[i]) return false;
  }
  return true;
}

/**
 * Create a validation middleware that intercepts all requests and validates
 * request/response bodies against the OpenAPI schema.
 *
 * Usage:
 * ```ts
 * import { createValidationMiddleware, RouteSchemaMap } from "./validation-middleware";
 *
 * const schemas: RouteSchemaMap = {
 *   "POST /pets": { requestBody: PetSchema, responseBody: PetSchema },
 *   "GET /pets/{petId}": { responseBody: PetSchema },
 * };
 *
 * client.use(createValidationMiddleware(schemas));
 * ```
 *
 * The middleware validates request bodies before dispatch and response bodies
 * after a successful response. Validation errors are thrown as Error objects
 * with a `validationErrors` property containing the details.
 */
export function createValidationMiddleware(schemas: RouteSchemaMap): Middleware {
  return async (req: MiddlewareRequest, next: (req: MiddlewareRequest) => Promise<Response>): Promise<Response> => {
    const method = req.method.toUpperCase();
    // Strip query string for route matching.
    const path = req.url.split("?")[0] || "";

    // Find a matching route schema.
    const routeKey = `${method} ${path}`;
    let endpointSchema = schemas[routeKey];

    // Try pattern matching if exact match fails.
    if (!endpointSchema) {
      for (const [pattern, schema] of Object.entries(schemas)) {
        const spaceIdx = pattern.indexOf(" ");
        if (spaceIdx < 0) continue;
        const patternMethod = pattern.substring(0, spaceIdx).toUpperCase();
        const patternPath = pattern.substring(spaceIdx + 1);
        if (patternMethod === method && matchesPath(patternPath, path)) {
          endpointSchema = schema;
          break;
        }
      }
    }

    // Validate request body if a schema is defined.
    if (endpointSchema?.requestBody && req.body !== undefined && req.body !== null) {
      let body: unknown;
      if (typeof req.body === "string") {
        try { body = JSON.parse(req.body); } catch { body = req.body; }
      } else if (
        typeof ReadableStream !== "undefined" && req.body instanceof ReadableStream ||
        typeof Blob !== "undefined" && req.body instanceof Blob ||
        typeof ArrayBuffer !== "undefined" && req.body instanceof ArrayBuffer ||
        typeof FormData !== "undefined" && req.body instanceof FormData
      ) {
        // Cannot validate non-JSON body types; skip.
      } else {
        body = req.body;
      }
      if (body !== undefined && body !== null && typeof body !== "string") {
        const errors: ValidationError[] = [];
        validateValue(body, endpointSchema.requestBody, "body", errors);
        if (errors.length > 0) {
          const err = new Error(
            `[validation] ${method} ${path} request body: ${errors.map((e) => `${e.path}: ${e.message}`).join("; ")}`,
          );
          (err as any).validationErrors = errors;
          throw err;
        }
      }
    }

    // Proceed with the request.
    const response = await next(req);

    // Validate response body if a schema is defined and the response is JSON.
    if (endpointSchema?.responseBody && response.ok) {
      const contentType = response.headers.get("content-type") || "";
      if (contentType.includes("application/json")) {
        const cloned = response.clone();
        try {
          const text = await cloned.text();
          if (text) {
            const body = JSON.parse(text);
            const errors: ValidationError[] = [];
            validateValue(body, endpointSchema.responseBody, "body", errors);
            if (errors.length > 0) {
              const err = new Error(
                `[validation] ${method} ${path} response ${response.status}: ${errors.map((e) => `${e.path}: ${e.message}`).join("; ")}`,
              );
              (err as any).validationErrors = errors;
              throw err;
            }
          }
        } catch (e) {
          if ((e as any).validationErrors) throw e;
          // Non-JSON or parse error -- skip response validation.
        }
      }
    }

    return response;
  };
}
"#
    .to_string()
}

/// Map an IR `Type` to a TypeScript `SchemaType` expression string for the
/// validation schema descriptor.
fn ts_schema_type(ty: &specforge_core::Type) -> String {
    use specforge_core::{CompositionKind, Scalar, Type};
    match ty {
        Type::Scalar(s) => match s {
            Scalar::String | Scalar::DateTime | Scalar::Uuid | Scalar::Integer64 | Scalar::Base64 | Scalar::Binary => {
                "{ kind: \"string\" }".into()
            }
            Scalar::Integer | Scalar::Float => "{ kind: \"number\" }".into(),
            Scalar::Boolean => "{ kind: \"boolean\" }".into(),
        },
        Type::StringEnum { variants, .. } => {
            let vals: Vec<String> = variants
                .iter()
                .map(|v| format!("\"{}\"", escape_ts_string(v)))
                .collect();
            format!("{{ kind: \"enum\", values: [{}] }}", vals.join(", "))
        }
        Type::Array { item, .. } => {
            format!("{{ kind: \"array\", items: {} }}", ts_schema_type(item))
        }
        Type::Map { .. } => "{ kind: \"string\" }".into(), // keys are strings
        Type::Reference { name, .. } => {
            format!(
                "{{ kind: \"ref\", name: \"{}\" }}",
                escape_ts_string(&crate::name::pascal(name))
            )
        }
        Type::Composition(c) => match c.kind {
            CompositionKind::AllOf => c
                .members
                .first()
                .map(ts_schema_type)
                .unwrap_or_else(|| "{ kind: \"string\" }".into()),
            CompositionKind::OneOf | CompositionKind::AnyOf => {
                // Use the first reference arm if available.
                c.members
                    .iter()
                    .find_map(|m| match m {
                        Type::Reference { name, .. } => Some(format!(
                            "{{ kind: \"ref\", name: \"{}\" }}",
                            escape_ts_string(&crate::name::pascal(name))
                        )),
                        _ => None,
                    })
                    .unwrap_or_else(|| "{ kind: \"string\" }".into())
            }
        },
        Type::Any | Type::Unknown => "{ kind: \"string\" }".into(),
    }
}

fn escape_ts_string(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

/// `cache.ts` — response caching with ETag/conditional request support.
/// GET responses are cached; subsequent requests send `If-None-Match` and
/// return the cached body on 304 Not Modified.
fn cache_source() -> String {
    r#"/* eslint-disable */
// Generated by specforge. DO NOT EDIT.

/**
 * A cached response entry: the ETag returned by the server, the parsed data,
 * and the wall-clock time the entry was stored.
 */
export interface CacheEntry {
    etag: string;
    data: unknown;
    timestamp: number;
}

/**
 * In-memory response cache keyed by full URL. Supports TTL-based expiry and
 * ETag-based conditional requests (`If-None-Match` / 304 Not Modified).
 *
 *   const cache = new ResponseCache(60_000);
 *   const cached = cache.get(url);
 *   if (cached) headers["If-None-Match"] = cached.etag;
 *   // ... on 304: return cached.data
 *   // ... on 200: cache.set(url, etag, data)
 */
export class ResponseCache {
    private cache = new Map<string, CacheEntry>();
    private ttl: number;

    constructor(ttlMs: number = 60000) {
        this.ttl = ttlMs;
    }

    /** Return the cached entry for `url` if it exists and has not expired. */
    get(url: string): CacheEntry | undefined {
        const entry = this.cache.get(url);
        if (entry && Date.now() - entry.timestamp < this.ttl) {
            return entry;
        }
        // Expired — evict.
        this.cache.delete(url);
        return undefined;
    }

    /** Store a response under `url` with its ETag and parsed data. */
    set(url: string, etag: string, data: unknown): void {
        this.cache.set(url, { etag, data, timestamp: Date.now() });
    }

    /** Remove all cached entries. */
    clear(): void {
        this.cache.clear();
    }

    /** Number of entries currently in the cache (including expired). */
    get size(): number {
        return this.cache.size;
    }
}
"#
    .to_string()
}

/// `logging.ts` — structured logging abstraction. Consumers plug in their own
/// logger; the SDK logs requests, responses, retries, and cache hits/misses.
fn logging_source() -> String {
    r#"/* eslint-disable */
// Generated by specforge. DO NOT EDIT.

/**
 * Structured logging interface. Implement this to plug in your own logger.
 * All methods receive a message string and optional structured context.
 */
export interface Logger {
  debug(message: string, ...args: unknown[]): void;
  info(message: string, ...args: unknown[]): void;
  warn(message: string, ...args: unknown[]): void;
  error(message: string, ...args: unknown[]): void;
}

/**
 * Default logger that delegates to console.debug/info/warn/error.
 */
export class ConsoleLogger implements Logger {
  debug(message: string, ...args: unknown[]): void {
    console.debug(message, ...args);
  }
  info(message: string, ...args: unknown[]): void {
    console.info(message, ...args);
  }
  warn(message: string, ...args: unknown[]): void {
    console.warn(message, ...args);
  }
  error(message: string, ...args: unknown[]): void {
    console.error(message, ...args);
  }
}

/** A no-op logger that discards all messages. */
export const NoopLogger: Logger = {
  debug() {},
  info() {},
  warn() {},
  error() {},
};
"#
    .to_string()
}

/// `ratelimit.ts` — rate limiting interface and built-in implementations.
fn ratelimit_source() -> String {
    r#"/* eslint-disable */
// Generated by specforge. DO NOT EDIT.

/**
 * Rate limiter interface. The client calls `acquire()` before each request;
 * the returned promise resolves when the request is allowed to proceed.
 */
export interface RateLimiter {
  /** Block until the request is allowed. Reject to abort. */
  acquire(): Promise<void>;
}

/**
 * Token bucket rate limiter. Tokens refill at a constant rate up to a maximum.
 * Each request consumes one token; when empty, `acquire()` waits for a refill.
 */
export class TokenBucket implements RateLimiter {
  private tokens: number;
  private readonly maxTokens: number;
  private readonly refillRate: number; // tokens per second
  private lastRefill: number;

  constructor(maxTokens: number, refillRate: number) {
    this.maxTokens = maxTokens;
    this.tokens = maxTokens;
    this.refillRate = refillRate;
    this.lastRefill = Date.now();
  }

  async acquire(): Promise<void> {
    this.refill();
    while (this.tokens < 1) {
      // Wait for the next refill.
      const waitMs = Math.ceil((1 - this.tokens) / this.refillRate * 1000);
      await new Promise((resolve) => setTimeout(resolve, Math.max(waitMs, 10)));
      this.refill();
    }
    this.tokens -= 1;
  }

  private refill(): void {
    const now = Date.now();
    const elapsed = (now - this.lastRefill) / 1000;
    this.tokens = Math.min(this.maxTokens, this.tokens + elapsed * this.refillRate);
    this.lastRefill = now;
  }
}

/**
 * Sliding window rate limiter. Allows at most `maxRequests` within any rolling
 * `windowMs`. When the limit is reached, `acquire()` waits until the oldest
 * request in the window expires.
 */
export class SlidingWindow implements RateLimiter {
  private readonly requests: number[] = [];
  private readonly maxRequests: number;
  private readonly windowMs: number;

  constructor(maxRequests: number, windowMs: number) {
    this.maxRequests = maxRequests;
    this.windowMs = windowMs;
  }

  async acquire(): Promise<void> {
    this.evict();
    if (this.requests.length >= this.maxRequests) {
      const oldest = this.requests[0]!;
      const waitMs = this.windowMs - (Date.now() - oldest);
      if (waitMs > 0) {
        await new Promise((resolve) => setTimeout(resolve, waitMs));
      }
      this.evict();
    }
    this.requests.push(Date.now());
  }

  private evict(): void {
    const cutoff = Date.now() - this.windowMs;
    while (this.requests.length > 0 && this.requests[0]! <= cutoff) {
      this.requests.shift();
    }
  }
}
"#
    .to_string()
}

/// `telemetry.ts` — telemetry hooks for request lifecycle observability.
fn telemetry_source() -> String {
    r#"/* eslint-disable */
// Generated by specforge. DO NOT EDIT.

/**
 * Telemetry hooks for observing the SDK request lifecycle.
 * Implement any subset; unused hooks are simply not called.
 */
export interface TelemetryHooks {
  /** Called just before the request is dispatched. */
  onRequestStart?(method: string, path: string): void;
  /** Called after a successful response (2xx) with the elapsed duration. */
  onRequestEnd?(method: string, path: string, durationMs: number, status: number): void;
  /** Called when a request fails (network, timeout, non-retriable HTTP error). */
  onRequestError?(method: string, path: string, durationMs: number, error: unknown): void;
  /** Called before a retry attempt (after backoff sleep). */
  onRetry?(method: string, path: string, attempt: number, error: unknown): void;
  /** Called when a GET request is served from the response cache. */
  onCacheHit?(method: string, path: string): void;
  /** Called when a GET request misses the cache and goes to the network. */
  onCacheMiss?(method: string, path: string): void;
}

/**
 * Built-in metrics collector that tracks request counts, errors, durations,
 * and retries. Use `getMetrics()` to obtain a snapshot.
 */
export class MetricsCollector implements TelemetryHooks {
  private requestCount = 0;
  private errorCount = 0;
  private totalDurationMs = 0;
  private retryCount = 0;

  onRequestStart(_method: string, _path: string): void {
    this.requestCount++;
  }

  onRequestEnd(_method: string, _path: string, durationMs: number, status: number): void {
    this.totalDurationMs += durationMs;
    if (status >= 400) this.errorCount++;
  }

  onRequestError(_method: string, _path: string, durationMs: number, _error: unknown): void {
    this.errorCount++;
    this.totalDurationMs += durationMs;
  }

  onRetry(_method: string, _path: string, _attempt: number, _error: unknown): void {
    this.retryCount++;
  }

  /** Return a snapshot of the collected metrics. */
  getMetrics(): Metrics {
    return {
      requestCount: this.requestCount,
      errorCount: this.errorCount,
      totalDurationMs: this.totalDurationMs,
      avgDurationMs: this.requestCount > 0 ? this.totalDurationMs / this.requestCount : 0,
      retryCount: this.retryCount,
    };
  }
}

export interface Metrics {
  requestCount: number;
  errorCount: number;
  totalDurationMs: number;
  avgDurationMs: number;
  retryCount: number;
}
"#
    .to_string()
}

/// `service_container.ts` — typed DI container grouping all injectable
/// dependencies for easy swapping and testing.
fn service_container_source() -> String {
    r#"/* eslint-disable */
// Generated by specforge. DO NOT EDIT.

import type { ResponseCache } from "./cache";
import type { RateLimiter } from "./ratelimit";
import type { Logger } from "./logging";
import type { TelemetryHooks } from "./telemetry";

/**
 * Typed service container grouping all injectable SDK dependencies.
 * Use `createContainer()` to build one; pass it to `ApiClientOptions.container`
 * to apply all services at once.
 *
 * Every field is optional: unspecified services use the SDK defaults
 * (global fetch, no cache, no rate limiter, console logger, no telemetry).
 *
 * @example
 * ```ts
 * const container = createContainer({
 *   httpClient: myCustomFetch,
 *   logger: new ConsoleLogger(),
 *   rateLimiter: new TokenBucket(10, 5),
 * });
 * const client = new ApiClient({ container });
 * ```
 */
export interface ServiceContainer {
  /** Custom fetch implementation (e.g. for testing, undici, or cloud workers). */
  httpClient?: typeof fetch;
  /** Pre-configured response cache for GET requests with ETag support. */
  cache?: ResponseCache;
  /** Rate limiter applied before each request. */
  rateLimiter?: RateLimiter;
  /** Structured logger for SDK lifecycle events. */
  logger?: Logger;
  /** Telemetry hooks for request lifecycle observability. */
  telemetry?: TelemetryHooks;
}

/**
 * Create a typed service container. All fields default to `undefined`
 * (the SDK applies its own defaults for unspecified services).
 */
export function createContainer(opts: ServiceContainer = {}): ServiceContainer {
  return { ...opts };
}
"#
    .to_string()
}

/// `client.ts` — the fetch-based core. Configurable base URL, auth, retry,
/// timeout, and custom fetch. Emits typed errors on failure.
fn client_source(doc: &Document) -> String {
    let default_base = doc
        .base_url
        .as_deref()
        .unwrap_or("https://example.com");
    format!(
        r#"/* eslint-disable */
// Generated by specforge. DO NOT EDIT.

import {{ ApiError, configurationError, httpError, isApiError, networkError, timeoutError }} from "./errors";
import {{ AuthProvider, applyAuth, anonymousAuth }} from "./auth";
import {{ DEFAULT_RETRY_OPTIONS, backoffDelay, isRetriableMethod, sleep }} from "./retry";
import type {{ RetryOptions }} from "./retry";
import {{ Semaphore, createSemaphore, UNLIMITED }} from "./concurrency";
import {{ RequestDeduper }} from "./dedup";
import {{ IDEMPOTENCY_HEADER, isIdempotencyCandidate, newIdempotencyKey }} from "./idempotency";
import {{ Middleware, MiddlewareRequest, composeMiddleware }} from "./middleware";
import {{ validateRequest, validateResponse, type SchemaType, type ValidationError }} from "./validate";
import {{ ResponseCache }} from "./cache";
import {{ type Logger, ConsoleLogger }} from "./logging";
import {{ type RequestInterceptor, type ResponseInterceptor }} from "./interceptors";
import {{ type ServiceContainer }} from "./service_container";
import {{ createValidationMiddleware, type RouteSchemaMap }} from "./validation-middleware";

/**
 * Transform response data before it reaches the application. Transformers are
 * applied in order after response validation (when enabled) and before the
 * value is returned to the caller.
 */
export interface ResponseTransformer {{
  /** Return a new value derived from `response`, or `response` unchanged. */
  transform(response: unknown): unknown;
}}

export interface ApiClientOptions {{
  /** Override the spec's base URL. Defaults to `{default_base}`. */
  baseUrl?: string;
  /** Auth provider. Defaults to anonymous if the spec declares no security. */
  auth?: AuthProvider;
  /** Default request timeout in ms. Default 30_000. Overridable per-call. */
  timeoutMs?: number;
  /** Retry configuration. See RetryOptions. */
  retry?: RetryOptions;
  /** Max in-flight requests. Default: unlimited. Set to bound socket usage. */
  maxConcurrent?: number;
  /** Deduplicate identical in-flight safe (GET/HEAD/OPTIONS) requests. Default true. */
  dedupe?: boolean;
  /** Auto-attach Idempotency-Key to POST/PUT/PATCH/DELETE so retries are safe. Default true. */
  idempotency?: boolean;
  /** Observability/rewrite middleware, applied in registration order. */
  middleware?: Middleware[];
  /** Inject a custom fetch (e.g. for testing or undici). Default: global fetch. */
  fetch?: typeof fetch;
  /** Extra default headers merged onto every request. */
  defaultHeaders?: Record<string, string>;
  /** Enable runtime request/response validation against the OpenAPI schema. Default false. */
  validate?: boolean;
  /** Pre-configured ResponseCache instance. Takes precedence over `cacheTtlMs`. */
  cache?: ResponseCache;
  /** Enable GET response caching with ETag/conditional requests. Sets the TTL in ms. */
  cacheTtlMs?: number;
  /** Response transformers applied after validation, in order. */
  responseTransformers?: ResponseTransformer[];
  /** Structured logger for SDK lifecycle events (requests, retries, cache). */
  logger?: Logger;
  /** Request interceptors applied before each request body is serialized. */
  requestInterceptors?: RequestInterceptor[];
  /** Response interceptors applied after each response body is deserialized. */
  responseInterceptors?: ResponseInterceptor[];
  /**
   * Typed service container grouping injectable dependencies (fetch, cache,
   * rate limiter, logger, telemetry). Individual option fields take precedence
   * over container values.
   */
  container?: ServiceContainer;
}}

/**
 * Core HTTP client. SDK methods (one per operation) build requests through this.
 * Errors are thrown as typed {{@link ApiError}} values; narrow with `.type`.
 *
 * Concurrency: async by default; `Promise.all([...])` fans out in parallel.
 * Set `maxConcurrent` to bound the fan-out. Identical in-flight safe requests
 * are deduplicated. POST/PUT/PATCH/DELETE get auto Idempotency-Key headers so
 * retries never double-execute server-side.
 */
export class ApiClient {{
  readonly baseUrl: string;
  readonly auth: AuthProvider;
  readonly timeoutMs: number;
  readonly retry: Required<RetryOptions>;
  private readonly fetchImpl: typeof fetch;
  private readonly defaultHeaders: Record<string, string>;
  private readonly semaphore: Semaphore;
  private readonly deduper: RequestDeduper;
  private readonly useDedupe: boolean;
  private readonly useIdempotency: boolean;
  private middlewares: Middleware[] = [];
  /** When true, operations validate request/response bodies against the schema. */
  readonly validate: boolean;
  /** Optional response cache for GET requests with ETag support. */
  readonly cache?: ResponseCache;
  /** Response transformers applied after validation, in order. */
  private readonly responseTransformers: ResponseTransformer[];
  /** Structured logger for SDK lifecycle events. */
  private readonly logger: Logger;
  /** Request interceptors applied before each request body is serialized. */
  private readonly requestInterceptors: RequestInterceptor[];
  /** Response interceptors applied after each response body is deserialized. */
  private readonly responseInterceptors: ResponseInterceptor[];

  constructor(opts: ApiClientOptions = {{}}) {{
    const c = opts.container;
    this.baseUrl = (opts.baseUrl ?? "{default_base}").replace(/\/$/, "");
    this.auth = opts.auth ?? anonymousAuth();
    this.timeoutMs = opts.timeoutMs ?? 30_000;
    this.retry = {{ ...DEFAULT_RETRY_OPTIONS, ...opts.retry }};
    // Individual options take precedence over container values.
    this.fetchImpl = opts.fetch ?? c?.httpClient ?? fetch;
    this.defaultHeaders = {{ "content-type": "application/json", ...opts.defaultHeaders }};
    if (!("accept" in this.defaultHeaders)) this.defaultHeaders["accept"] = "application/json";
    this.semaphore = opts.maxConcurrent ? createSemaphore(opts.maxConcurrent) : UNLIMITED;
    this.deduper = new RequestDeduper();
    this.useDedupe = opts.dedupe ?? true;
    this.useIdempotency = opts.idempotency ?? true;
    this.validate = opts.validate ?? false;
    this.cache = opts.cache ?? c?.cache ?? (opts.cacheTtlMs !== undefined ? new ResponseCache(opts.cacheTtlMs) : undefined);
    this.responseTransformers = opts.responseTransformers ?? [];
    this.logger = opts.logger ?? c?.logger ?? new ConsoleLogger();
    this.requestInterceptors = opts.requestInterceptors ?? [];
    this.responseInterceptors = opts.responseInterceptors ?? [];
    if (opts.middleware) for (const m of opts.middleware) this.middlewares.push(m);
  }}

  /** Register an observability/rewrite middleware. Returns `this` for chaining. */
  use(middleware: Middleware): this {{
    this.middlewares.push(middleware);
    return this;
  }}

  /** Issue a request and return the raw Response, applying concurrency,
   *  dedup, auth, retry, timeout, idempotency, and middleware. */
  async request(
    method: string,
    path: string,
    requestOptions?: RequestOptions,
  ): Promise<Response> {{
    if (typeof path !== "string" || !path.startsWith("/")) {{
      throw configurationError(`path must start with "/", got ${{JSON.stringify(path)}}`);
    }}
    const url = this.baseUrl + path + (requestOptions?.query ? "?" + encodeQuery(requestOptions.query) : "");

    // --- ETag cache: check for GET requests before dispatching ---
    const isGet = method.toUpperCase() === "GET";
    const cachedEntry = isGet && this.cache ? this.cache.get(url) : undefined;
    if (cachedEntry) {{
      this.logger.debug(`[cache] HIT ${{method}} ${{path}}`);
    }} else if (isGet && this.cache) {{
      this.logger.debug(`[cache] MISS ${{method}} ${{path}}`);
    }}
    const mergedHeaders: Record<string, string> | undefined =
      cachedEntry
        ? {{ ...requestOptions?.headers, "If-None-Match": cachedEntry.etag }}
        : requestOptions?.headers;

    // The core dispatch loop (retry-aware). Split out so dedup can memoize it.
    const dispatch = async (): Promise<Response> => {{
      const release = await this.semaphore.acquire();
      try {{
        return await this.dispatchWithRetry(method, url, {{ ...requestOptions, headers: mergedHeaders }});
      }} finally {{
        release();
      }}
    }};

    let response: Response;
    if (this.useDedupe) {{
      response = await this.deduper.dedupe(method, url, dispatch);
    }} else {{
      response = await dispatch();
    }}

    // --- ETag cache: handle 304 Not Modified and update on 200 ---
    if (isGet && this.cache) {{
      if (response.status === 304 && cachedEntry) {{
        // Return cached data as a synthetic Response.
        return new Response(JSON.stringify(cachedEntry.data), {{
          status: 200,
          statusText: "OK (cached)",
          headers: {{ "content-type": "application/json", "x-cache": "HIT" }},
        }});
      }}
      if (response.ok) {{
        const etag = response.headers.get("etag");
        if (etag) {{
          // Buffer the body so we can both return it and cache it.
          const cloned = response.clone();
          const body = await cloned.text();
          try {{
            this.cache.set(url, etag, JSON.parse(body));
          }} catch {{
            // Non-JSON body — cache the raw text.
            this.cache.set(url, etag, body);
          }}
        }}
      }}
    }}

    return response;
  }}

  /** Retry loop around a single attempt. Holds a semaphore slot while running. */
  private async dispatchWithRetry(
    method: string,
    url: string,
    requestOptions: RequestOptions | undefined,
  ): Promise<Response> {{
    const perCallRetry = requestOptions?.retry;
    const maxRetries = perCallRetry?.maxRetries ?? this.retry.maxRetries;
    const retryable = perCallRetry?.retryable ?? isRetriableMethod(method);
    for (let attempt = 0; attempt <= maxRetries; attempt++) {{
      // Per-attempt headers: fresh copy + auth + idempotency key on first try.
      const headers: Record<string, string> = {{ ...this.defaultHeaders, ...requestOptions?.headers }};
      await applyAuth(headers, this.auth);
      // Attach a fresh idempotency key on the first attempt of an unsafe method.
      // (Retries reuse the server's stored result via the SAME key, so we only
      // generate one and preserve it across attempts.)
      if (attempt === 0 && this.useIdempotency && isIdempotencyCandidate(method)) {{
        if (!(IDEMPOTENCY_HEADER in headers)) headers[IDEMPOTENCY_HEADER] = newIdempotencyKey();
      }}

      // Compose caller's signal with our timeout signal.
      const timeoutMs = requestOptions?.timeoutMs ?? this.timeoutMs;
      const callerSignal = requestOptions?.signal;
      const ownController = "AbortController" in globalThis ? new AbortController() : undefined;
      const startedAt = Date.now();
      const timer = ownController ? setTimeout(() => ownController.abort(), timeoutMs) : undefined;
      // If the caller aborts, propagate to our controller too.
      const onCallerAbort = callerSignal ? () => ownController?.abort() : undefined;
      callerSignal?.addEventListener("abort", onCallerAbort!, {{ once: true }});

      this.logger.info(`[request] ${{method}} ${{url}}${{attempt > 0 ? ` (attempt ${{attempt + 1}})` : ""}}`);

      // Build the request descriptor for middleware.
      const mwReq: MiddlewareRequest = {{
        method,
        url,
        headers,
        body: serializeBody(requestOptions),
        signal: ownController?.signal,
      }};

      // Wrap fetch with the middleware chain.
      const handler = composeMiddleware(this.middlewares, (req) =>
        this.fetchImpl(req.url, {{
          method: req.method,
          headers: req.headers,
          body: req.body,
          signal: req.signal,
        }}),
      );

      try {{
        const response = await handler(mwReq);
        if (timer) clearTimeout(timer);
        callerSignal?.removeEventListener("abort", onCallerAbort!);

        if (response.ok) {{
          this.logger.info(`[response] ${{method}} ${{url}} -> ${{response.status}}`);
          return response;
        }}

        const shouldRetry =
          attempt < maxRetries &&
          retryable &&
          this.retry.retryOnStatuses.includes(response.status);
        if (shouldRetry) {{
          this.logger.warn(`[retry] ${{method}} ${{url}} status=${{response.status}}, attempt ${{attempt + 2}}/${{maxRetries + 1}}`);
          await sleep(backoffDelay(attempt, this.retry));
          continue;
        }}

        const body = await parseBody(response);
        throw httpError(response.status, body, url, response.statusText || `HTTP ${{response.status}}`);
      }} catch (e) {{
        if (timer) clearTimeout(timer);
        callerSignal?.removeEventListener("abort", onCallerAbort!);
        if (isApiError(e)) throw e;
        // Distinguish caller-cancelled from our-timeout from network.
        if (callerSignal?.aborted) throw networkError(e, "request aborted by caller");
        if (e instanceof DOMException && e.name === "AbortError") {{
          throw timeoutError(Date.now() - startedAt);
        }}
        if (attempt < maxRetries && retryable) {{
          this.logger.warn(`[retry] ${{method}} ${{url}} error=${{(e as Error)?.message}}, attempt ${{attempt + 2}}/${{maxRetries + 1}}`);
          await sleep(backoffDelay(attempt, this.retry));
          continue;
        }}
        throw networkError(e, (e as Error)?.message ?? "network error");
      }}
    }}
    throw configurationError("exhausted retries without a response");
  }}

  /** Convenience: request + parse JSON body. Throws typed errors on !ok. */
  async requestJson<T>(method: string, path: string, requestOptions?: RequestOptions): Promise<T> {{
    // Apply request interceptors to the body before sending.
    let body = requestOptions?.body;
    for (const interceptor of this.requestInterceptors) {{
      body = interceptor.transform(body);
    }}
    const interceptedOptions = requestOptions ? {{ ...requestOptions, body }} : undefined;
    const response = await this.request(method, path, interceptedOptions);
    let result = (await parseBody(response)) as T;
    // Apply response interceptors after parsing.
    for (const interceptor of this.responseInterceptors) {{
      result = interceptor.transform(result) as T;
    }}
    for (const t of this.responseTransformers) {{
      result = t.transform(result) as T;
    }}
    return result;
  }}
}}

/** A query value. Scalars and arrays are rendered directly; objects/unknown
 *  (e.g. deepObject-style structured params) are JSON-encoded. The value type
 *  is intentionally permissive (`unknown`) because OpenAPI query params can be
 *  arbitrary structured schemas; the encoder stringifies anything non-scalar. */
export type QueryRecord = Record<string, unknown>;

export interface RequestOptions {{
  query?: QueryRecord;
  headers?: Record<string, string>;
  /** JSON body (serialized automatically), or a pre-built BodyInit (FormData,
   *  Blob, etc.) for multipart uploads / raw payloads. */
  body?: unknown;
  /** Per-call timeout override in ms. */
  timeoutMs?: number;
  /** Caller-provided cancellation signal. Aborting rejects the promise. */
  signal?: AbortSignal;
  retry?: {{ maxRetries?: number; retryable?: boolean }};
}}

/** URL-encode a query record, skipping undefined/null. Array values repeat the
 *  key (?k=a&k=b); scalars use a single occurrence; objects are JSON-encoded. */
export function encodeQuery(query: QueryRecord): string {{
  const sp = new URLSearchParams();
  for (const [k, v] of Object.entries(query)) {{
    if (v === undefined || v === null) continue;
    if (Array.isArray(v)) {{
      for (const item of v) sp.append(k, encodeQueryItem(item));
    }} else {{
      sp.set(k, encodeQueryItem(v));
    }}
  }}
  return sp.toString();
}}

function encodeQueryItem(v: unknown): string {{
  if (typeof v === "string" || typeof v === "number" || typeof v === "boolean") return String(v);
  return JSON.stringify(v);
}}

/** Serialize a request body: pass through BodyInit (FormData/Blob/string),
 *  JSON-encode plain objects, drop undefined. */
function serializeBody(requestOptions: RequestOptions | undefined): BodyInit | undefined {{
  const body = requestOptions?.body;
  if (body === undefined || body === null) return undefined;
  // BodyInit covers FormData, Blob, ArrayBuffer, URLSearchParams, ReadableStream, string.
  if (typeof body === "string") return body;
  if (typeof (body as BodyInit).toString === "function" && isBodyInit(body)) return body as BodyInit;
  return JSON.stringify(body);
}}

function isBodyInit(v: unknown): boolean {{
  return (
    v instanceof FormData ||
    v instanceof Blob ||
    v instanceof ArrayBuffer ||
    v instanceof URLSearchParams ||
    (typeof ReadableStream !== "undefined" && v instanceof ReadableStream)
  );
}}

async function parseBody(response: Response): Promise<unknown> {{
  const text = await response.text();
  if (!text) return undefined;
  try {{
    return JSON.parse(text);
  }} catch {{
    return text;
  }}
}}

/**
 * Create an options object with automatic validation middleware pre-registered.
 * Pass the schemas map to enable request/response validation for all requests
 * matching the given route patterns.
 *
 * Usage:
 * ```ts
 * import {{ createClient, withValidation, PetSchema }} from "./sdk";
 *
 * const schemas = {{
 *   "POST /pets": {{ requestBody: PetSchema, responseBody: PetSchema }},
 *   "GET /pets/{{petId}}": {{ responseBody: PetSchema }},
 * }};
 *
 * const client = createClient(withValidation(schemas));
 * ```
 */
export function withValidation(schemas: RouteSchemaMap): ApiClientOptions {{
  return {{
    middleware: [createValidationMiddleware(schemas)],
  }};
}}

export type {{ ApiError }};
"#,
        default_base = default_base,
    )
}
