//! Small emission helpers shared across model/operation/runtime generators.

use std::path::Path;

/// Standard file header comment. Includes a "do not edit" notice because all
/// emitted files are generated.
pub fn file_header() -> String {
    "/* eslint-disable */\n// This file is generated by specforge. DO NOT EDIT.\n".to_string()
}

/// Express `abs` relative to `base` as a forward-slashed string. Falls back to
/// the absolute path if `abs` isn't under `base`.
pub fn path_str(abs: &Path, base: &Path) -> String {
    abs.strip_prefix(base)
        .map(|p| p.to_string_lossy().into_owned())
        .unwrap_or_else(|_| abs.to_string_lossy().into_owned())
}

/// Indent every line of `s` by `n` spaces.
pub fn indent(s: &str, n: usize) -> String {
    let pad = " ".repeat(n);
    s.lines()
        .map(|line| format!("{pad}{line}"))
        .collect::<Vec<_>>()
        .join("\n")
}

/// Join non-empty lines with `\n`. Handy for building up file bodies from
/// optional sections.
pub fn join_lines(parts: impl IntoIterator<Item = Option<String>>) -> String {
    parts
        .into_iter()
        .flatten()
        .filter(|s| !s.is_empty())
        .collect::<Vec<_>>()
        .join("\n")
}
